# Metadata
mod_name=SecurityCraft
mod_id=securitycraft
authors=Geforce, bl4ckscor3, Redstone_Dubstep, and ChainmailPickaxe

# Versions
mod_version=1.10.2.1-beta1
mc_version=26.2
mc_min_version=26.2
port=false
porting_pr=3198
neoforge_version=26.2.0.7-beta
neoforge_min_version=26.2.0.0-beta
mdg_version=2.0.141
java_version=25

# Mod dependencies
ftb_library=7971743
ftb_teams=7972096
jei=8292647
top=5502323
jade=8281956
betterf3=7952333
cloth_config=7817583
wthit=7880673
badpackets=7878544
projecte=3955047
embeddium=6116910
sodium_mc=26.2
sodium_self=0.9.0
distant_horizons=8287428
curios=7925547

# Gradle
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=false
org.gradle.parallel=true
