package net.geforcemods.securitycraft;

import net.geforcemods.securitycraft.blocks.BlockAlarm;
import net.geforcemods.securitycraft.blocks.BlockCageTrap;
import net.geforcemods.securitycraft.blocks.BlockFakeLava;
import net.geforcemods.securitycraft.blocks.BlockFakeWater;
import net.geforcemods.securitycraft.blocks.BlockFrame;
import net.geforcemods.securitycraft.blocks.BlockInventoryScanner;
import net.geforcemods.securitycraft.blocks.BlockInventoryScannerField;
import net.geforcemods.securitycraft.blocks.BlockIronFence;
import net.geforcemods.securitycraft.blocks.BlockIronTrapDoor;
import net.geforcemods.securitycraft.blocks.BlockKeycardReader;
import net.geforcemods.securitycraft.blocks.BlockKeypad;
import net.geforcemods.securitycraft.blocks.BlockKeypadChest;
import net.geforcemods.securitycraft.blocks.BlockKeypadFurnace;
import net.geforcemods.securitycraft.blocks.BlockLaserBlock;
import net.geforcemods.securitycraft.blocks.BlockLaserField;
import net.geforcemods.securitycraft.blocks.BlockLogger;
import net.geforcemods.securitycraft.blocks.BlockMotionActivatedLight;
import net.geforcemods.securitycraft.blocks.BlockPanicButton;
import net.geforcemods.securitycraft.blocks.BlockPortableRadar;
import net.geforcemods.securitycraft.blocks.BlockProtecto;
import net.geforcemods.securitycraft.blocks.BlockRetinalScanner;
import net.geforcemods.securitycraft.blocks.BlockScannerDoor;
import net.geforcemods.securitycraft.blocks.BlockSecretSignStanding;
import net.geforcemods.securitycraft.blocks.BlockSecretSignWall;
import net.geforcemods.securitycraft.blocks.BlockSecurityCamera;
import net.geforcemods.securitycraft.blocks.BlockTrophySystem;
import net.geforcemods.securitycraft.blocks.mines.BlockBouncingBetty;
import net.geforcemods.securitycraft.blocks.mines.BlockClaymore;
import net.geforcemods.securitycraft.blocks.mines.BlockFullMineBase;
import net.geforcemods.securitycraft.blocks.mines.BlockFullMineFalling;
import net.geforcemods.securitycraft.blocks.mines.BlockFurnaceMine;
import net.geforcemods.securitycraft.blocks.mines.BlockIMS;
import net.geforcemods.securitycraft.blocks.mines.BlockMine;
import net.geforcemods.securitycraft.blocks.mines.BlockTrackMine;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedBase;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedCarpet;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedDoor;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedFalling;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedFenceGate;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedGlass;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedPane;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedRotatedPillar;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedSlab;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedStainedGlass;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedStainedGlassPane;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedStairs;
import net.geforcemods.securitycraft.fluids.FakeLavaFluid;
import net.geforcemods.securitycraft.fluids.FakeWaterFluid;
import net.geforcemods.securitycraft.gui.GuiHandler;
import net.geforcemods.securitycraft.items.ItemAdminTool;
import net.geforcemods.securitycraft.items.ItemBriefcase;
import net.geforcemods.securitycraft.items.ItemCameraMonitor;
import net.geforcemods.securitycraft.items.ItemCodebreaker;
import net.geforcemods.securitycraft.items.ItemKeyPanel;
import net.geforcemods.securitycraft.items.ItemKeycardBase;
import net.geforcemods.securitycraft.items.ItemMineRemoteAccessTool;
import net.geforcemods.securitycraft.items.ItemModule;
import net.geforcemods.securitycraft.items.ItemReinforcedDoor;
import net.geforcemods.securitycraft.items.ItemSCManual;
import net.geforcemods.securitycraft.items.ItemScannerDoor;
import net.geforcemods.securitycraft.items.ItemSecretSign;
import net.geforcemods.securitycraft.items.ItemSentry;
import net.geforcemods.securitycraft.items.ItemTaser;
import net.geforcemods.securitycraft.items.ItemUniversalBlockReinforcer;
import net.geforcemods.securitycraft.items.ItemUniversalKeyChanger;
import net.geforcemods.securitycraft.items.ItemUniversalOwnerChanger;
import net.geforcemods.securitycraft.misc.EnumCustomModules;
import net.minecraft.block.BlockFlowingFluid;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.item.EnumDyeColor;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBucket;
import net.minecraft.util.ResourceLocation;

public class SetupHandler
{
	public static void setupFluids()
	{
		SCContent.flowingFakeWater = new FakeWaterFluid.Flowing();
		SCContent.fakeWater = new FakeWaterFluid.Source();
		SCContent.flowingFakeLava = new FakeLavaFluid.Flowing();
		SCContent.fakeLava = new FakeLavaFluid.Source();
	}

	public static void setupBlocks()
	{
		SCContent.laserBlock = new BlockLaserBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "laser_block"));
		SCContent.laserField = new BlockLaserField(Material.ROCK).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "laser"));
		SCContent.keypad = new BlockKeypad(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keypad"));
		SCContent.retinalScanner = new BlockRetinalScanner(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "retinal_scanner"));
		SCContent.reinforcedDoor = new BlockReinforcedDoor(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "iron_door_reinforced"));
		SCContent.keycardReader = new BlockKeycardReader(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keycard_reader"));
		SCContent.ironTrapdoor = new BlockIronTrapDoor(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "reinforced_iron_trapdoor"));
		SCContent.inventoryScanner = new BlockInventoryScanner(Material.ROCK).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "inventory_scanner"));
		SCContent.inventoryScannerField = new BlockInventoryScannerField(Material.GLASS).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "inventory_scanner_field"));
		SCContent.cageTrap = new BlockCageTrap(Material.ROCK).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "cage_trap"));
		SCContent.portableRadar = new BlockPortableRadar(Material.CIRCUITS).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "portable_radar"));
		SCContent.keypadChest = new BlockKeypadChest().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keypad_chest"));
		SCContent.usernameLogger = new BlockLogger(Material.ROCK).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "username_logger"));
		SCContent.alarm = new BlockAlarm().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "alarm"));
		SCContent.reinforcedFencegate = new BlockReinforcedFenceGate().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "reinforced_fence_gate"));
		SCContent.panicButton = new BlockPanicButton().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "panic_button"));
		SCContent.frame = new BlockFrame(Material.ROCK).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keypad_frame"));
		SCContent.keypadFurnace = new BlockKeypadFurnace(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keypad_furnace"));
		SCContent.securityCamera = new BlockSecurityCamera(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "security_camera"));
		SCContent.ironFence = new BlockIronFence(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "electrified_iron_fence"));
		SCContent.protecto = new BlockProtecto(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "protecto"));
		SCContent.scannerDoor = new BlockScannerDoor(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "scanner_door"));
		SCContent.secretSignStanding = new BlockSecretSignStanding().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_sign_standing"));
		SCContent.secretSignWall = new BlockSecretSignWall().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_sign_wall"));
		SCContent.motionActivatedLight = new BlockMotionActivatedLight(Material.GLASS).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "motion_activated_light"));
		SCContent.fakeWaterBlock = (BlockFlowingFluid)new BlockFakeWater().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "fake_water_block"));
		SCContent.fakeLavaBlock = (BlockFlowingFluid)new BlockFakeLava().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "fake_lava_block"));
		SCContent.trophySystem = new BlockTrophySystem(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "trophy_system"));
	}

	public static void setupReinforcedBlocks()
	{
		//ordered by vanilla building blocks creative tab order
		SCContent.reinforcedStone = new BlockReinforcedBase(Material.ROCK, Blocks.STONE, "reinforced_stone");
		SCContent.reinforcedGranite = new BlockReinforcedBase(Material.ROCK, Blocks.GRANITE, "reinforced_granite");
		SCContent.reinforcedPolishedGranite = new BlockReinforcedBase(Material.ROCK, Blocks.POLISHED_GRANITE, "reinforced_polished_granite");
		SCContent.reinforcedDiorite = new BlockReinforcedBase(Material.ROCK, Blocks.DIORITE, "reinforced_diorite");
		SCContent.reinforcedPolishedDiorite = new BlockReinforcedBase(Material.ROCK, Blocks.POLISHED_DIORITE, "reinforced_polished_diorite");
		SCContent.reinforcedAndesite = new BlockReinforcedBase(Material.ROCK, Blocks.ANDESITE, "reinforced_andesite");
		SCContent.reinforcedPolishedAndesite = new BlockReinforcedBase(Material.ROCK, Blocks.POLISHED_ANDESITE, "reinforced_polished_andesite");
		SCContent.reinforcedDirt = new BlockReinforcedBase(SoundType.GROUND, Material.GROUND, Blocks.DIRT, "reinforced_dirt");
		SCContent.reinforcedCobblestone = new BlockReinforcedBase(Material.ROCK, Blocks.COBBLESTONE, "reinforced_cobblestone");
		SCContent.reinforcedOakPlanks = new BlockReinforcedBase(SoundType.WOOD, Material.WOOD, Blocks.OAK_PLANKS, "reinforced_oak_planks");
		SCContent.reinforcedSprucePlanks = new BlockReinforcedBase(SoundType.WOOD, Material.WOOD, Blocks.SPRUCE_PLANKS, "reinforced_spruce_planks");
		SCContent.reinforcedBirchPlanks = new BlockReinforcedBase(SoundType.WOOD, Material.WOOD, Blocks.BIRCH_PLANKS, "reinforced_birch_planks");
		SCContent.reinforcedJunglePlanks = new BlockReinforcedBase(SoundType.WOOD, Material.WOOD, Blocks.JUNGLE_PLANKS, "reinforced_jungle_planks");
		SCContent.reinforcedAcaciaPlanks = new BlockReinforcedBase(SoundType.WOOD, Material.WOOD, Blocks.ACACIA_PLANKS, "reinforced_acacia_planks");
		SCContent.reinforcedDarkOakPlanks = new BlockReinforcedBase(SoundType.WOOD, Material.WOOD, Blocks.DARK_OAK_PLANKS, "reinforced_dark_oak_planks");
		SCContent.reinforcedSand = new BlockReinforcedFalling(SoundType.SAND, Material.SAND, Blocks.SAND, "reinforced_sand");
		SCContent.reinforcedGravel = new BlockReinforcedFalling(SoundType.GROUND, Material.GROUND, Blocks.GRAVEL, "reinforced_gravel");
		SCContent.reinforcedOakLog = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.OAK_LOG, "reinforced_oak_log");
		SCContent.reinforcedSpruceLog = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.SPRUCE_LOG, "reinforced_spruce_log");
		SCContent.reinforcedBirchLog = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.BIRCH_LOG, "reinforced_birch_log");
		SCContent.reinforcedJungleLog = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.JUNGLE_LOG, "reinforced_jungle_log");
		SCContent.reinforcedAcaciaLog = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.ACACIA_LOG, "reinforced_acacia_log");
		SCContent.reinforcedDarkOakLog = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.DARK_OAK_LOG, "reinforced_dark_oak_log");
		SCContent.reinforcedStrippedOakLog = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_OAK_LOG, "reinforced_stripped_oak_log");
		SCContent.reinforcedStrippedSpruceLog = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_SPRUCE_LOG, "reinforced_stripped_spruce_log");
		SCContent.reinforcedStrippedBirchLog = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_BIRCH_LOG, "reinforced_stripped_birch_log");
		SCContent.reinforcedStrippedJungleLog = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_JUNGLE_LOG, "reinforced_stripped_jungle_log");
		SCContent.reinforcedStrippedAcaciaLog = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_ACACIA_LOG, "reinforced_stripped_acacia_log");
		SCContent.reinforcedStrippedDarkOakLog = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_DARK_OAK_LOG, "reinforced_stripped_dark_oak_log");
		SCContent.reinforcedStrippedOakWood = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_OAK_WOOD, "reinforced_stripped_oak_wood");
		SCContent.reinforcedStrippedSpruceWood = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_SPRUCE_WOOD, "reinforced_stripped_spruce_wood");
		SCContent.reinforcedStrippedBirchWood = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_BIRCH_WOOD, "reinforced_stripped_birch_wood");
		SCContent.reinforcedStrippedJungleWood = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_JUNGLE_WOOD, "reinforced_stripped_jungle_wood");
		SCContent.reinforcedStrippedAcaciaWood = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_ACACIA_WOOD, "reinforced_stripped_acacia_wood");
		SCContent.reinforcedStrippedDarkOakWood = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_DARK_OAK_WOOD, "reinforced_stripped_dark_oak_wood");
		SCContent.reinforcedOakWood = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.OAK_WOOD, "reinforced_oak_wood");
		SCContent.reinforcedSpruceWood = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.SPRUCE_WOOD, "reinforced_spruce_wood");
		SCContent.reinforcedBirchWood = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.BIRCH_WOOD, "reinforced_birch_wood");
		SCContent.reinforcedJungleWood = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.JUNGLE_WOOD, "reinforced_jungle_wood");
		SCContent.reinforcedAcaciaWood = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.ACACIA_WOOD, "reinforced_acacia_wood");
		SCContent.reinforcedDarkOakWood = new BlockReinforcedRotatedPillar(SoundType.WOOD, Material.WOOD, Blocks.DARK_OAK_WOOD, "reinforced_dark_oak_wood");
		SCContent.reinforcedGlass = new BlockReinforcedGlass(Blocks.GLASS, "reinforced_glass");
		SCContent.reinforcedLapisBlock = new BlockReinforcedBase(Material.ROCK, Blocks.LAPIS_BLOCK, "reinforced_lapis_block");
		SCContent.reinforcedSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.SANDSTONE, "reinforced_sandstone");
		SCContent.reinforcedChiseledSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.CHISELED_SANDSTONE, "reinforced_chiseled_sandstone");
		SCContent.reinforcedCutSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.CUT_SANDSTONE, "reinforced_cut_sandstone");
		SCContent.reinforcedWhiteWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.WHITE_WOOL, "reinforced_white_wool");
		SCContent.reinforcedOrangeWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.ORANGE_WOOL, "reinforced_orange_wool");
		SCContent.reinforcedMagentaWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.MAGENTA_WOOL, "reinforced_magenta_wool");
		SCContent.reinforcedLightBlueWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.LIGHT_BLUE_WOOL, "reinforced_light_blue_wool");
		SCContent.reinforcedYellowWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.YELLOW_WOOL, "reinforced_yellow_wool");
		SCContent.reinforcedLimeWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.LIME_WOOL, "reinforced_lime_wool");
		SCContent.reinforcedPinkWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.PINK_WOOL, "reinforced_pink_wool");
		SCContent.reinforcedGrayWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.GRAY_WOOL, "reinforced_gray_wool");
		SCContent.reinforcedLightGrayWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.LIGHT_GRAY_WOOL, "reinforced_light_gray_wool");
		SCContent.reinforcedCyanWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.CYAN_WOOL, "reinforced_cyan_wool");
		SCContent.reinforcedPurpleWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.PURPLE_WOOL, "reinforced_purple_wool");
		SCContent.reinforcedBlueWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.BLUE_WOOL, "reinforced_blue_wool");
		SCContent.reinforcedBrownWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.BROWN_WOOL, "reinforced_brown_wool");
		SCContent.reinforcedGreenWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.GREEN_WOOL, "reinforced_green_wool");
		SCContent.reinforcedRedWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.RED_WOOL, "reinforced_red_wool");
		SCContent.reinforcedBlackWool = new BlockReinforcedBase(SoundType.CLOTH, Material.CLOTH, Blocks.BLACK_WOOL, "reinforced_black_wool");
		SCContent.reinforcedGoldBlock = new BlockReinforcedBase(SoundType.METAL, Material.IRON, Blocks.GOLD_BLOCK, "reinforced_gold_block");
		SCContent.reinforcedIronBlock = new BlockReinforcedBase(SoundType.METAL, Material.IRON, Blocks.IRON_BLOCK, "reinforced_iron_block");
		SCContent.reinforcedOakSlab = new BlockReinforcedSlab(SoundType.WOOD, Material.WOOD, Blocks.OAK_SLAB, "reinforced_oak_slab");
		SCContent.reinforcedSpruceSlab = new BlockReinforcedSlab(SoundType.WOOD, Material.WOOD, Blocks.SPRUCE_SLAB, "reinforced_spruce_slab");
		SCContent.reinforcedBirchSlab = new BlockReinforcedSlab(SoundType.WOOD, Material.WOOD, Blocks.BIRCH_SLAB, "reinforced_birch_slab");
		SCContent.reinforcedJungleSlab = new BlockReinforcedSlab(SoundType.WOOD, Material.WOOD, Blocks.JUNGLE_SLAB, "reinforced_jungle_slab");
		SCContent.reinforcedAcaciaSlab = new BlockReinforcedSlab(SoundType.WOOD, Material.WOOD, Blocks.ACACIA_SLAB, "reinforced_acacia_slab");
		SCContent.reinforcedDarkOakSlab = new BlockReinforcedSlab(SoundType.WOOD, Material.WOOD, Blocks.DARK_OAK_SLAB, "reinforced_dark_oak_slab");
		SCContent.reinforcedStoneSlab = new BlockReinforcedSlab(SoundType.STONE, Material.ROCK, Blocks.STONE_SLAB, "reinforced_stone_slab");
		SCContent.reinforcedSandstoneSlab = new BlockReinforcedSlab(SoundType.STONE, Material.ROCK, Blocks.SANDSTONE_SLAB, "reinforced_sandstone_slab");
		SCContent.reinforcedCobblestoneSlab = new BlockReinforcedSlab(SoundType.STONE, Material.ROCK, Blocks.COBBLESTONE_SLAB, "reinforced_cobblestone_slab");
		SCContent.reinforcedBrickSlab = new BlockReinforcedSlab(SoundType.STONE, Material.ROCK, Blocks.BRICK_SLAB, "reinforced_brick_slab");
		SCContent.reinforcedStoneBrickSlab = new BlockReinforcedSlab(SoundType.STONE, Material.ROCK, Blocks.STONE_BRICK_SLAB, "reinforced_stone_brick_slab");
		SCContent.reinforcedNetherBrickSlab = new BlockReinforcedSlab(SoundType.STONE, Material.ROCK, Blocks.NETHER_BRICK_SLAB, "reinforced_nether_brick_slab");
		SCContent.reinforcedQuartzSlab = new BlockReinforcedSlab(SoundType.STONE, Material.ROCK, Blocks.QUARTZ_SLAB, "reinforced_quartz_slab");
		SCContent.reinforcedRedSandstoneSlab = new BlockReinforcedSlab(SoundType.STONE, Material.ROCK, Blocks.RED_SANDSTONE_SLAB, "reinforced_red_sandstone_slab");
		SCContent.reinforcedPurpurSlab = new BlockReinforcedSlab(SoundType.STONE, Material.ROCK, Blocks.PURPUR_SLAB, "reinforced_purpur_slab");
		SCContent.reinforcedPrismarineSlab = new BlockReinforcedSlab(SoundType.STONE, Material.ROCK, Blocks.PRISMARINE_SLAB, "reinforced_prismarine_slab");
		SCContent.reinforcedPrismarineBrickSlab = new BlockReinforcedSlab(SoundType.STONE, Material.ROCK, Blocks.PRISMARINE_BRICK_SLAB, "reinforced_prismarine_brick_slab");
		SCContent.reinforcedDarkPrismarineSlab = new BlockReinforcedSlab(SoundType.STONE, Material.ROCK, Blocks.DARK_PRISMARINE_SLAB, "reinforced_dark_prismarine_slab");
		SCContent.reinforcedSmoothQuartz = new BlockReinforcedBase(Material.ROCK, Blocks.SMOOTH_QUARTZ, "reinforced_smooth_quartz");
		SCContent.reinforcedSmoothRedSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.SMOOTH_RED_SANDSTONE, "reinforced_smooth_red_sandstone");
		SCContent.reinforcedSmoothSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.SMOOTH_SANDSTONE, "reinforced_smooth_sandstone");
		SCContent.reinforcedSmoothStone = new BlockReinforcedBase(Material.ROCK, Blocks.SMOOTH_STONE, "reinforced_smooth_stone");
		SCContent.reinforcedBricks = new BlockReinforcedBase(Material.ROCK, Blocks.BRICKS, "reinforced_bricks");
		SCContent.reinforcedMossyCobblestone = new BlockReinforcedBase(Material.ROCK, Blocks.MOSSY_COBBLESTONE, "reinforced_mossy_cobblestone");
		SCContent.reinforcedObsidian = new BlockReinforcedBase(Material.ROCK, Blocks.OBSIDIAN, "reinforced_obsidian");
		SCContent.reinforcedPurpurBlock = new BlockReinforcedBase(Material.ROCK, Blocks.PURPUR_BLOCK, "reinforced_purpur_block");
		SCContent.reinforcedPurpurPillar = new BlockReinforcedRotatedPillar(Material.ROCK, Blocks.PURPUR_PILLAR, "reinforced_purpur_pillar");
		SCContent.reinforcedPurpurStairs = new BlockReinforcedStairs(SoundType.STONE, Material.ROCK, Blocks.PURPUR_STAIRS, "reinforced_purpur_stairs");
		SCContent.reinforcedOakStairs = new BlockReinforcedStairs(SoundType.WOOD, Material.WOOD, Blocks.OAK_STAIRS, "reinforced_oak_stairs");
		SCContent.reinforcedDiamondBlock = new BlockReinforcedBase(SoundType.METAL, Material.IRON, Blocks.DIAMOND_BLOCK, "reinforced_diamond_block");
		SCContent.reinforcedCobblestoneStairs = new BlockReinforcedStairs(SoundType.STONE, Material.ROCK, Blocks.COBBLESTONE_STAIRS, "reinforced_cobblestone_stairs");
		SCContent.reinforcedNetherrack = new BlockReinforcedBase(Material.ROCK, Blocks.NETHERRACK, "reinforced_netherrack");
		SCContent.reinforcedGlowstone = new BlockReinforcedBase(SoundType.GLASS, Material.GLASS, Blocks.GLOWSTONE, "reinforced_glowstone", 15);
		SCContent.reinforcedStoneBricks = new BlockReinforcedBase(Material.ROCK, Blocks.STONE_BRICKS, "reinforced_stone_bricks");
		SCContent.reinforcedMossyStoneBricks = new BlockReinforcedBase(Material.ROCK, Blocks.MOSSY_STONE_BRICKS, "reinforced_mossy_stone_bricks");
		SCContent.reinforcedCrackedStoneBricks = new BlockReinforcedBase(Material.ROCK, Blocks.CRACKED_STONE_BRICKS, "reinforced_cracked_stone_bricks");
		SCContent.reinforcedChiseledStoneBricks = new BlockReinforcedBase(Material.ROCK, Blocks.CHISELED_STONE_BRICKS, "reinforced_chiseled_stone_bricks");
		SCContent.reinforcedBrickStairs = new BlockReinforcedStairs(SoundType.STONE, Material.ROCK, Blocks.BRICK_STAIRS, "reinforced_brick_stairs");
		SCContent.reinforcedStoneBrickStairs = new BlockReinforcedStairs(SoundType.STONE, Material.ROCK, Blocks.STONE_BRICK_STAIRS, "reinforced_stone_brick_stairs");
		SCContent.reinforcedNetherBricks = new BlockReinforcedBase(Material.ROCK, Blocks.NETHER_BRICKS, "reinforced_nether_bricks");
		SCContent.reinforcedNetherBrickStairs = new BlockReinforcedStairs(SoundType.STONE, Material.ROCK, Blocks.NETHER_BRICK_STAIRS, "reinforced_nether_brick_stairs");
		SCContent.reinforcedEndStone = new BlockReinforcedBase(Material.ROCK, Blocks.END_STONE, "reinforced_end_stone");
		SCContent.reinforcedEndStoneBricks = new BlockReinforcedBase(Material.ROCK, Blocks.END_STONE_BRICKS, "reinforced_end_stone_bricks");
		SCContent.reinforcedSandstoneStairs = new BlockReinforcedStairs(SoundType.STONE, Material.ROCK, Blocks.SANDSTONE_STAIRS, "reinforced_sandstone_stairs");
		SCContent.reinforcedEmeraldBlock = new BlockReinforcedBase(SoundType.METAL, Material.IRON, Blocks.EMERALD_BLOCK, "reinforced_emerald_block");
		SCContent.reinforcedSpruceStairs = new BlockReinforcedStairs(SoundType.WOOD, Material.WOOD, Blocks.SPRUCE_STAIRS, "reinforced_spruce_stairs");
		SCContent.reinforcedBirchStairs = new BlockReinforcedStairs(SoundType.WOOD, Material.WOOD, Blocks.BIRCH_STAIRS, "reinforced_birch_stairs");
		SCContent.reinforcedJungleStairs = new BlockReinforcedStairs(SoundType.WOOD, Material.WOOD, Blocks.JUNGLE_STAIRS, "reinforced_jungle_stairs");
		SCContent.reinforcedChiseledQuartz = new BlockReinforcedBase(Material.ROCK, Blocks.CHISELED_QUARTZ_BLOCK, "reinforced_chiseled_quartz_block");
		SCContent.reinforcedQuartz = new BlockReinforcedBase(Material.ROCK, Blocks.QUARTZ_BLOCK, "reinforced_quartz_block");
		SCContent.reinforcedQuartzPillar = new BlockReinforcedRotatedPillar(Material.ROCK, Blocks.QUARTZ_PILLAR, "reinforced_quartz_pillar");
		SCContent.reinforcedQuartzStairs = new BlockReinforcedStairs(SoundType.STONE, Material.ROCK, Blocks.QUARTZ_STAIRS, "reinforced_quartz_stairs");
		SCContent.reinforcedWhiteTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.WHITE_TERRACOTTA, "reinforced_white_terracotta");
		SCContent.reinforcedOrangeTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.ORANGE_TERRACOTTA, "reinforced_orange_terracotta");
		SCContent.reinforcedMagentaTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.MAGENTA_TERRACOTTA, "reinforced_magenta_terracotta");
		SCContent.reinforcedLightBlueTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.LIGHT_BLUE_TERRACOTTA, "reinforced_light_blue_terracotta");
		SCContent.reinforcedYellowTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.YELLOW_TERRACOTTA, "reinforced_yellow_terracotta");
		SCContent.reinforcedLimeTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.LIME_TERRACOTTA, "reinforced_lime_terracotta");
		SCContent.reinforcedPinkTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.PINK_TERRACOTTA, "reinforced_pink_terracotta");
		SCContent.reinforcedGrayTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.GRAY_TERRACOTTA, "reinforced_gray_terracotta");
		SCContent.reinforcedLightGrayTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.LIGHT_GRAY_TERRACOTTA, "reinforced_light_gray_terracotta");
		SCContent.reinforcedCyanTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.CYAN_TERRACOTTA, "reinforced_cyan_terracotta");
		SCContent.reinforcedPurpleTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.PURPLE_TERRACOTTA, "reinforced_purple_terracotta");
		SCContent.reinforcedBlueTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.BLUE_TERRACOTTA, "reinforced_blue_terracotta");
		SCContent.reinforcedBrownTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.BROWN_TERRACOTTA, "reinforced_brown_terracotta");
		SCContent.reinforcedGreenTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.GREEN_TERRACOTTA, "reinforced_green_terracotta");
		SCContent.reinforcedRedTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.RED_TERRACOTTA, "reinforced_red_terracotta");
		SCContent.reinforcedBlackTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.BLACK_TERRACOTTA, "reinforced_black_terracotta");
		SCContent.reinforcedTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.TERRACOTTA, "reinforced_hardened_clay");
		SCContent.reinforcedCoalBlock = new BlockReinforcedBase(Material.ROCK, Blocks.COAL_BLOCK, "reinforced_coal_block");
		SCContent.reinforcedAcaciaStairs = new BlockReinforcedStairs(SoundType.WOOD, Material.WOOD, Blocks.ACACIA_STAIRS, "reinforced_acacia_stairs");
		SCContent.reinforcedDarkOakStairs = new BlockReinforcedStairs(SoundType.WOOD, Material.WOOD, Blocks.DARK_OAK_STAIRS, "reinforced_dark_oak_stairs");
		SCContent.reinforcedWhiteStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.WHITE, Blocks.WHITE_STAINED_GLASS, "reinforced_white_stained_glass");
		SCContent.reinforcedOrangeStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.ORANGE, Blocks.ORANGE_STAINED_GLASS, "reinforced_orange_stained_glass");
		SCContent.reinforcedMagentaStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.MAGENTA, Blocks.MAGENTA_STAINED_GLASS, "reinforced_magenta_stained_glass");
		SCContent.reinforcedLightBlueStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_STAINED_GLASS, "reinforced_light_blue_stained_glass");
		SCContent.reinforcedYellowStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.YELLOW, Blocks.YELLOW_STAINED_GLASS, "reinforced_yellow_stained_glass");
		SCContent.reinforcedLimeStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.LIME, Blocks.LIME_STAINED_GLASS, "reinforced_lime_stained_glass");
		SCContent.reinforcedPinkStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.PINK, Blocks.PINK_STAINED_GLASS, "reinforced_pink_stained_glass");
		SCContent.reinforcedGrayStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.GRAY, Blocks.GRAY_STAINED_GLASS, "reinforced_gray_stained_glass");
		SCContent.reinforcedLightGrayStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_STAINED_GLASS, "reinforced_light_gray_stained_glass");
		SCContent.reinforcedCyanStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.CYAN, Blocks.CYAN_STAINED_GLASS, "reinforced_cyan_stained_glass");
		SCContent.reinforcedPurpleStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.PURPLE, Blocks.PURPLE_STAINED_GLASS, "reinforced_purple_stained_glass");
		SCContent.reinforcedBlueStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.BLUE, Blocks.BLUE_STAINED_GLASS, "reinforced_blue_stained_glass");
		SCContent.reinforcedBrownStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.BROWN, Blocks.BROWN_STAINED_GLASS, "reinforced_brown_stained_glass");
		SCContent.reinforcedGreenStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.GREEN, Blocks.GREEN_STAINED_GLASS, "reinforced_green_stained_glass");
		SCContent.reinforcedRedStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.RED, Blocks.RED_STAINED_GLASS, "reinforced_red_stained_glass");
		SCContent.reinforcedBlackStainedGlass = new BlockReinforcedStainedGlass(EnumDyeColor.BLACK, Blocks.BLACK_STAINED_GLASS, "reinforced_black_stained_glass");
		SCContent.reinforcedPrismarine = new BlockReinforcedBase(Material.ROCK, Blocks.PRISMARINE, "reinforced_prismarine");
		SCContent.reinforcedPrismarineBricks = new BlockReinforcedBase(Material.ROCK, Blocks.PRISMARINE_BRICKS, "reinforced_prismarine_bricks");
		SCContent.reinforcedDarkPrismarine = new BlockReinforcedBase(Material.ROCK, Blocks.DARK_PRISMARINE, "reinforced_dark_prismarine");
		SCContent.reinforcedPrismarineStairs = new BlockReinforcedStairs(SoundType.STONE, Material.ROCK, Blocks.PRISMARINE_STAIRS, "reinforced_prismarine_stairs");
		SCContent.reinforcedPrismarineBrickStairs = new BlockReinforcedStairs(SoundType.STONE, Material.ROCK, Blocks.PRISMARINE_BRICK_STAIRS, "reinforced_prismarine_brick_stairs");
		SCContent.reinforcedDarkPrismarineStairs = new BlockReinforcedStairs(SoundType.STONE, Material.ROCK, Blocks.DARK_PRISMARINE_STAIRS, "reinforced_dark_prismarine_stairs");
		SCContent.reinforcedSeaLantern = new BlockReinforcedBase(Material.GLASS, Blocks.SEA_LANTERN, "reinforced_sea_lantern", 15);
		SCContent.reinforcedRedSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.SANDSTONE, "reinforced_red_sandstone");
		SCContent.reinforcedChiseledRedSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.CHISELED_SANDSTONE, "reinforced_chiseled_red_sandstone");
		SCContent.reinforcedCutRedSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.CUT_SANDSTONE, "reinforced_cut_red_sandstone");
		SCContent.reinforcedRedSandstoneStairs = new BlockReinforcedStairs(SoundType.STONE, Material.ROCK, Blocks.RED_SANDSTONE_STAIRS, "reinforced_red_sandstone_stairs");
		SCContent.reinforcedRedNetherBricks = new BlockReinforcedBase(Material.ROCK, Blocks.RED_NETHER_BRICKS, "reinforced_red_nether_bricks");
		SCContent.reinforcedBoneBlock = new BlockReinforcedRotatedPillar(Material.ROCK, Blocks.BONE_BLOCK, "reinforced_bone_block");
		SCContent.reinforcedWhiteConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.WHITE_CONCRETE, "reinforced_white_concrete");
		SCContent.reinforcedOrangeConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.ORANGE_CONCRETE, "reinforced_orange_concrete");
		SCContent.reinforcedMagentaConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.MAGENTA_CONCRETE, "reinforced_magenta_concrete");
		SCContent.reinforcedLightBlueConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.LIGHT_BLUE_CONCRETE, "reinforced_light_blue_concrete");
		SCContent.reinforcedYellowConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.YELLOW_CONCRETE, "reinforced_yellow_concrete");
		SCContent.reinforcedLimeConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.LIME_CONCRETE, "reinforced_lime_concrete");
		SCContent.reinforcedPinkConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.PINK_CONCRETE, "reinforced_pink_concrete");
		SCContent.reinforcedGrayConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.GRAY_CONCRETE, "reinforced_gray_concrete");
		SCContent.reinforcedLightGrayConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.LIGHT_GRAY_CONCRETE, "reinforced_light_gray_concrete");
		SCContent.reinforcedCyanConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.CYAN_CONCRETE, "reinforced_cyan_concrete");
		SCContent.reinforcedPurpleConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.PURPLE_CONCRETE, "reinforced_purple_concrete");
		SCContent.reinforcedBlueConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.BLUE_CONCRETE, "reinforced_blue_concrete");
		SCContent.reinforcedBrownConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.BROWN_CONCRETE, "reinforced_brown_concrete");
		SCContent.reinforcedGreenConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.GREEN_CONCRETE, "reinforced_green_concrete");
		SCContent.reinforcedRedConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.RED_CONCRETE, "reinforced_red_concrete");
		SCContent.reinforcedBlackConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.BLACK_CONCRETE, "reinforced_black_concrete");
		//ordered by vanilla decoration blocks creative tab order
		SCContent.reinforcedIronBars = new BlockReinforcedPane(SoundType.METAL, Material.IRON, Blocks.IRON_BARS, "reinforced_iron_bars");
		SCContent.reinforcedGlassPane = new BlockReinforcedPane(SoundType.GLASS, Material.GLASS, Blocks.GLASS_PANE, "reinforced_glass_pane");
		SCContent.reinforcedWhiteCarpet = new BlockReinforcedCarpet(Blocks.WHITE_CARPET, "reinforced_white_carpet");
		SCContent.reinforcedOrangeCarpet = new BlockReinforcedCarpet(Blocks.ORANGE_CARPET, "reinforced_orange_carpet");
		SCContent.reinforcedMagentaCarpet = new BlockReinforcedCarpet(Blocks.MAGENTA_CARPET, "reinforced_magenta_carpet");
		SCContent.reinforcedLightBlueCarpet = new BlockReinforcedCarpet(Blocks.LIGHT_BLUE_CARPET, "reinforced_light_blue_carpet");
		SCContent.reinforcedYellowCarpet = new BlockReinforcedCarpet(Blocks.YELLOW_CARPET, "reinforced_yellow_carpet");
		SCContent.reinforcedLimeCarpet = new BlockReinforcedCarpet(Blocks.LIME_CARPET, "reinforced_lime_carpet");
		SCContent.reinforcedPinkCarpet = new BlockReinforcedCarpet(Blocks.PINK_CARPET, "reinforced_pink_carpet");
		SCContent.reinforcedGrayCarpet = new BlockReinforcedCarpet(Blocks.GRAY_CARPET, "reinforced_gray_carpet");
		SCContent.reinforcedLightGrayCarpet = new BlockReinforcedCarpet(Blocks.LIGHT_GRAY_CARPET, "reinforced_light_gray_carpet");
		SCContent.reinforcedCyanCarpet = new BlockReinforcedCarpet(Blocks.CYAN_CARPET, "reinforced_cyan_carpet");
		SCContent.reinforcedPurpleCarpet = new BlockReinforcedCarpet(Blocks.PURPLE_CARPET, "reinforced_purple_carpet");
		SCContent.reinforcedBlueCarpet = new BlockReinforcedCarpet(Blocks.BLUE_CARPET, "reinforced_blue_carpet");
		SCContent.reinforcedBrownCarpet = new BlockReinforcedCarpet(Blocks.BROWN_CARPET, "reinforced_brown_carpet");
		SCContent.reinforcedGreenCarpet = new BlockReinforcedCarpet(Blocks.GREEN_CARPET, "reinforced_green_carpet");
		SCContent.reinforcedRedCarpet = new BlockReinforcedCarpet(Blocks.RED_CARPET, "reinforced_red_carpet");
		SCContent.reinforcedBlackCarpet = new BlockReinforcedCarpet(Blocks.BLACK_CARPET, "reinforced_black_carpet");
		SCContent.reinforcedWhiteStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.WHITE, Blocks.WHITE_STAINED_GLASS_PANE, "reinforced_white_stained_glass_pane");
		SCContent.reinforcedOrangeStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.ORANGE, Blocks.ORANGE_STAINED_GLASS_PANE, "reinforced_orange_stained_glass_pane");
		SCContent.reinforcedMagentaStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.MAGENTA, Blocks.MAGENTA_STAINED_GLASS_PANE, "reinforced_magenta_stained_glass_pane");
		SCContent.reinforcedLightBlueStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_STAINED_GLASS_PANE, "reinforced_light_blue_stained_glass_pane");
		SCContent.reinforcedYellowStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.YELLOW, Blocks.YELLOW_STAINED_GLASS_PANE, "reinforced_yellow_stained_glass_pane");
		SCContent.reinforcedLimeStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.LIME, Blocks.LIME_STAINED_GLASS_PANE, "reinforced_lime_stained_glass_pane");
		SCContent.reinforcedPinkStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.PINK, Blocks.PINK_STAINED_GLASS_PANE, "reinforced_pink_stained_glass_pane");
		SCContent.reinforcedGrayStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.GRAY, Blocks.GRAY_STAINED_GLASS_PANE, "reinforced_gray_stained_glass_pane");
		SCContent.reinforcedLightGrayStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_STAINED_GLASS_PANE, "reinforced_light_gray_stained_glass_pane");
		SCContent.reinforcedCyanStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.CYAN, Blocks.CYAN_STAINED_GLASS_PANE, "reinforced_cyan_stained_glass_pane");
		SCContent.reinforcedPurpleStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.PURPLE, Blocks.PURPLE_STAINED_GLASS_PANE, "reinforced_purple_stained_glass_pane");
		SCContent.reinforcedBlueStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.BLUE, Blocks.BLUE_STAINED_GLASS_PANE, "reinforced_blue_stained_glass_pane");
		SCContent.reinforcedBrownStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.BROWN, Blocks.BROWN_STAINED_GLASS_PANE, "reinforced_brown_stained_glass_pane");
		SCContent.reinforcedGreenStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.GREEN, Blocks.GREEN_STAINED_GLASS_PANE, "reinforced_green_stained_glass_pane");
		SCContent.reinforcedRedStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.RED, Blocks.RED_STAINED_GLASS_PANE, "reinforced_red_stained_glass_pane");
		SCContent.reinforcedBlackStainedGlassPane = new BlockReinforcedStainedGlassPane(EnumDyeColor.BLACK, Blocks.BLACK_STAINED_GLASS_PANE, "reinforced_black_stained_glass_pane");
		//anything else, alphabetical
		SCContent.reinforcedStoneStairs = new BlockReinforcedStairs(SoundType.STONE, Material.ROCK, Blocks.STONE, "reinforced_stone_stairs");
	}

	public static void setupMines()
	{
		SCContent.mine = (BlockMine) new BlockMine(Material.CIRCUITS, 1F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "mine"));
		SCContent.dirtMine = new BlockFullMineBase(Material.GROUND, Blocks.DIRT, 1.25F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "dirt_mine"));
		SCContent.stoneMine = new BlockFullMineBase(Material.ROCK, Blocks.STONE, 2.5F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "stone_mine"));
		SCContent.cobblestoneMine = new BlockFullMineBase(Material.ROCK, Blocks.COBBLESTONE, 2.75F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "cobblestone_mine"));
		SCContent.sandMine = new BlockFullMineFalling(Material.SAND, Blocks.SAND, 1.25F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "sand_mine"));
		SCContent.diamondOreMine = new BlockFullMineBase(Material.ROCK, Blocks.DIAMOND_ORE, 3.75F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "diamond_mine"));
		SCContent.furnaceMine = new BlockFurnaceMine(Material.ROCK, 3.75F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "furnace_mine"));
		SCContent.gravelMine = new BlockFullMineFalling(Material.GROUND, Blocks.GRAVEL, 1.25F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "gravel_mine"));
		SCContent.trackMine = new BlockTrackMine().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "track_mine"));
		SCContent.bouncingBetty = new BlockBouncingBetty(Material.CIRCUITS, 1F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "bouncing_betty"));
		SCContent.claymore = new BlockClaymore(Material.CIRCUITS).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "claymore"));
		SCContent.ims = new BlockIMS(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "ims"));
	}

	public static void setupItems()
	{
		SCContent.codebreaker = new ItemCodebreaker().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "codebreaker"));
		SCContent.keycardLvl1 = new ItemKeycardBase(0).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keycard_lv1"));
		SCContent.keycardLvl2 = new ItemKeycardBase(1).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keycard_lv2"));
		SCContent.keycardLvl3 = new ItemKeycardBase(2).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keycard_lv3"));
		SCContent.keycardLvl4 = new ItemKeycardBase(4).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keycard_lv4"));
		SCContent.keycardLvl5 = new ItemKeycardBase(5).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keycard_lv5"));
		SCContent.limitedUseKeycard = new ItemKeycardBase(3).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "limited_use_keycard"));
		SCContent.reinforcedDoorItem = new ItemReinforcedDoor().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "door_indestructible_iron_item"));
		SCContent.universalBlockRemover = new Item(new Item.Properties().maxStackSize(1).defaultMaxDamage(476).group(SecurityCraft.groupSCTechnical)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_block_remover"));
		SCContent.remoteAccessMine = new ItemMineRemoteAccessTool().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "remote_access_mine"));
		SCContent.fWaterBucket = new ItemBucket(SCContent.fakeWater, new Item.Properties().group(SecurityCraft.groupSCTechnical).maxStackSize(1)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "bucket_f_water"));
		SCContent.fLavaBucket = new ItemBucket(SCContent.fakeLava, new Item.Properties().group(SecurityCraft.groupSCTechnical).maxStackSize(1)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "bucket_f_lava"));
		SCContent.universalBlockModifier = new Item(new Item.Properties().maxStackSize(1).group(SecurityCraft.groupSCTechnical)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_block_modifier"));
		SCContent.redstoneModule = (ItemModule) new ItemModule(EnumCustomModules.REDSTONE, false).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "redstone_module"));
		SCContent.whitelistModule = (ItemModule) new ItemModule(EnumCustomModules.WHITELIST, true, true, GuiHandler.MODULES).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "whitelist_module"));
		SCContent.blacklistModule = (ItemModule) new ItemModule(EnumCustomModules.BLACKLIST, true, true, GuiHandler.MODULES).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "blacklist_module"));
		SCContent.harmingModule = (ItemModule) new ItemModule(EnumCustomModules.HARMING, false).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "harming_module"));
		SCContent.smartModule = (ItemModule) new ItemModule(EnumCustomModules.SMART, false).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "smart_module"));
		SCContent.storageModule = (ItemModule) new ItemModule(EnumCustomModules.STORAGE, false).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "storage_module"));
		SCContent.disguiseModule = (ItemModule) new ItemModule(EnumCustomModules.DISGUISE, false, true, GuiHandler.DISGUISE_MODULE, 0, 1).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "disguise_module"));
		SCContent.wireCutters = new Item(new Item.Properties().maxStackSize(1).defaultMaxDamage(476).group(SecurityCraft.groupSCTechnical)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "wire_cutters"));
		SCContent.keyPanel = new ItemKeyPanel().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keypad_item"));
		SCContent.adminTool = new ItemAdminTool().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "admin_tool"));
		SCContent.cameraMonitor = new ItemCameraMonitor().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "camera_monitor"));
		SCContent.scManual = new ItemSCManual().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "sc_manual"));
		SCContent.taser = new ItemTaser(false).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "taser"));
		SCContent.taserPowered = new ItemTaser(true).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "taser_powered"));
		SCContent.universalOwnerChanger = new ItemUniversalOwnerChanger().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_owner_changer"));
		SCContent.universalBlockReinforcerLvL1 = new ItemUniversalBlockReinforcer(300).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_block_reinforcer_lvl1"));
		SCContent.universalBlockReinforcerLvL2 = new ItemUniversalBlockReinforcer(2700).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_block_reinforcer_lvl2"));
		SCContent.universalBlockReinforcerLvL3 = new ItemUniversalBlockReinforcer(0).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_block_reinforcer_lvl3"));
		SCContent.briefcase = new ItemBriefcase().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "briefcase"));
		SCContent.universalKeyChanger = new ItemUniversalKeyChanger().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_key_changer"));
		SCContent.scannerDoorItem = new ItemScannerDoor().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "scanner_door_item"));
		SCContent.secretSignItem = new ItemSecretSign().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_sign_item"));
		SCContent.sentry = new ItemSentry().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "sentry"));
	}
}
