package net.geforcemods.securitycraft;

import net.geforcemods.securitycraft.ConfigHandler.ServerConfig;
import net.geforcemods.securitycraft.blocks.BlockAlarm;
import net.geforcemods.securitycraft.blocks.BlockCageTrap;
import net.geforcemods.securitycraft.blocks.BlockFakeLava;
import net.geforcemods.securitycraft.blocks.BlockFakeLavaBase;
import net.geforcemods.securitycraft.blocks.BlockFakeWater;
import net.geforcemods.securitycraft.blocks.BlockFakeWaterBase;
import net.geforcemods.securitycraft.blocks.BlockFrame;
import net.geforcemods.securitycraft.blocks.BlockInventoryScanner;
import net.geforcemods.securitycraft.blocks.BlockInventoryScannerField;
import net.geforcemods.securitycraft.blocks.BlockIronFence;
import net.geforcemods.securitycraft.blocks.BlockIronTrapDoor;
import net.geforcemods.securitycraft.blocks.BlockKeycardReader;
import net.geforcemods.securitycraft.blocks.BlockKeypad;
import net.geforcemods.securitycraft.blocks.BlockKeypadChest;
import net.geforcemods.securitycraft.blocks.BlockKeypadFurnace;
import net.geforcemods.securitycraft.blocks.BlockLaserBlock;
import net.geforcemods.securitycraft.blocks.BlockLaserField;
import net.geforcemods.securitycraft.blocks.BlockLogger;
import net.geforcemods.securitycraft.blocks.BlockMotionActivatedLight;
import net.geforcemods.securitycraft.blocks.BlockPanicButton;
import net.geforcemods.securitycraft.blocks.BlockPortableRadar;
import net.geforcemods.securitycraft.blocks.BlockProtecto;
import net.geforcemods.securitycraft.blocks.BlockRetinalScanner;
import net.geforcemods.securitycraft.blocks.BlockScannerDoor;
import net.geforcemods.securitycraft.blocks.BlockSecretSignStanding;
import net.geforcemods.securitycraft.blocks.BlockSecretSignWall;
import net.geforcemods.securitycraft.blocks.BlockSecurityCamera;
import net.geforcemods.securitycraft.blocks.mines.BlockBouncingBetty;
import net.geforcemods.securitycraft.blocks.mines.BlockClaymore;
import net.geforcemods.securitycraft.blocks.mines.BlockFullMineBase;
import net.geforcemods.securitycraft.blocks.mines.BlockFullMineFalling;
import net.geforcemods.securitycraft.blocks.mines.BlockFurnaceMine;
import net.geforcemods.securitycraft.blocks.mines.BlockIMS;
import net.geforcemods.securitycraft.blocks.mines.BlockMine;
import net.geforcemods.securitycraft.blocks.mines.BlockTrackMine;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedBase;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedCarpet;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedDoor;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedFalling;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedFenceGate;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedGlass;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedGlassPane;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedIronBars;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedNewLog;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedOldLog;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedRotatedPillar;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedSlabs;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedSlabs2;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedStainedGlass;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedStainedGlassPanes;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedStairs;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedWoodSlabs;
import net.geforcemods.securitycraft.gui.GuiHandler;
import net.geforcemods.securitycraft.items.ItemAdminTool;
import net.geforcemods.securitycraft.items.ItemBriefcase;
import net.geforcemods.securitycraft.items.ItemCameraMonitor;
import net.geforcemods.securitycraft.items.ItemCodebreaker;
import net.geforcemods.securitycraft.items.ItemKeyPanel;
import net.geforcemods.securitycraft.items.ItemKeycardBase;
import net.geforcemods.securitycraft.items.ItemMineRemoteAccessTool;
import net.geforcemods.securitycraft.items.ItemModifiedBucket;
import net.geforcemods.securitycraft.items.ItemModule;
import net.geforcemods.securitycraft.items.ItemReinforcedDoor;
import net.geforcemods.securitycraft.items.ItemSCManual;
import net.geforcemods.securitycraft.items.ItemScannerDoor;
import net.geforcemods.securitycraft.items.ItemSecretSign;
import net.geforcemods.securitycraft.items.ItemSentry;
import net.geforcemods.securitycraft.items.ItemTaser;
import net.geforcemods.securitycraft.items.ItemUniversalBlockReinforcer;
import net.geforcemods.securitycraft.items.ItemUniversalKeyChanger;
import net.geforcemods.securitycraft.items.ItemUniversalOwnerChanger;
import net.geforcemods.securitycraft.misc.EnumCustomModules;
import net.minecraft.block.BlockStaticLiquid;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.item.Item;

public class SetupHandler
{
	public static void setupBlocks()
	{
		SCContent.laserBlock = new BlockLaserBlock(Material.IRON).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("laser_block").setTranslationKey("securitycraft:laserBlock");
		SCContent.laserField = new BlockLaserField(Material.ROCK).setRegistryName("laser");
		SCContent.keypad = new BlockKeypad(Material.IRON).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("keypad").setTranslationKey("securitycraft:keypad");
		SCContent.retinalScanner = new BlockRetinalScanner(Material.IRON).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("retinal_scanner").setTranslationKey("securitycraft:retinalScanner");
		SCContent.reinforcedDoor = new BlockReinforcedDoor(Material.IRON).setRegistryName("iron_door_reinforced").setTranslationKey("securitycraft:ironDoorReinforced");
		SCContent.bogusLava = (BlockStaticLiquid) new BlockFakeLavaBase(Material.LAVA).setHardness(100.0F).setLightLevel(1.0F).setRegistryName("bogus_lava").setTranslationKey("securitycraft:bogusLava");
		SCContent.bogusLavaFlowing = new BlockFakeLava(Material.LAVA).setHardness(0.0F).setLightLevel(1.0F).setRegistryName("bogus_lava_flowing").setTranslationKey("securitycraft:bogusLavaFlowing");
		SCContent.bogusWater = (BlockStaticLiquid) new BlockFakeWaterBase(Material.WATER).setHardness(100.0F).setRegistryName("bogus_water").setTranslationKey("securitycraft:bogusWater");
		SCContent.bogusWaterFlowing = new BlockFakeWater(Material.WATER).setHardness(0.0F).setRegistryName("bogus_water_flowing").setTranslationKey("securitycraft:bogusWaterFlowing");
		SCContent.keycardReader = new BlockKeycardReader(Material.IRON).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("keycard_reader").setTranslationKey("securitycraft:keycardReader");
		SCContent.ironTrapdoor = new BlockIronTrapDoor(Material.IRON).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_iron_trapdoor").setTranslationKey("securitycraft:reinforcedIronTrapdoor");
		SCContent.inventoryScanner = new BlockInventoryScanner(Material.ROCK).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("inventory_scanner").setTranslationKey("securitycraft:inventoryScanner");
		SCContent.inventoryScannerField = new BlockInventoryScannerField(Material.GLASS).setRegistryName("inventory_scanner_field").setTranslationKey("securitycraft:inventoryScannerField");
		SCContent.cageTrap = new BlockCageTrap(Material.ROCK).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("cage_trap").setTranslationKey("securitycraft:cageTrap");
		SCContent.portableRadar = new BlockPortableRadar(Material.CIRCUITS).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("portable_radar").setTranslationKey("securitycraft:portableRadar");
		SCContent.reinforcedIronBars = new BlockReinforcedIronBars(Material.IRON).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_iron_bars").setTranslationKey("securitycraft:reinforcedIronBars");
		SCContent.keypadChest = new BlockKeypadChest().setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("keypad_chest").setTranslationKey("securitycraft:keypadChest");
		SCContent.usernameLogger = new BlockLogger(Material.ROCK).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("username_logger").setTranslationKey("securitycraft:usernameLogger");
		SCContent.alarm = new BlockAlarm().setRegistryName("alarm");
		SCContent.reinforcedFencegate = new BlockReinforcedFenceGate().setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_fence_gate").setTranslationKey("securitycraft:reinforcedFenceGate");
		SCContent.panicButton = new BlockPanicButton().setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("panic_button").setTranslationKey("securitycraft:panicButton");
		SCContent.frame = new BlockFrame(Material.ROCK).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("keypad_frame").setTranslationKey("securitycraft:keypadFrame");
		SCContent.keypadFurnace = new BlockKeypadFurnace(Material.IRON).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("keypad_furnace").setTranslationKey("securitycraft:keypadFurnace");
		SCContent.securityCamera = new BlockSecurityCamera(Material.IRON).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("security_camera").setTranslationKey("securitycraft:securityCamera");
		SCContent.reinforcedStairsOak = new BlockReinforcedStairs(SCContent.reinforcedWoodPlanks, 0).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_oak").setTranslationKey("securitycraft:reinforcedStairsOak");
		SCContent.reinforcedStairsSpruce = new BlockReinforcedStairs(SCContent.reinforcedWoodPlanks, 1).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_spruce").setTranslationKey("securitycraft:reinforcedStairsSpruce");
		SCContent.reinforcedStairsBirch = new BlockReinforcedStairs(SCContent.reinforcedWoodPlanks, 2).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_birch").setTranslationKey("securitycraft:reinforcedStairsBirch");
		SCContent.reinforcedStairsJungle = new BlockReinforcedStairs(SCContent.reinforcedWoodPlanks, 3).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_jungle").setTranslationKey("securitycraft:reinforcedStairsJungle");
		SCContent.reinforcedStairsAcacia = new BlockReinforcedStairs(SCContent.reinforcedWoodPlanks, 4).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_acacia").setTranslationKey("securitycraft:reinforcedStairsAcacia");
		SCContent.reinforcedStairsDarkoak = new BlockReinforcedStairs(SCContent.reinforcedWoodPlanks, 5).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_darkoak").setTranslationKey("securitycraft:reinforcedStairsDarkoak");
		SCContent.reinforcedStairsStone = new BlockReinforcedStairs(SCContent.reinforcedStone, 0).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_stone").setTranslationKey("securitycraft:reinforcedStairsStone");
		SCContent.ironFence = new BlockIronFence(Material.IRON).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("electrified_iron_fence").setTranslationKey("securitycraft:electrifiedIronFence");
		SCContent.reinforcedGlass = new BlockReinforcedGlass(Material.GLASS).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_glass_block").setTranslationKey("securitycraft:reinforcedGlassBlock");
		SCContent.reinforcedStainedGlass = new BlockReinforcedStainedGlass(Material.GLASS).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stained_glass").setTranslationKey("securitycraft:reinforcedStainedGlass");
		SCContent.reinforcedStairsCobblestone = new BlockReinforcedStairs(SCContent.reinforcedCobblestone, 0).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_cobblestone").setTranslationKey("securitycraft:reinforcedStairsCobblestone");
		SCContent.reinforcedStairsSandstone = new BlockReinforcedStairs(SCContent.reinforcedSandstone, 0).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_sandstone").setTranslationKey("securitycraft:reinforcedStairsSandstone");
		SCContent.reinforcedWoodSlabs = new BlockReinforcedWoodSlabs(false).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_wood_slabs").setTranslationKey("securitycraft:reinforcedWoodSlabs");
		SCContent.reinforcedDoubleWoodSlabs = new BlockReinforcedWoodSlabs(true).setBlockUnbreakable().setResistance(6000000.0F).setRegistryName("reinforced_double_wood_slabs").setTranslationKey("securitycraft:reinforcedDoubleWoodSlabs");
		SCContent.reinforcedStoneSlabs = new BlockReinforcedSlabs(false, Material.ROCK).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stone_slabs").setTranslationKey("securitycraft:reinforcedStoneSlabs");
		SCContent.reinforcedDoubleStoneSlabs = new BlockReinforcedSlabs(true, Material.ROCK).setBlockUnbreakable().setResistance(6000000.0F).setRegistryName("reinforced_double_stone_slabs").setTranslationKey("securitycraft:reinforcedDoubleStoneSlabs");
		SCContent.protecto = new BlockProtecto(Material.IRON).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("protecto").setTranslationKey("securitycraft:protecto");
		SCContent.scannerDoor = new BlockScannerDoor(Material.IRON).setRegistryName("scanner_door").setTranslationKey("securitycraft:scannerDoor");
		SCContent.reinforcedStairsStoneBrick= new BlockReinforcedStairs(SCContent.reinforcedStoneBrick, 0).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_stone_brick").setTranslationKey("securitycraft:reinforcedStairsStoneBrick");
		SCContent.reinforcedStairsBrick= new BlockReinforcedStairs(SCContent.reinforcedBricks, 0).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_brick").setTranslationKey("securitycraft:reinforcedStairsBrick");
		SCContent.reinforcedStairsNetherBrick= new BlockReinforcedStairs(SCContent.reinforcedNetherBricks, 0).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_nether_brick").setTranslationKey("securitycraft:reinforcedStairsNetherBrick");
		SCContent.reinforcedOldLogs = new BlockReinforcedOldLog().setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_logs").setTranslationKey("securitycraft:reinforcedLogs");
		SCContent.reinforcedNewLogs = new BlockReinforcedNewLog().setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_logs2").setTranslationKey("securitycraft:reinforcedLogs2");
		SCContent.reinforcedStairsQuartz = new BlockReinforcedStairs(SCContent.reinforcedQuartz, 0).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_quartz").setTranslationKey("securitycraft:reinforcedStairsQuartz");
		SCContent.reinforcedStairsRedSandstone = new BlockReinforcedStairs(SCContent.reinforcedRedSandstone, 0).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_red_sandstone").setTranslationKey("securitycraft:reinforcedStairsRedSandstone");
		SCContent.reinforcedStoneSlabs2 = new BlockReinforcedSlabs2(false, Material.ROCK).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stone_slabs2").setTranslationKey("securitycraft:reinforcedStoneSlabs2");
		SCContent.reinforcedDoubleStoneSlabs2 = new BlockReinforcedSlabs2(true, Material.ROCK).setBlockUnbreakable().setResistance(6000000.0F).setRegistryName("reinforced_double_stone_slabs2").setTranslationKey("securitycraft:reinforcedDoubleStoneSlabs2");
		SCContent.reinforcedStairsPurpur = new BlockReinforcedStairs(SCContent.reinforcedPurpurBlock, 0).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stairs_purpur").setTranslationKey("securitycraft:reinforcedStairsPurpur");
		SCContent.secretSignStanding = new BlockSecretSignStanding().setBlockUnbreakable().setResistance(6000000.0F).setRegistryName("secret_sign_standing").setTranslationKey("securitycraft:secretSign");
		SCContent.secretSignWall = new BlockSecretSignWall().setBlockUnbreakable().setResistance(6000000.0F).setRegistryName("secret_sign_wall").setTranslationKey("securitycraft:secretSign");
		SCContent.motionActivatedLight = new BlockMotionActivatedLight(Material.GLASS).setRegistryName("motion_activated_light").setTranslationKey("securitycraft:motionActivatedLight").setCreativeTab(SecurityCraft.groupSCTechnical);
		SCContent.reinforcedObsidian = new BlockReinforcedBase(Material.ROCK, 1, Blocks.OBSIDIAN).setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_obsidian").setTranslationKey("securitycraft:reinforcedObsidian");
		SCContent.reinforcedSeaLantern = new BlockReinforcedBase(Material.GLASS, 1, Blocks.SEA_LANTERN).setBlockUnbreakable().setResistance(6000000.0F).setLightLevel(1.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_sea_lantern").setTranslationKey("securitycraft:reinforcedSeaLantern");
		SCContent.reinforcedGlassPane = new BlockReinforcedGlassPane().setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_glass_pane").setTranslationKey("securitycraft:reinforcedGlassPane");
		SCContent.reinforcedStainedGlassPanes = new BlockReinforcedStainedGlassPanes().setBlockUnbreakable().setResistance(6000000.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_stained_panes").setTranslationKey("securitycraft:reinforcedStainedGlassPanes");
		SCContent.reinforcedGlowstone = new BlockReinforcedBase(Material.GLASS, 1, Blocks.GLOWSTONE).setBlockUnbreakable().setResistance(6000000.0F).setLightLevel(1.0F).setCreativeTab(SecurityCraft.groupSCDecoration).setRegistryName("reinforced_glowstone").setTranslationKey("securitycraft:reinforcedGlowstone");
		SCContent.reinforcedSand = new BlockReinforcedFalling(Material.SAND, Blocks.SAND).setCreativeTab(SecurityCraft.groupSCDecoration).setBlockUnbreakable().setResistance(6000000.0F).setRegistryName("reinforced_sand").setTranslationKey("securitycraft:reinforcedSand");
		SCContent.reinforcedGravel = new BlockReinforcedFalling(Material.GROUND, Blocks.GRAVEL).setCreativeTab(SecurityCraft.groupSCDecoration).setBlockUnbreakable().setResistance(6000000.0F).setRegistryName("reinforced_gravel").setTranslationKey("securitycraft:reinforcedGravel");
	}

	public static void setupReinforcedBlocks()
	{
		//ordered by vanilla building blocks creative tab order
		SCContent.reinforcedStone = new BlockReinforcedBase(Material.ROCK, Blocks.STONE, "reinforced_stone");
		SCContent.reinforcedGranite = new BlockReinforcedBase(Material.ROCK, Blocks.GRANITE, "reinforced_granite");
		SCContent.reinforcedPolishedGranite = new BlockReinforcedBase(Material.ROCK, Blocks.POLISHED_GRANITE, "reinforced_polished_granite");
		SCContent.reinforcedDiorite = new BlockReinforcedBase(Material.ROCK, Blocks.DIORITE, "reinforced_diorite");
		SCContent.reinforcedPolishedDiorite = new BlockReinforcedBase(Material.ROCK, Blocks.POLISHED_DIORITE, "reinforced_polished_diorite");
		SCContent.reinforcedAndesite = new BlockReinforcedBase(Material.ROCK, Blocks.ANDESITE, "reinforced_andesite");
		SCContent.reinforcedPolishedAndesite = new BlockReinforcedBase(Material.ROCK, Blocks.POLISHED_ANDESITE, "reinforced_polished_andesite");
		SCContent.reinforcedDirt = new BlockReinforcedBase(Material.ROCK, Blocks.DIRT, "reinforced_dirt");
		SCContent.reinforcedCobblestone = new BlockReinforcedBase(Material.ROCK, Blocks.COBBLESTONE, "reinforced_cobblestone");
		SCContent.reinforcedOakPlanks = new BlockReinforcedBase(Material.ROCK, Blocks.OAK_PLANKS, "reinforced_oak_planks");
		SCContent.reinforcedSprucePlanks = new BlockReinforcedBase(Material.ROCK, Blocks.SPRUCE_PLANKS, "reinforced_spruce_planks");
		SCContent.reinforcedBirchPlanks = new BlockReinforcedBase(Material.ROCK, Blocks.BIRCH_PLANKS, "reinforced_birch_planks");
		SCContent.reinforcedJunglePlanks = new BlockReinforcedBase(Material.ROCK, Blocks.JUNGLE_PLANKS, "reinforced_jungle_planks");
		SCContent.reinforcedAcaciaPlanks = new BlockReinforcedBase(Material.ROCK, Blocks.ACACIA_PLANKS, "reinforced_acacia_planks");
		SCContent.reinforcedDarkOakPlanks = new BlockReinforcedBase(Material.ROCK, Blocks.DARK_OAK_PLANKS, "reinforced_dark_oak_planks");
		SCContent.reinforcedLapisBlock = new BlockReinforcedBase(Material.ROCK, Blocks.LAPIS_BLOCK, "reinforced_lapis_block");
		SCContent.reinforcedSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.SANDSTONE, "reinforced_sandstone");
		SCContent.reinforcedChiseledSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.CHISELED_SANDSTONE, "reinforced_chiseled_sandstone");
		SCContent.reinforcedCutSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.CUT_SANDSTONE, "reinforced_cut_sandstone");
		SCContent.reinforcedWhiteWool = new BlockReinforcedBase(Material.ROCK, Blocks.WHITE_WOOL, "reinforced_white_wool");
		SCContent.reinforcedOrangeWool = new BlockReinforcedBase(Material.ROCK, Blocks.ORANGE_WOOL, "reinforced_orange_wool");
		SCContent.reinforcedMagentaWool = new BlockReinforcedBase(Material.ROCK, Blocks.MAGENTA_WOOL, "reinforced_magenta_wool");
		SCContent.reinforcedLightBlueWool = new BlockReinforcedBase(Material.ROCK, Blocks.LIGHT_BLUE_WOOL, "reinforced_light_blue_wool");
		SCContent.reinforcedYellowWool = new BlockReinforcedBase(Material.ROCK, Blocks.YELLOW_WOOL, "reinforced_yellow_wool");
		SCContent.reinforcedLimeWool = new BlockReinforcedBase(Material.ROCK, Blocks.LIME_WOOL, "reinforced_lime_wool");
		SCContent.reinforcedPinkWool = new BlockReinforcedBase(Material.ROCK, Blocks.PINK_WOOL, "reinforced_pink_wool");
		SCContent.reinforcedGrayWool = new BlockReinforcedBase(Material.ROCK, Blocks.GRAY_WOOL, "reinforced_gray_wool");
		SCContent.reinforcedLightGrayWool = new BlockReinforcedBase(Material.ROCK, Blocks.LIGHT_GRAY_WOOL, "reinforced_light_gray_wool");
		SCContent.reinforcedCyanWool = new BlockReinforcedBase(Material.ROCK, Blocks.CYAN_WOOL, "reinforced_cyan_wool");
		SCContent.reinforcedPurpleWool = new BlockReinforcedBase(Material.ROCK, Blocks.PURPLE_WOOL, "reinforced_purple_wool");
		SCContent.reinforcedBlueWool = new BlockReinforcedBase(Material.ROCK, Blocks.BLUE_WOOL, "reinforced_blue_wool");
		SCContent.reinforcedBrownWool = new BlockReinforcedBase(Material.ROCK, Blocks.BROWN_WOOL, "reinforced_brown_wool");
		SCContent.reinforcedGreenWool = new BlockReinforcedBase(Material.ROCK, Blocks.GREEN_WOOL, "reinforced_green_wool");
		SCContent.reinforcedRedWool = new BlockReinforcedBase(Material.ROCK, Blocks.RED_WOOL, "reinforced_red_wool");
		SCContent.reinforcedBlackWool = new BlockReinforcedBase(Material.ROCK, Blocks.BLACK_WOOL, "reinforced_black_wool");
		SCContent.reinforcedGoldBlock = new BlockReinforcedBase(Material.ROCK, Blocks.GOLD_BLOCK, "reinforced_gold_block");
		SCContent.reinforcedIronBlock = new BlockReinforcedBase(Material.ROCK, Blocks.IRON_BLOCK, "reinforced_iron_block");
		SCContent.reinforcedBricks = new BlockReinforcedBase(Material.ROCK, Blocks.BRICKS, "reinforced_bricks");
		SCContent.reinforcedMossyCobblestone = new BlockReinforcedBase(Material.ROCK, Blocks.MOSSY_COBBLESTONE, "reinforced_mossy_cobblestone");
		SCContent.reinforcedPurpurBlock = new BlockReinforcedBase(Material.ROCK, Blocks.PURPUR_BLOCK, "reinforced_purpur_block");
		SCContent.reinforcedPurpurPillar = new BlockReinforcedRotatedPillar(Material.ROCK, Blocks.PURPUR_PILLAR, "reinforced_purpur_pillar");
		SCContent.reinforcedDiamondBlock = new BlockReinforcedBase(Material.ROCK, Blocks.DIAMOND_BLOCK, "reinforced_diamond_block");
		SCContent.reinforcedNetherrack = new BlockReinforcedBase(Material.ROCK, Blocks.NETHERRACK, "reinforced_netherrack");
		SCContent.reinforcedStoneBricks = new BlockReinforcedBase(Material.ROCK, Blocks.STONE_BRICKS, "reinforced_stone_bricks");
		SCContent.reinforcedMossyStoneBricks = new BlockReinforcedBase(Material.ROCK, Blocks.MOSSY_STONE_BRICKS, "reinforced_mossy_stone_bricks");
		SCContent.reinforcedCrackedStoneBricks = new BlockReinforcedBase(Material.ROCK, Blocks.CRACKED_STONE_BRICKS, "reinforced_cracked_stone_bricks");
		SCContent.reinforcedChiseledStoneBricks = new BlockReinforcedBase(Material.ROCK, Blocks.CHISELED_STONE_BRICKS, "reinforced_chiseled_stone_bricks");
		SCContent.reinforcedNetherBricks = new BlockReinforcedBase(Material.ROCK, Blocks.NETHER_BRICKS, "reinforced_nether_bricks");
		SCContent.reinforcedEndStone = new BlockReinforcedBase(Material.ROCK, Blocks.END_STONE, "reinforced_end_stone");
		SCContent.reinforcedEndStoneBricks = new BlockReinforcedBase(Material.ROCK, Blocks.END_STONE_BRICKS, "reinforced_end_stone_bricks");
		SCContent.reinforcedEmeraldBlock = new BlockReinforcedBase(Material.ROCK, Blocks.EMERALD_BLOCK, "reinforced_emerald_block");
		SCContent.reinforcedChiseledQuartz = new BlockReinforcedBase(Material.ROCK, Blocks.CHISELED_QUARTZ_BLOCK, "reinforced_chiseled_quartz_block");
		SCContent.reinforcedQuartz = new BlockReinforcedBase(Material.ROCK, Blocks.QUARTZ_BLOCK, "reinforced_quartz_block");
		SCContent.reinforcedQuartzPillar = new BlockReinforcedRotatedPillar(Material.ROCK, Blocks.QUARTZ_PILLAR, "reinforced_quartz_pillar");
		SCContent.reinforcedWhiteTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.WHITE_TERRACOTTA, "reinforced_white_terracotta");
		SCContent.reinforcedOrangeTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.ORANGE_TERRACOTTA, "reinforced_orange_terracotta");
		SCContent.reinforcedMagentaTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.MAGENTA_TERRACOTTA, "reinforced_magenta_terracotta");
		SCContent.reinforcedLightBlueTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.LIGHT_BLUE_TERRACOTTA, "reinforced_light_blue_terracotta");
		SCContent.reinforcedYellowTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.YELLOW_TERRACOTTA, "reinforced_yellow_terracotta");
		SCContent.reinforcedLimeTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.LIME_TERRACOTTA, "reinforced_lime_terracotta");
		SCContent.reinforcedPinkTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.PINK_TERRACOTTA, "reinforced_pink_terracotta");
		SCContent.reinforcedGrayTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.GRAY_TERRACOTTA, "reinforced_gray_terracotta");
		SCContent.reinforcedLightGrayTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.LIGHT_GRAY_TERRACOTTA, "reinforced_light_gray_terracotta");
		SCContent.reinforcedCyanTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.CYAN_TERRACOTTA, "reinforced_cyan_terracotta");
		SCContent.reinforcedPurpleTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.PURPLE_TERRACOTTA, "reinforced_purple_terracotta");
		SCContent.reinforcedBlueTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.BLUE_TERRACOTTA, "reinforced_blue_terracotta");
		SCContent.reinforcedBrownTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.BROWN_TERRACOTTA, "reinforced_brown_terracotta");
		SCContent.reinforcedGreenTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.GREEN_TERRACOTTA, "reinforced_green_terracotta");
		SCContent.reinforcedRedTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.RED_TERRACOTTA, "reinforced_red_terracotta");
		SCContent.reinforcedBlackTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.BLACK_TERRACOTTA, "reinforced_black_terracotta");
		SCContent.reinforcedTerracotta = new BlockReinforcedBase(Material.ROCK, Blocks.TERRACOTTA, "reinforced_hardened_clay");
		SCContent.reinforcedCoalBlock = new BlockReinforcedBase(Material.ROCK, Blocks.COAL_BLOCK, "reinforced_coal_block");
		SCContent.reinforcedPrismarine = new BlockReinforcedBase(Material.ROCK, Blocks.PRISMARINE, "reinforced_prismarine");
		SCContent.reinforcedPrismarineBricks = new BlockReinforcedBase(Material.ROCK, Blocks.PRISMARINE_BRICKS, "reinforced_prismarine_bricks");
		SCContent.reinforcedDarkPrismarine = new BlockReinforcedBase(Material.ROCK, Blocks.DARK_PRISMARINE, "reinforced_dark_prismarine");
		SCContent.reinforcedRedSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.SANDSTONE, "reinforced_red_sandstone");
		SCContent.reinforcedChiseledRedSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.CHISELED_SANDSTONE, "reinforced_chiseled_red_sandstone");
		SCContent.reinforcedCutRedSandstone = new BlockReinforcedBase(Material.ROCK, Blocks.CUT_SANDSTONE, "reinforced_cut_red_sandstone");
		SCContent.reinforcedRedNetherBricks = new BlockReinforcedBase(Material.ROCK, Blocks.RED_NETHER_BRICKS, "reinforced_red_nether_bricks");
		SCContent.reinforcedBoneBlock = new BlockReinforcedRotatedPillar(Material.ROCK, Blocks.BONE_BLOCK, "reinforced_bone_block");
		SCContent.reinforcedWhiteConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.WHITE_CONCRETE, "reinforced_white_concrete");
		SCContent.reinforcedOrangeConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.ORANGE_CONCRETE, "reinforced_orange_concrete");
		SCContent.reinforcedMagentaConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.MAGENTA_CONCRETE, "reinforced_magenta_concrete");
		SCContent.reinforcedLightBlueConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.LIGHT_BLUE_CONCRETE, "reinforced_light_blue_concrete");
		SCContent.reinforcedYellowConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.YELLOW_CONCRETE, "reinforced_yellow_concrete");
		SCContent.reinforcedLimeConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.LIME_CONCRETE, "reinforced_lime_concrete");
		SCContent.reinforcedPinkConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.PINK_CONCRETE, "reinforced_pink_concrete");
		SCContent.reinforcedGrayConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.GRAY_CONCRETE, "reinforced_gray_concrete");
		SCContent.reinforcedLightGrayConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.LIGHT_GRAY_CONCRETE, "reinforced_light_gray_concrete");
		SCContent.reinforcedCyanConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.CYAN_CONCRETE, "reinforced_cyan_concrete");
		SCContent.reinforcedPurpleConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.PURPLE_CONCRETE, "reinforced_purple_concrete");
		SCContent.reinforcedBlueConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.BLUE_CONCRETE, "reinforced_blue_concrete");
		SCContent.reinforcedBrownConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.BROWN_CONCRETE, "reinforced_brown_concrete");
		SCContent.reinforcedGreenConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.GREEN_CONCRETE, "reinforced_green_concrete");
		SCContent.reinforcedRedConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.RED_CONCRETE, "reinforced_red_concrete");
		SCContent.reinforcedBlackConcrete = new BlockReinforcedBase(Material.ROCK, Blocks.BLACK_CONCRETE, "reinforced_black_concrete");
		//ordered by vanilla decoration blocks creative tab order
		SCContent.reinforcedWhiteCarpet = new BlockReinforcedCarpet(Blocks.WHITE_CARPET, "reinforced_white_carpet");
		SCContent.reinforcedOrangeCarpet = new BlockReinforcedCarpet(Blocks.ORANGE_CARPET, "reinforced_orange_carpet");
		SCContent.reinforcedMagentaCarpet = new BlockReinforcedCarpet(Blocks.MAGENTA_CARPET, "reinforced_magenta_carpet");
		SCContent.reinforcedLightBlueCarpet = new BlockReinforcedCarpet(Blocks.LIGHT_BLUE_CARPET, "reinforced_light_blue_carpet");
		SCContent.reinforcedYellowCarpet = new BlockReinforcedCarpet(Blocks.YELLOW_CARPET, "reinforced_yellow_carpet");
		SCContent.reinforcedLimeCarpet = new BlockReinforcedCarpet(Blocks.LIME_CARPET, "reinforced_lime_carpet");
		SCContent.reinforcedPinkCarpet = new BlockReinforcedCarpet(Blocks.PINK_CARPET, "reinforced_pink_carpet");
		SCContent.reinforcedGrayCarpet = new BlockReinforcedCarpet(Blocks.GRAY_CARPET, "reinforced_gray_carpet");
		SCContent.reinforcedLightGrayCarpet = new BlockReinforcedCarpet(Blocks.LIGHT_GRAY_CARPET, "reinforced_light_gray_carpet");
		SCContent.reinforcedCyanCarpet = new BlockReinforcedCarpet(Blocks.CYAN_CARPET, "reinforced_cyan_carpet");
		SCContent.reinforcedPurpleCarpet = new BlockReinforcedCarpet(Blocks.PURPLE_CARPET, "reinforced_purple_carpet");
		SCContent.reinforcedBlueCarpet = new BlockReinforcedCarpet(Blocks.BLUE_CARPET, "reinforced_blue_carpet");
		SCContent.reinforcedBrownCarpet = new BlockReinforcedCarpet(Blocks.BROWN_CARPET, "reinforced_brown_carpet");
		SCContent.reinforcedGreenCarpet = new BlockReinforcedCarpet(Blocks.GREEN_CARPET, "reinforced_green_carpet");
		SCContent.reinforcedRedCarpet = new BlockReinforcedCarpet(Blocks.RED_CARPET, "reinforced_red_carpet");
		SCContent.reinforcedBlackCarpet = new BlockReinforcedCarpet(Blocks.BLACK_CARPET, "reinforced_black_carpet");
	}

	public static void setupMines()
	{
		SCContent.mine = (BlockMine) new BlockMine(Material.CIRCUITS).setCreativeTab(SecurityCraft.groupSCMine).setRegistryName("mine").setTranslationKey("securitycraft:mine");
		SCContent.mineCut = (BlockMine) new BlockMine(Material.CIRCUITS).setRegistryName("mine_cut").setTranslationKey("securitycraft:mineCut");
		SCContent.dirtMine = new BlockFullMineBase(Material.GROUND, Blocks.DIRT).setCreativeTab(SecurityCraft.groupSCMine).setHardness(!ServerConfig.CONFIG.ableToBreakMines.get() ? -1F : 1.25F).setRegistryName("dirt_mine").setTranslationKey("securitycraft:dirtMine");
		SCContent.stoneMine = new BlockFullMineBase(Material.ROCK, Blocks.STONE).setCreativeTab(SecurityCraft.groupSCMine).setHardness(!ServerConfig.CONFIG.ableToBreakMines.get() ? -1F : 2.5F).setRegistryName("stone_mine").setTranslationKey("securitycraft:stoneMine");
		SCContent.cobblestoneMine = new BlockFullMineBase(Material.ROCK, Blocks.COBBLESTONE).setCreativeTab(SecurityCraft.groupSCMine).setHardness(!ServerConfig.CONFIG.ableToBreakMines.get() ? -1F : 2.75F).setRegistryName("cobblestone_mine").setTranslationKey("securitycraft:cobblestoneMine");
		SCContent.sandMine = new BlockFullMineFalling(Material.SAND, Blocks.SAND).setCreativeTab(SecurityCraft.groupSCMine).setHardness(!ServerConfig.CONFIG.ableToBreakMines.get() ? -1F : 1.25F).setRegistryName("sand_mine").setTranslationKey("securitycraft:sandMine");
		SCContent.diamondOreMine = new BlockFullMineBase(Material.ROCK, Blocks.DIAMOND_ORE).setCreativeTab(SecurityCraft.groupSCMine).setHardness(!ServerConfig.CONFIG.ableToBreakMines.get() ? -1F : 3.75F).setRegistryName("diamond_mine").setTranslationKey("securitycraft:diamondMine");
		SCContent.furnaceMine = new BlockFurnaceMine(Material.ROCK).setCreativeTab(SecurityCraft.groupSCMine).setHardness(!ServerConfig.CONFIG.ableToBreakMines.get() ? -1F : 3.75F).setRegistryName("furnace_mine").setTranslationKey("securitycraft:furnaceMine");
		SCContent.gravelMine = new BlockFullMineFalling(Material.GROUND, Blocks.GRAVEL).setCreativeTab(SecurityCraft.groupSCMine).setHardness(!ServerConfig.CONFIG.ableToBreakMines.get() ? -1F : 1.25F).setRegistryName("gravel_mine").setTranslationKey("securitycraft:gravelMine");
		SCContent.trackMine = new BlockTrackMine().setCreativeTab(SecurityCraft.groupSCMine).setRegistryName("track_mine").setTranslationKey("securitycraft:trackMine");
		SCContent.bouncingBetty = new BlockBouncingBetty(Material.CIRCUITS).setCreativeTab(SecurityCraft.groupSCMine).setRegistryName("bouncing_betty").setTranslationKey("securitycraft:bouncingBetty");
		SCContent.claymore = new BlockClaymore(Material.CIRCUITS).setCreativeTab(SecurityCraft.groupSCMine).setRegistryName("claymore").setTranslationKey("securitycraft:claymore");
		SCContent.ims = new BlockIMS(Material.IRON).setCreativeTab(SecurityCraft.groupSCMine).setRegistryName("ims").setTranslationKey("securitycraft:ims");
	}

	public static void setupItems()
	{
		SCContent.codebreaker = new ItemCodebreaker().setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("codebreaker").setTranslationKey("securitycraft:codebreaker");
		SCContent.keycardLvl1 = new ItemKeycardBase(0).setRegistryName("keycard_lv1").setTranslationKey("securitycraft:keycardLV1");
		SCContent.keycardLvl2 = new ItemKeycardBase(1).setRegistryName("keycard_lv2").setTranslationKey("securitycraft:keycardLV2");
		SCContent.keycardLvl3 = new ItemKeycardBase(2).setRegistryName("keycard_lv3").setTranslationKey("securitycraft:keycardLV3");
		SCContent.keycardLvl4 = new ItemKeycardBase(4).setRegistryName("keycard_lv4").setTranslationKey("securitycraft:keycardLV4");
		SCContent.keycardLvl5 = new ItemKeycardBase(5).setRegistryName("keycard_lv5").setTranslationKey("securitycraft:keycardLV5");
		SCContent.limitedUseKeycard = new ItemKeycardBase(3).setRegistryName("limited_use_keycard").setTranslationKey("securitycraft:limitedUseKeycard");
		SCContent.reinforcedDoorItem = new ItemReinforcedDoor().setRegistryName("door_indestructible_iron_item").setTranslationKey("securitycraft:doorIndestructibleIronItem").setCreativeTab(SecurityCraft.groupSCDecoration);
		SCContent.universalBlockRemover = new Item().setMaxStackSize(1).setMaxDamage(476).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("universal_block_remover").setTranslationKey("securitycraft:universalBlockRemover");
		SCContent.remoteAccessMine = new ItemMineRemoteAccessTool().setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("remote_access_mine").setTranslationKey("securitycraft:remoteAccessMine");
		SCContent.fWaterBucket = new ItemModifiedBucket(SCContent.bogusWaterFlowing).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("bucket_f_water").setTranslationKey("securitycraft:bucketFWater");
		SCContent.fLavaBucket = new ItemModifiedBucket(SCContent.bogusLavaFlowing).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("bucket_f_lava").setTranslationKey("securitycraft:bucketFLava");
		SCContent.universalBlockModifier = new Item().setMaxStackSize(1).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("universal_block_modifier").setTranslationKey("securitycraft:universalBlockModifier");
		SCContent.redstoneModule = (ItemModule) new ItemModule(EnumCustomModules.REDSTONE, false).setRegistryName("redstone_module").setTranslationKey("securitycraft:redstoneModule");
		SCContent.whitelistModule = (ItemModule) new ItemModule(EnumCustomModules.WHITELIST, true, true, GuiHandler.MODULES).setRegistryName("whitelist_module").setTranslationKey("securitycraft:whitelistModule");
		SCContent.blacklistModule = (ItemModule) new ItemModule(EnumCustomModules.BLACKLIST, true, true, GuiHandler.MODULES).setRegistryName("blacklist_module").setTranslationKey("securitycraft:blacklistModule");
		SCContent.harmingModule = (ItemModule) new ItemModule(EnumCustomModules.HARMING, false).setRegistryName("harming_module").setTranslationKey("securitycraft:harmingModule");
		SCContent.smartModule = (ItemModule) new ItemModule(EnumCustomModules.SMART, false).setRegistryName("smart_module").setTranslationKey("securitycraft:smartModule");
		SCContent.storageModule = (ItemModule) new ItemModule(EnumCustomModules.STORAGE, false).setRegistryName("storage_module").setTranslationKey("securitycraft:storageModule");
		SCContent.disguiseModule = (ItemModule) new ItemModule(EnumCustomModules.DISGUISE, false, true, GuiHandler.DISGUISE_MODULE, 0, 1).setRegistryName("disguise_module").setTranslationKey("securitycraft:disguiseModule");
		SCContent.wireCutters = new Item().setMaxStackSize(1).setMaxDamage(476).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("wire_cutters").setTranslationKey("securitycraft:wireCutters");
		SCContent.keyPanel = new ItemKeyPanel().setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("keypad_item").setTranslationKey("securitycraft:keypadItem");
		SCContent.adminTool = new ItemAdminTool().setMaxStackSize(1).setRegistryName("admin_tool").setTranslationKey("securitycraft:adminTool");
		SCContent.cameraMonitor = new ItemCameraMonitor().setMaxStackSize(1).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("camera_monitor").setTranslationKey("securitycraft:cameraMonitor");
		SCContent.scManual = new ItemSCManual().setMaxStackSize(1).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("sc_manual").setTranslationKey("securitycraft:scManual");
		SCContent.taser = new ItemTaser(false).setMaxStackSize(1).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("taser").setTranslationKey("securitycraft:taser");
		SCContent.taserPowered = new ItemTaser(true).setMaxStackSize(1).setRegistryName("taser_powered").setTranslationKey("securitycraft:taser");
		SCContent.universalOwnerChanger = new ItemUniversalOwnerChanger().setMaxStackSize(1).setMaxDamage(48).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("universal_owner_changer").setTranslationKey("securitycraft:universalOwnerChanger");
		SCContent.universalBlockReinforcerLvL1 = new ItemUniversalBlockReinforcer(300).setMaxStackSize(1).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("universal_block_reinforcer_lvl1").setTranslationKey("securitycraft:universalBlockReinforcerLvL1");
		SCContent.universalBlockReinforcerLvL2 = new ItemUniversalBlockReinforcer(2700).setMaxStackSize(1).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("universal_block_reinforcer_lvl2").setTranslationKey("securitycraft:universalBlockReinforcerLvL2");
		SCContent.universalBlockReinforcerLvL3 = new ItemUniversalBlockReinforcer(0).setMaxStackSize(1).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("universal_block_reinforcer_lvl3").setTranslationKey("securitycraft:universalBlockReinforcerLvL3");
		SCContent.briefcase = new ItemBriefcase().setMaxStackSize(1).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("briefcase").setTranslationKey("securitycraft:briefcase");
		SCContent.universalKeyChanger = new ItemUniversalKeyChanger().setMaxStackSize(1).setCreativeTab(SecurityCraft.groupSCTechnical).setRegistryName("universal_key_changer").setTranslationKey("securitycraft:universalKeyChanger");
		SCContent.scannerDoorItem = new ItemScannerDoor().setRegistryName("scanner_door_item").setTranslationKey("securitycraft:scannerDoorItem").setCreativeTab(SecurityCraft.groupSCDecoration);
		SCContent.secretSignItem = new ItemSecretSign().setRegistryName("secret_sign_item").setTranslationKey("securitycraft:secretSignItem").setCreativeTab(SecurityCraft.groupSCDecoration);
		SCContent.sentry = new ItemSentry().setRegistryName("sentry").setTranslationKey("securitycraft:sentry").setCreativeTab(SecurityCraft.groupSCTechnical);
	}
}
