package net.geforcemods.securitycraft;

import net.geforcemods.securitycraft.blocks.mines.BlockMine;
import net.geforcemods.securitycraft.items.ItemModule;
import net.geforcemods.securitycraft.util.Reinforced;
import net.geforcemods.securitycraft.util.Tinted;
import net.minecraft.block.Block;
import net.minecraft.block.BlockStaticLiquid;
import net.minecraft.item.Item;

public class SCContent
{
	//Blocks
	public static Block alarm;
	@Deprecated //use alarm and its lit property
	public static Block alarmLit;
	@Tinted(customTint = 0x15b3a2) public static Block blockPocketManager;
	@Tinted(customTint = 0x15b3a2) public static Block blockPocketWall;
	public static Block bogusLavaFlowing;
	public static Block bogusWaterFlowing;
	public static Block bouncingBetty;
	public static Block cageTrap;
	public static Block claymore;
	public static Block coalOreMine;
	public static Block cobblestoneMine;
	@Tinted(customTint = 0x15b3a2, hasReinforcedTint = false) public static Block crystalQuartz;
	@Tinted(customTint = 0x15b3a2, hasReinforcedTint = false) public static Block crystalQuartzSlab;
	public static Block diamondOreMine;
	public static Block dirtMine;
	@Tinted(customTint = 0x15b3a2, hasReinforcedTint = false) public static Block doubleCrystalQuartzSlab;
	public static Block emeraldOreMine;
	public static Block frame;
	public static Block furnaceMine;
	public static Block goldOreMine;
	public static Block gravelMine;
	public static Block ims;
	public static Block inventoryScanner;
	public static Block inventoryScannerField;
	public static Block ironFence;
	public static Block ironOreMine;
	public static Block keycardReader;
	public static Block keypad;
	public static Block keypadChest;
	public static Block keypadDoor;
	public static Block keypadFurnace;
	public static Block lapisOreMine;
	public static Block laserBlock;
	public static Block laserField;
	public static Block motionActivatedLight;
	public static Block panicButton;
	public static Block portableRadar;
	public static Block projector;
	public static Block protecto;
	public static Block quartzOreMine;
	public static Block redstoneOreMine;
	@Reinforced @Tinted public static Block reinforcedBoneBlock;
	@Reinforced @Tinted public static Block reinforcedBookshelf;
	@Reinforced @Tinted public static Block reinforcedBrick;
	@Reinforced @Tinted public static Block reinforcedCarpet;
	@Reinforced @Tinted public static Block reinforcedCauldron;
	@Reinforced @Tinted public static Block reinforcedClay;
	@Reinforced @Tinted public static Block reinforcedCobblestone;
	@Reinforced @Tinted public static Block reinforcedCompressedBlocks;
	@Reinforced @Tinted public static Block reinforcedConcrete;
	@Reinforced @Tinted(customTint = 0x15b3a2) public static Block reinforcedCrystalQuartz;
	@Reinforced @Tinted public static Block reinforcedDirt;
	public static Block reinforcedDoor;
	@Reinforced @Tinted public static Block reinforcedCobweb;
	@Tinted(customTint = 0x15b3a2) public static Block reinforcedCrystalQuartzSlab;
	@Tinted(customTint = 0x15b3a2) public static Block reinforcedDoubleCrystalQuartzSlab;
	@Tinted public static Block reinforcedDoubleStoneSlabs;
	@Tinted public static Block reinforcedDoubleStoneSlabs2;
	@Tinted public static Block reinforcedDoubleWoodSlabs;
	@Reinforced @Tinted public static Block reinforcedEndStone;
	@Reinforced @Tinted public static Block reinforcedEndStoneBricks;
	public static Block reinforcedFencegate;
	@Reinforced public static Block reinforcedGlass;
	@Reinforced public static Block reinforcedGlassPane;
	@Reinforced @Tinted public static Block reinforcedGrassPath;
	@Reinforced @Tinted public static Block reinforcedGlowstone;
	@Reinforced @Tinted public static Block reinforcedGrass;
	@Reinforced @Tinted public static Block reinforcedGravel;
	@Reinforced @Tinted public static Block reinforcedHardenedClay;
	@Reinforced @Tinted public static Block reinforcedHopper;
	@Reinforced @Tinted public static Block reinforcedIce;
	public static Block horizontalReinforcedIronBars;
	@Reinforced public static Block reinforcedIronBars;
	@Reinforced public static Block reinforcedIronTrapdoor;
	@Reinforced @Tinted public static Block reinforcedLever;
	@Reinforced @Tinted public static Block reinforcedMetals;
	@Reinforced @Tinted public static Block reinforcedMossyCobblestone;
	@Reinforced @Tinted public static Block reinforcedMycelium;
	@Reinforced @Tinted public static Block reinforcedNetherBrick;
	@Reinforced @Tinted public static Block reinforcedNetherrack;
	@Reinforced @Tinted public static Block reinforcedNetherWartBlock;
	@Reinforced @Tinted public static Block reinforcedNewLogs;
	@Reinforced @Tinted public static Block reinforcedObserver;
	@Reinforced @Tinted public static Block reinforcedObsidian;
	@Reinforced @Tinted public static Block reinforcedOldLogs;
	@Reinforced @Tinted public static Block reinforcedPackedIce;
	@Reinforced @Tinted public static Block reinforcedPrismarine;
	@Reinforced @Tinted public static Block reinforcedPurpur;
	@Reinforced @Tinted public static Block reinforcedQuartz;
	@Reinforced @Tinted public static Block reinforcedRedNetherBrick;
	@Reinforced @Tinted public static Block reinforcedRedSandstone;
	@Reinforced @Tinted public static Block reinforcedRedstoneLamp;
	@Reinforced @Tinted public static Block reinforcedSand;
	@Reinforced @Tinted public static Block reinforcedSandstone;
	@Reinforced @Tinted public static Block reinforcedSeaLantern;
	@Reinforced @Tinted public static Block reinforcedSnowBlock;
	@Reinforced public static Block reinforcedStainedGlass;
	@Reinforced public static Block reinforcedStainedGlassPanes;
	@Reinforced @Tinted public static Block reinforcedStainedHardenedClay;
	@Tinted public static Block reinforcedStairsAcacia;
	@Tinted public static Block reinforcedStairsBirch;
	@Tinted public static Block reinforcedStairsBrick;
	@Tinted public static Block reinforcedStairsCobblestone;
	@Tinted(customTint = 0x15b3a2) public static Block reinforcedStairsCrystalQuartz;
	@Tinted public static Block reinforcedStairsDarkoak;
	@Tinted public static Block reinforcedStairsJungle;
	@Tinted public static Block reinforcedStairsNetherBrick;
	@Tinted public static Block reinforcedStairsOak;
	@Tinted public static Block reinforcedStairsPurpur;
	@Tinted public static Block reinforcedStairsQuartz;
	@Tinted public static Block reinforcedStairsRedSandstone;
	@Tinted public static Block reinforcedStairsSandstone;
	@Tinted public static Block reinforcedStairsSpruce;
	@Tinted public static Block reinforcedStairsStone;
	@Tinted public static Block reinforcedStairsStoneBrick;
	@Reinforced @Tinted public static Block reinforcedStone;
	@Reinforced @Tinted public static Block reinforcedStoneBrick;
	@Reinforced @Tinted public static Block reinforcedStoneButton;
	@Reinforced @Tinted public static Block reinforcedStonePressurePlate;
	@Tinted public static Block reinforcedStoneSlabs;
	@Tinted public static Block reinforcedStoneSlabs2;
	@Reinforced @Tinted public static Block reinforcedWalls;
	@Reinforced @Tinted public static Block reinforcedWoodenButton;
	@Reinforced @Tinted public static Block reinforcedWoodenPressurePlate;
	@Reinforced @Tinted public static Block reinforcedWoodPlanks;
	@Tinted public static Block reinforcedWoodSlabs;
	@Reinforced @Tinted public static Block reinforcedWool;
	public static Block retinalScanner;
	public static Block sandMine;
	public static Block scannerDoor;
	public static Block secretSignStanding;
	public static Block secretSignWall;
	public static Block securityCamera;
	@Tinted(customTint = 0x15b3a2, hasReinforcedTint = false) public static Block stairsCrystalQuartz;
	public static Block stoneMine;
	public static Block trackMine;
	public static Block trophySystem;
	public static Block usernameLogger;
	public static BlockMine mine;
	public static BlockMine mineCut;
	public static BlockStaticLiquid fakeLava;
	public static BlockStaticLiquid fakeWater;

	//Items
	public static Item adminTool;
	public static Item briefcase;
	public static Item cameraMonitor;
	public static Item codebreaker;
	public static Item crystalQuartzItem;
	public static Item fLavaBucket;
	public static Item fWaterBucket;
	public static Item keycardLvl1;
	public static Item keycardLvl2;
	public static Item keycardLvl3;
	public static Item keycardLvl4;
	public static Item keycardLvl5;
	public static Item keypadDoorItem;
	public static Item keyPanel;
	public static Item limitedUseKeycard;
	public static Item reinforcedDoorItem;
	public static Item remoteAccessMine;
	public static Item remoteAccessSentry;
	public static Item scannerDoorItem;
	public static Item scManual;
	public static Item secretSignItem;
	public static Item sentry;
	public static Item taser;
	public static Item taserPowered;
	public static Item universalBlockModifier;
	public static Item universalBlockReinforcerLvL1;
	public static Item universalBlockReinforcerLvL2;
	public static Item universalBlockReinforcerLvL3;
	public static Item universalBlockRemover;
	public static Item universalKeyChanger;
	public static Item universalOwnerChanger;
	public static Item wireCutters;

	//Modules
	public static ItemModule denylistModule;
	public static ItemModule disguiseModule;
	public static ItemModule harmingModule;
	public static ItemModule redstoneModule;
	public static ItemModule smartModule;
	public static ItemModule storageModule;
	public static ItemModule allowlistModule;
	public static ItemModule speedModule;
}
