package net.geforcemods.securitycraft;

import net.geforcemods.securitycraft.blocks.BlockAlarm;
import net.geforcemods.securitycraft.blocks.BlockBlockChangeDetector;
import net.geforcemods.securitycraft.blocks.BlockBlockPocketManager;
import net.geforcemods.securitycraft.blocks.BlockBlockPocketWall;
import net.geforcemods.securitycraft.blocks.BlockCageTrap;
import net.geforcemods.securitycraft.blocks.BlockCrystalQuartz;
import net.geforcemods.securitycraft.blocks.BlockCrystalQuartzSlab;
import net.geforcemods.securitycraft.blocks.BlockCustomStairs;
import net.geforcemods.securitycraft.blocks.BlockDisplayCase;
import net.geforcemods.securitycraft.blocks.BlockFakeLava;
import net.geforcemods.securitycraft.blocks.BlockFakeLavaBase;
import net.geforcemods.securitycraft.blocks.BlockFakeWater;
import net.geforcemods.securitycraft.blocks.BlockFakeWaterBase;
import net.geforcemods.securitycraft.blocks.BlockFloorCeilingKeyPanel;
import net.geforcemods.securitycraft.blocks.BlockFrame;
import net.geforcemods.securitycraft.blocks.BlockInventoryScanner;
import net.geforcemods.securitycraft.blocks.BlockInventoryScannerField;
import net.geforcemods.securitycraft.blocks.BlockIronFence;
import net.geforcemods.securitycraft.blocks.BlockKeycardReader;
import net.geforcemods.securitycraft.blocks.BlockKeypad;
import net.geforcemods.securitycraft.blocks.BlockKeypadChest;
import net.geforcemods.securitycraft.blocks.BlockKeypadDoor;
import net.geforcemods.securitycraft.blocks.BlockKeypadFurnace;
import net.geforcemods.securitycraft.blocks.BlockLaserBlock;
import net.geforcemods.securitycraft.blocks.BlockLaserField;
import net.geforcemods.securitycraft.blocks.BlockLogger;
import net.geforcemods.securitycraft.blocks.BlockMotionActivatedLight;
import net.geforcemods.securitycraft.blocks.BlockOldLitAlarm;
import net.geforcemods.securitycraft.blocks.BlockOwnableStairs;
import net.geforcemods.securitycraft.blocks.BlockPanicButton;
import net.geforcemods.securitycraft.blocks.BlockPortableRadar;
import net.geforcemods.securitycraft.blocks.BlockProjector;
import net.geforcemods.securitycraft.blocks.BlockProtecto;
import net.geforcemods.securitycraft.blocks.BlockRetinalScanner;
import net.geforcemods.securitycraft.blocks.BlockRiftStabilizer;
import net.geforcemods.securitycraft.blocks.BlockScannerDoor;
import net.geforcemods.securitycraft.blocks.BlockSecretSignStanding;
import net.geforcemods.securitycraft.blocks.BlockSecretSignWall;
import net.geforcemods.securitycraft.blocks.BlockSecurityCamera;
import net.geforcemods.securitycraft.blocks.BlockSentryDisguise;
import net.geforcemods.securitycraft.blocks.BlockSonicSecuritySystem;
import net.geforcemods.securitycraft.blocks.BlockTrophySystem;
import net.geforcemods.securitycraft.blocks.BlockWallKeyPanel;
import net.geforcemods.securitycraft.blocks.mines.BlockBouncingBetty;
import net.geforcemods.securitycraft.blocks.mines.BlockClaymore;
import net.geforcemods.securitycraft.blocks.mines.BlockFullMineBase;
import net.geforcemods.securitycraft.blocks.mines.BlockFullMineFalling;
import net.geforcemods.securitycraft.blocks.mines.BlockFurnaceMine;
import net.geforcemods.securitycraft.blocks.mines.BlockIMS;
import net.geforcemods.securitycraft.blocks.mines.BlockMine;
import net.geforcemods.securitycraft.blocks.mines.BlockRedstoneOreMine;
import net.geforcemods.securitycraft.blocks.mines.BlockTrackMine;
import net.geforcemods.securitycraft.blocks.reinforced.BlockHorizontalReinforcedIronBars;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedBase;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedBoneBlock;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedBookshelf;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedButton;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedCarpet;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedCauldron;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedCobweb;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedCompressedBlocks;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedConcrete;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedCrystalQuartz;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedCrystalQuartzSlab;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedDirt;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedDoor;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedEndRod;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedFalling;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedFenceGate;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedGlass;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedGlassPane;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedGlazedTerracotta;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedGrass;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedGrassPath;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedHopper;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedIce;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedIceBase;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedIronBars;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedIronTrapDoor;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedLever;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedMetals;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedMycelium;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedNetherrack;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedNewLog;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedObserver;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedOldLog;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedPistonBase;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedPistonExtension;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedPistonMoving;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedPressurePlate;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedPrismarine;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedPurpur;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedQuartz;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedRedSandstone;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedRedstoneLamp;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedSand;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedSandstone;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedSlabs;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedSlabs2;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedStainedGlass;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedStainedGlassPanes;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedStainedHardenedClay;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedStairs;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedStone;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedStoneBrick;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedWall;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedWood;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedWoodSlabs;
import net.geforcemods.securitycraft.blocks.reinforced.BlockReinforcedWool;
import net.geforcemods.securitycraft.gui.GuiHandler;
import net.geforcemods.securitycraft.items.ItemAdminTool;
import net.geforcemods.securitycraft.items.ItemBriefcase;
import net.geforcemods.securitycraft.items.ItemCameraMonitor;
import net.geforcemods.securitycraft.items.ItemCodebreaker;
import net.geforcemods.securitycraft.items.ItemKeyPanel;
import net.geforcemods.securitycraft.items.ItemKeycard;
import net.geforcemods.securitycraft.items.ItemMineRemoteAccessTool;
import net.geforcemods.securitycraft.items.ItemModifiedBucket;
import net.geforcemods.securitycraft.items.ItemModule;
import net.geforcemods.securitycraft.items.ItemPortableTunePlayer;
import net.geforcemods.securitycraft.items.ItemReinforcedDoor;
import net.geforcemods.securitycraft.items.ItemSCManual;
import net.geforcemods.securitycraft.items.ItemSecretSign;
import net.geforcemods.securitycraft.items.ItemSentry;
import net.geforcemods.securitycraft.items.ItemSentryRemoteAccessTool;
import net.geforcemods.securitycraft.items.ItemSonicSecuritySystem;
import net.geforcemods.securitycraft.items.ItemSpecialDoor;
import net.geforcemods.securitycraft.items.ItemTaser;
import net.geforcemods.securitycraft.items.ItemUniversalBlockReinforcer;
import net.geforcemods.securitycraft.items.ItemUniversalBlockRemover;
import net.geforcemods.securitycraft.items.ItemUniversalKeyChanger;
import net.geforcemods.securitycraft.items.ItemUniversalOwnerChanger;
import net.geforcemods.securitycraft.misc.EnumModuleType;
import net.minecraft.block.BlockPressurePlate.Sensitivity;
import net.minecraft.block.BlockStaticLiquid;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.init.Blocks;
import net.minecraft.item.EnumDyeColor;
import net.minecraft.item.Item;

public class SetupHandler {
	public static void setupBlocks() {
		SCContent.laserBlock = new BlockLaserBlock(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("laser_block").setTranslationKey("securitycraft:laserBlock");
		SCContent.laserField = new BlockLaserField(Material.ROCK).setBlockUnbreakable().setRegistryName("laser").setTranslationKey("securitycraft:laserField");
		SCContent.keypad = new BlockKeypad(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("keypad").setTranslationKey("securitycraft:keypad");
		SCContent.retinalScanner = new BlockRetinalScanner(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("retinal_scanner").setTranslationKey("securitycraft:retinalScanner");
		SCContent.reinforcedDoor = new BlockReinforcedDoor(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("iron_door_reinforced").setTranslationKey("securitycraft:ironDoorReinforced");
		SCContent.fakeLava = (BlockStaticLiquid) new BlockFakeLavaBase(Material.LAVA).setHardness(100.0F).setLightLevel(1.0F).setRegistryName("bogus_lava").setTranslationKey("securitycraft:bogusLava");
		SCContent.bogusLavaFlowing = new BlockFakeLava(Material.LAVA).setHardness(0.0F).setLightLevel(1.0F).setRegistryName("bogus_lava_flowing").setTranslationKey("securitycraft:bogusLavaFlowing");
		SCContent.fakeWater = (BlockStaticLiquid) new BlockFakeWaterBase(Material.WATER).setHardness(100.0F).setRegistryName("bogus_water").setTranslationKey("securitycraft:bogusWater");
		SCContent.bogusWaterFlowing = new BlockFakeWater(Material.WATER).setHardness(0.0F).setRegistryName("bogus_water_flowing").setTranslationKey("securitycraft:bogusWaterFlowing");
		SCContent.keycardReader = new BlockKeycardReader(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("keycard_reader").setTranslationKey("securitycraft:keycardReader");
		SCContent.reinforcedIronTrapdoor = new BlockReinforcedIronTrapDoor(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_iron_trapdoor").setTranslationKey("securitycraft:reinforcedIronTrapdoor");
		SCContent.inventoryScanner = new BlockInventoryScanner(Material.ROCK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("inventory_scanner").setTranslationKey("securitycraft:inventoryScanner");
		SCContent.inventoryScannerField = new BlockInventoryScannerField(Material.GLASS).setBlockUnbreakable().setRegistryName("inventory_scanner_field").setTranslationKey("securitycraft:inventoryScannerField");
		SCContent.cageTrap = new BlockCageTrap(Material.ROCK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("cage_trap").setTranslationKey("securitycraft:cageTrap");
		SCContent.portableRadar = new BlockPortableRadar(Material.CIRCUITS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("portable_radar").setTranslationKey("securitycraft:portableRadar");
		SCContent.reinforcedIronBars = new BlockReinforcedIronBars(Material.IRON, true).setCreativeTab(SecurityCraft.tabSCDecoration).setBlockUnbreakable().setRegistryName("reinforced_iron_bars").setTranslationKey("securitycraft:reinforcedIronBars");
		SCContent.keypadChest = new BlockKeypadChest().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("keypad_chest").setTranslationKey("securitycraft:keypadChest");
		SCContent.usernameLogger = new BlockLogger(Material.ROCK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("username_logger").setTranslationKey("securitycraft:usernameLogger");
		SCContent.alarm = new BlockAlarm(Material.IRON).setBlockUnbreakable().setTickRandomly(true).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("alarm").setTranslationKey("securitycraft:alarm");
		SCContent.alarmLit = new BlockOldLitAlarm(Material.IRON).setBlockUnbreakable().setTickRandomly(true).setRegistryName("alarm_lit").setTranslationKey("securitycraft:alarmLit");
		SCContent.reinforcedStone = new BlockReinforcedStone().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stone").setTranslationKey("securitycraft:reinforcedStone");
		SCContent.reinforcedFencegate = new BlockReinforcedFenceGate().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_fence_gate").setTranslationKey("securitycraft:reinforcedFenceGate");
		SCContent.reinforcedWoodPlanks = new BlockReinforcedWood().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_planks").setTranslationKey("securitycraft:reinforcedPlanks");
		SCContent.panicButton = new BlockPanicButton().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("panic_button").setTranslationKey("securitycraft:panicButton");
		SCContent.frame = new BlockFrame(Material.ROCK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("keypad_frame").setTranslationKey("securitycraft:keypadFrame");
		SCContent.keypadFurnace = new BlockKeypadFurnace(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("keypad_furnace").setTranslationKey("securitycraft:keypadFurnace");
		SCContent.securityCamera = new BlockSecurityCamera(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("security_camera").setTranslationKey("securitycraft:securityCamera");
		SCContent.reinforcedStairsOak = new BlockReinforcedStairs(SCContent.reinforcedWoodPlanks, 0, Blocks.OAK_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_oak").setTranslationKey("securitycraft:reinforcedStairsOak");
		SCContent.reinforcedStairsSpruce = new BlockReinforcedStairs(SCContent.reinforcedWoodPlanks, 1, Blocks.SPRUCE_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_spruce").setTranslationKey("securitycraft:reinforcedStairsSpruce");
		SCContent.reinforcedStairsBirch = new BlockReinforcedStairs(SCContent.reinforcedWoodPlanks, 2, Blocks.BIRCH_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_birch").setTranslationKey("securitycraft:reinforcedStairsBirch");
		SCContent.reinforcedStairsJungle = new BlockReinforcedStairs(SCContent.reinforcedWoodPlanks, 3, Blocks.JUNGLE_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_jungle").setTranslationKey("securitycraft:reinforcedStairsJungle");
		SCContent.reinforcedStairsAcacia = new BlockReinforcedStairs(SCContent.reinforcedWoodPlanks, 4, Blocks.ACACIA_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_acacia").setTranslationKey("securitycraft:reinforcedStairsAcacia");
		SCContent.reinforcedStairsDarkoak = new BlockReinforcedStairs(SCContent.reinforcedWoodPlanks, 5, Blocks.DARK_OAK_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_darkoak").setTranslationKey("securitycraft:reinforcedStairsDarkoak");
		SCContent.reinforcedStairsStone = new BlockOwnableStairs(SCContent.reinforcedStone, 0).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_stone").setTranslationKey("securitycraft:reinforcedStairsStone");
		SCContent.ironFence = new BlockIronFence(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("electrified_iron_fence").setTranslationKey("securitycraft:electrifiedIronFence");
		SCContent.reinforcedGlass = new BlockReinforcedGlass(Material.GLASS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_glass_block").setTranslationKey("securitycraft:reinforcedGlassBlock");
		SCContent.reinforcedStainedGlass = new BlockReinforcedStainedGlass(Material.GLASS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stained_glass").setTranslationKey("securitycraft:reinforcedStainedGlass");
		SCContent.reinforcedDirt = new BlockReinforcedDirt().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_dirt").setTranslationKey("securitycraft:reinforcedDirt");
		SCContent.reinforcedCobblestone = new BlockReinforcedBase(Material.ROCK, 1, Blocks.COBBLESTONE).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_cobblestone").setTranslationKey("securitycraft:reinforcedCobblestone");
		SCContent.reinforcedStairsCobblestone = new BlockReinforcedStairs(SCContent.reinforcedCobblestone, 0, Blocks.STONE_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_cobblestone").setTranslationKey("securitycraft:reinforcedStairsCobblestone");
		SCContent.reinforcedSandstone = new BlockReinforcedSandstone().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_sandstone").setTranslationKey("securitycraft:reinforcedSandstone");
		SCContent.reinforcedStairsSandstone = new BlockReinforcedStairs(SCContent.reinforcedSandstone, 0, Blocks.SANDSTONE_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_sandstone").setTranslationKey("securitycraft:reinforcedStairsSandstone");
		SCContent.reinforcedWoodSlabs = new BlockReinforcedWoodSlabs(false).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_wood_slabs").setTranslationKey("securitycraft:reinforcedWoodSlabs");
		SCContent.reinforcedDoubleWoodSlabs = new BlockReinforcedWoodSlabs(true).setBlockUnbreakable().setRegistryName("reinforced_double_wood_slabs").setTranslationKey("securitycraft:reinforcedDoubleWoodSlabs");
		SCContent.reinforcedStoneSlabs = new BlockReinforcedSlabs(false, Material.ROCK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stone_slabs").setTranslationKey("securitycraft:reinforcedStoneSlabs");
		SCContent.reinforcedDoubleStoneSlabs = new BlockReinforcedSlabs(true, Material.ROCK).setBlockUnbreakable().setRegistryName("reinforced_double_stone_slabs").setTranslationKey("securitycraft:reinforcedDoubleStoneSlabs");
		SCContent.protecto = new BlockProtecto(Material.IRON).setBlockUnbreakable().setLightLevel(0.5F).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("protecto").setTranslationKey("securitycraft:protecto");
		SCContent.scannerDoor = new BlockScannerDoor(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("scanner_door").setTranslationKey("securitycraft:scannerDoor");
		SCContent.reinforcedStoneBrick = new BlockReinforcedStoneBrick().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stone_brick").setTranslationKey("securitycraft:reinforcedStoneBrick");
		SCContent.reinforcedStairsStoneBrick = new BlockReinforcedStairs(SCContent.reinforcedStoneBrick, 0, Blocks.STONE_BRICK_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_stone_brick").setTranslationKey("securitycraft:reinforcedStairsStoneBrick");
		SCContent.reinforcedMossyCobblestone = new BlockReinforcedBase(Material.ROCK, 1, Blocks.MOSSY_COBBLESTONE).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_mossy_cobblestone").setTranslationKey("securitycraft:reinforcedMossyCobblestone");
		SCContent.reinforcedBrick = new BlockReinforcedBase(Material.ROCK, 1, Blocks.BRICK_BLOCK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_brick").setTranslationKey("securitycraft:reinforcedBrick");
		SCContent.reinforcedStairsBrick = new BlockReinforcedStairs(SCContent.reinforcedBrick, 0, Blocks.BRICK_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_brick").setTranslationKey("securitycraft:reinforcedStairsBrick");
		SCContent.reinforcedNetherBrick = new BlockReinforcedBase(Material.ROCK, 1, Blocks.NETHER_BRICK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_nether_brick").setTranslationKey("securitycraft:reinforcedNetherBrick");
		SCContent.reinforcedStairsNetherBrick = new BlockReinforcedStairs(SCContent.reinforcedNetherBrick, 0, Blocks.NETHER_BRICK_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_nether_brick").setTranslationKey("securitycraft:reinforcedStairsNetherBrick");
		SCContent.reinforcedHardenedClay = new BlockReinforcedBase(Material.ROCK, 1, Blocks.HARDENED_CLAY).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_hardened_clay").setTranslationKey("securitycraft:reinforcedHardenedClay");
		SCContent.reinforcedStainedHardenedClay = new BlockReinforcedStainedHardenedClay().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stained_hardened_clay").setTranslationKey("securitycraft:reinforcedStainedHardenedClay");
		SCContent.reinforcedOldLogs = new BlockReinforcedOldLog().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_logs").setTranslationKey("securitycraft:reinforcedLogs");
		SCContent.reinforcedNewLogs = new BlockReinforcedNewLog().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_logs2").setTranslationKey("securitycraft:reinforcedLogs2");
		SCContent.reinforcedMetals = new BlockReinforcedMetals().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_metals").setTranslationKey("securitycraft:reinforcedMetals");
		SCContent.reinforcedCompressedBlocks = new BlockReinforcedCompressedBlocks().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_compressed_blocks").setTranslationKey("securitycraft:reinforcedCompressedBlocks");
		SCContent.reinforcedWool = new BlockReinforcedWool().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_wool").setTranslationKey("securitycraft:reinforcedWool");
		SCContent.reinforcedQuartz = new BlockReinforcedQuartz().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_quartz").setTranslationKey("securitycraft:reinforcedQuartz");
		SCContent.reinforcedStairsQuartz = new BlockReinforcedStairs(SCContent.reinforcedQuartz, 0, Blocks.QUARTZ_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_quartz").setTranslationKey("securitycraft:reinforcedStairsQuartz");
		SCContent.reinforcedPrismarine = new BlockReinforcedPrismarine().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_prismarine").setTranslationKey("securitycraft:reinforcedPrismarine");
		SCContent.reinforcedRedSandstone = new BlockReinforcedRedSandstone().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_red_sandstone").setTranslationKey("securitycraft:reinforcedRedSandstone");
		SCContent.reinforcedStairsRedSandstone = new BlockReinforcedStairs(SCContent.reinforcedRedSandstone, 0, Blocks.RED_SANDSTONE_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_red_sandstone").setTranslationKey("securitycraft:reinforcedStairsRedSandstone");
		SCContent.reinforcedStoneSlabs2 = new BlockReinforcedSlabs2(false, Material.ROCK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stone_slabs2").setTranslationKey("securitycraft:reinforcedStoneSlabs2");
		SCContent.reinforcedDoubleStoneSlabs2 = new BlockReinforcedSlabs2(true, Material.ROCK).setBlockUnbreakable().setRegistryName("reinforced_double_stone_slabs2").setTranslationKey("securitycraft:reinforcedDoubleStoneSlabs2");
		SCContent.reinforcedEndStoneBricks = new BlockReinforcedBase(Material.ROCK, 1, Blocks.END_BRICKS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_end_stone_bricks").setTranslationKey("securitycraft:reinforcedEndStoneBricks");
		SCContent.reinforcedRedNetherBrick = new BlockReinforcedBase(Material.ROCK, 1, Blocks.RED_NETHER_BRICK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_red_nether_brick").setTranslationKey("securitycraft:reinforcedRedNetherBrick");
		SCContent.reinforcedPurpur = new BlockReinforcedPurpur().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_purpur").setTranslationKey("securitycraft:reinforcedPurpur");
		SCContent.reinforcedStairsPurpur = new BlockReinforcedStairs(SCContent.reinforcedPurpur, 0, Blocks.PURPUR_STAIRS).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_purpur").setTranslationKey("securitycraft:reinforcedStairsPurpur");
		SCContent.reinforcedConcrete = new BlockReinforcedConcrete().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_concrete").setTranslationKey("securitycraft:reinforcedConcrete");
		SCContent.secretSignStanding = new BlockSecretSignStanding().setBlockUnbreakable().setRegistryName("secret_sign_standing").setTranslationKey("securitycraft:secretSign");
		SCContent.secretSignWall = new BlockSecretSignWall().setBlockUnbreakable().setRegistryName("secret_sign_wall").setTranslationKey("securitycraft:secretSign");
		SCContent.motionActivatedLight = new BlockMotionActivatedLight(Material.GLASS).setBlockUnbreakable().setRegistryName("motion_activated_light").setTranslationKey("securitycraft:motionActivatedLight").setCreativeTab(SecurityCraft.tabSCTechnical);
		SCContent.reinforcedObsidian = new BlockReinforcedBase(Material.ROCK, 1, Blocks.OBSIDIAN).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_obsidian").setTranslationKey("securitycraft:reinforcedObsidian");
		SCContent.reinforcedNetherrack = new BlockReinforcedNetherrack(Material.ROCK, 1, Blocks.NETHERRACK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_netherrack").setTranslationKey("securitycraft:reinforcedNetherrack");
		SCContent.reinforcedEndStone = new BlockReinforcedBase(Material.ROCK, 1, Blocks.END_STONE).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_end_stone").setTranslationKey("securitycraft:reinforcedEndStone");
		SCContent.reinforcedSeaLantern = new BlockReinforcedBase(Material.GLASS, 1, Blocks.SEA_LANTERN).setBlockUnbreakable().setLightLevel(1.0F).setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_sea_lantern").setTranslationKey("securitycraft:reinforcedSeaLantern");
		SCContent.reinforcedBoneBlock = new BlockReinforcedBoneBlock(Material.ROCK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_bone_block").setTranslationKey("securitycraft:reinforcedBoneBlock");
		SCContent.reinforcedGlassPane = new BlockReinforcedGlassPane().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_glass_pane").setTranslationKey("securitycraft:reinforcedGlassPane");
		SCContent.reinforcedStainedGlassPanes = new BlockReinforcedStainedGlassPanes().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stained_panes").setTranslationKey("securitycraft:reinforcedStainedGlassPanes");
		SCContent.reinforcedCarpet = new BlockReinforcedCarpet().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_carpet").setTranslationKey("securitycraft:reinforcedCarpet");
		SCContent.reinforcedGlowstone = new BlockReinforcedBase(Material.GLASS, 1, Blocks.GLOWSTONE).setBlockUnbreakable().setLightLevel(1.0F).setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_glowstone").setTranslationKey("securitycraft:reinforcedGlowstone");
		SCContent.reinforcedSand = new BlockReinforcedSand().setCreativeTab(SecurityCraft.tabSCDecoration).setBlockUnbreakable().setRegistryName("reinforced_sand").setTranslationKey("securitycraft:reinforcedSand");
		SCContent.reinforcedGravel = new BlockReinforcedFalling(Material.GROUND, Blocks.GRAVEL).setCreativeTab(SecurityCraft.tabSCDecoration).setBlockUnbreakable().setRegistryName("reinforced_gravel").setTranslationKey("securitycraft:reinforcedGravel");
		SCContent.trophySystem = new BlockTrophySystem(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("trophy_system").setTranslationKey("securitycraft:trophy_system");
		SCContent.crystalQuartz = new BlockCrystalQuartz().setHardness(0.8F).setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("crystal_quartz").setTranslationKey("securitycraft:crystalQuartz");
		SCContent.reinforcedCrystalQuartz = new BlockReinforcedCrystalQuartz().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_crystal_quartz").setTranslationKey("securitycraft:reinforcedCrystalQuartz");
		SCContent.crystalQuartzSlab = new BlockCrystalQuartzSlab(false, Material.ROCK).setHardness(2.0F).setResistance(10.0F).setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("crystal_quartz_slab").setTranslationKey("securitycraft:crystalQuartzSlab");
		SCContent.doubleCrystalQuartzSlab = new BlockCrystalQuartzSlab(true, Material.ROCK).setHardness(2.0F).setResistance(10.0F).setRegistryName("double_crystal_quartz_slab").setTranslationKey("securitycraft:doubleCrystalQuartzSlab");
		SCContent.reinforcedCrystalQuartzSlab = new BlockReinforcedCrystalQuartzSlab(false, Material.ROCK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_crystal_quartz_slab").setTranslationKey("securitycraft:reinforcedCrystalQuartzSlab");
		SCContent.reinforcedDoubleCrystalQuartzSlab = new BlockReinforcedCrystalQuartzSlab(true, Material.ROCK).setBlockUnbreakable().setRegistryName("reinforced_double_crystal_quartz_slab").setTranslationKey("securitycraft:reinforcedDoubleCrystalQuartzSlab");
		SCContent.stairsCrystalQuartz = new BlockCustomStairs(SCContent.crystalQuartz.getDefaultState()).setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("stairs_crystal_quartz").setTranslationKey("securitycraft:stairsCrystalQuartz");
		SCContent.reinforcedStairsCrystalQuartz = new BlockReinforcedStairs(SCContent.reinforcedCrystalQuartz, 0, SCContent.stairsCrystalQuartz).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stairs_crystal_quartz").setTranslationKey("securitycraft:reinforcedStairsCrystalQuartz");
		SCContent.blockPocketWall = new BlockBlockPocketWall().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("block_pocket_wall").setTranslationKey("securitycraft:blockPocketWall");
		SCContent.blockPocketManager = new BlockBlockPocketManager().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("block_pocket_manager").setTranslationKey("securitycraft:blockPocketManager");
		SCContent.reinforcedStonePressurePlate = new BlockReinforcedPressurePlate(Material.ROCK, Sensitivity.MOBS, SoundType.STONE, Blocks.STONE_PRESSURE_PLATE).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stone_pressure_plate").setTranslationKey("securitycraft:reinforced_stone_pressure_plate");
		SCContent.reinforcedWoodenPressurePlate = new BlockReinforcedPressurePlate(Material.WOOD, Sensitivity.EVERYTHING, SoundType.WOOD, Blocks.WOODEN_PRESSURE_PLATE).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_wooden_pressure_plate").setTranslationKey("securitycraft:reinforced_wooden_pressure_plate");
		SCContent.reinforcedBookshelf = new BlockReinforcedBookshelf(Material.WOOD, 1, Blocks.BOOKSHELF).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_bookshelf").setTranslationKey("securitycraft:reinforcedBookshelf");
		SCContent.horizontalReinforcedIronBars = new BlockHorizontalReinforcedIronBars().setBlockUnbreakable().setRegistryName("horizontal_reinforced_iron_bars");
		SCContent.reinforcedWalls = new BlockReinforcedWall().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_walls").setTranslationKey("securitycraft:reinforced_walls");
		SCContent.reinforcedStickyPiston = new BlockReinforcedPistonBase(true).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_sticky_piston").setTranslationKey("securitycraft:reinforced_sticky_piston");
		SCContent.reinforcedPiston = new BlockReinforcedPistonBase(false).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_piston").setTranslationKey("securitycraft:reinforced_piston");
		SCContent.reinforcedPistonHead = new BlockReinforcedPistonExtension().setBlockUnbreakable().setRegistryName("reinforced_piston_head").setTranslationKey("securitycraft:reinforced_piston_head");
		SCContent.reinforcedPistonExtension = new BlockReinforcedPistonMoving().setBlockUnbreakable().setRegistryName("reinforced_piston_extension").setTranslationKey("securitycraft:reinforced_piston_extension");
		SCContent.reinforcedObserver = new BlockReinforcedObserver().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_observer").setTranslationKey("securitycraft:reinforced_observer");
		SCContent.reinforcedRedstoneLamp = new BlockReinforcedRedstoneLamp().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_redstone_lamp").setTranslationKey("securitycraft:reinforced_redstone_lamp");
		SCContent.reinforcedCobweb = new BlockReinforcedCobweb().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_cobweb").setTranslationKey("securitycraft:reinforced_cobweb");
		SCContent.reinforcedGrass = new BlockReinforcedGrass().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_grass").setTranslationKey("securitycraft:reinforced_grass");
		SCContent.reinforcedSnowBlock = new BlockReinforcedBase(Material.CRAFTED_SNOW, 1, SoundType.SNOW, Blocks.SNOW).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_snow_block").setTranslationKey("securitycraft:reinforced_snow_block");
		SCContent.reinforcedIce = new BlockReinforcedIce(Material.ICE, 1, SoundType.GLASS, Blocks.ICE).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_ice").setTranslationKey("securitycraft:reinforced_ice");
		SCContent.reinforcedPackedIce = new BlockReinforcedIceBase(Material.PACKED_ICE, 1, SoundType.GLASS, Blocks.PACKED_ICE).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_packed_ice").setTranslationKey("securitycraft:reinforced_packed_ice");
		SCContent.reinforcedMycelium = new BlockReinforcedMycelium().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_mycelium").setTranslationKey("securitycraft:reinforced_mycelium");
		SCContent.reinforcedClay = new BlockReinforcedBase(Material.GROUND, 1, Blocks.CLAY).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_clay").setTranslationKey("securitycraft:reinforced_clay");
		SCContent.reinforcedNetherWartBlock = new BlockReinforcedBase(Material.GRASS, 1, SoundType.WOOD, Blocks.NETHER_WART_BLOCK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_nether_wart_block").setTranslationKey("securitycraft:reinforced_nether_wart_block");
		SCContent.reinforcedGrassPath = new BlockReinforcedGrassPath().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_grass_path").setTranslationKey("securitycraft:reinforced_grass_path");
		SCContent.reinforcedStoneButton = new BlockReinforcedButton(false).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_stone_button").setTranslationKey("securitycraft:reinforced_stone_button");
		SCContent.reinforcedWoodenButton = new BlockReinforcedButton(true).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_wooden_button").setTranslationKey("securitycraft:reinforced_wooden_button");
		SCContent.reinforcedLever = new BlockReinforcedLever().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_lever").setTranslationKey("securitycraft:reinforced_lever");
		SCContent.reinforcedHopper = new BlockReinforcedHopper().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_hopper").setTranslationKey("securitycraft:reinforced_hopper");
		SCContent.projector = new BlockProjector().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("projector").setTranslationKey("securitycraft:projector");
		SCContent.keypadDoor = new BlockKeypadDoor(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("keypad_door").setTranslationKey("securitycraft:keypad_door");
		SCContent.reinforcedCauldron = new BlockReinforcedCauldron().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_cauldron").setTranslationKey("securitycraft:reinforced_cauldron");
		SCContent.keyPanelFloorCeilingBlock = new BlockFloorCeilingKeyPanel(Material.IRON).setCreativeTab(SecurityCraft.tabSCTechnical).setBlockUnbreakable().setRegistryName("floor_ceiling_key_panel").setTranslationKey("securitycraft:key_panel");
		SCContent.keyPanelWallBlock = new BlockWallKeyPanel(Material.IRON).setBlockUnbreakable().setRegistryName("wall_key_panel").setTranslationKey("securitycraft:key_panel");
		SCContent.sonicSecuritySystem = new BlockSonicSecuritySystem(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("sonic_security_system").setTranslationKey("securitycraft:sonic_security_system");
		SCContent.blockChangeDetector = new BlockBlockChangeDetector(Material.ROCK).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("block_change_detector").setTranslationKey("securitycraft:block_change_detector");
		SCContent.sentryDisguise = new BlockSentryDisguise(Material.AIR).setBlockUnbreakable().setHardness(-1.0F).setRegistryName("sentry_disguise");
		SCContent.reinforcedEndRod = new BlockReinforcedEndRod().setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_end_rod").setTranslationKey("securitycraft:reinforced_end_rod");
		SCContent.reinforcedWhiteGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.WHITE, Blocks.WHITE_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_white_glazed_terracotta").setTranslationKey("securitycraft:reinforced_white_glazed_terracotta");
		SCContent.reinforcedOrangeGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.ORANGE, Blocks.ORANGE_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_orange_glazed_terracotta").setTranslationKey("securitycraft:reinforced_orange_glazed_terracotta");
		SCContent.reinforcedMagentaGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.MAGENTA, Blocks.MAGENTA_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_magenta_glazed_terracotta").setTranslationKey("securitycraft:reinforced_magenta_glazed_terracotta");
		SCContent.reinforcedLightBlueGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_light_blue_glazed_terracotta").setTranslationKey("securitycraft:reinforced_light_blue_glazed_terracotta");
		SCContent.reinforcedYellowGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.YELLOW, Blocks.YELLOW_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_yellow_glazed_terracotta").setTranslationKey("securitycraft:reinforced_yellow_glazed_terracotta");
		SCContent.reinforcedLimeGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.LIME, Blocks.LIME_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_lime_glazed_terracotta").setTranslationKey("securitycraft:reinforced_lime_glazed_terracotta");
		SCContent.reinforcedPinkGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.PINK, Blocks.PINK_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_pink_glazed_terracotta").setTranslationKey("securitycraft:reinforced_pink_glazed_terracotta");
		SCContent.reinforcedGrayGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.GRAY, Blocks.GRAY_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_gray_glazed_terracotta").setTranslationKey("securitycraft:reinforced_gray_glazed_terracotta");
		SCContent.reinforcedSilverGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.SILVER, Blocks.SILVER_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_silver_glazed_terracotta").setTranslationKey("securitycraft:reinforced_light_gray_glazed_terracotta");
		SCContent.reinforcedCyanGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.CYAN, Blocks.CYAN_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_cyan_glazed_terracotta").setTranslationKey("securitycraft:reinforced_cyan_glazed_terracotta");
		SCContent.reinforcedPurpleGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.PURPLE, Blocks.PURPLE_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_purple_glazed_terracotta").setTranslationKey("securitycraft:reinforced_purple_glazed_terracotta");
		SCContent.reinforcedBlueGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.BLUE, Blocks.BLUE_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_blue_glazed_terracotta").setTranslationKey("securitycraft:reinforced_blue_glazed_terracotta");
		SCContent.reinforcedBrownGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.BROWN, Blocks.BROWN_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_brown_glazed_terracotta").setTranslationKey("securitycraft:reinforced_brown_glazed_terracotta");
		SCContent.reinforcedGreenGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.GREEN, Blocks.GREEN_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_green_glazed_terracotta").setTranslationKey("securitycraft:reinforced_green_glazed_terracotta");
		SCContent.reinforcedRedGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.RED, Blocks.RED_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_red_glazed_terracotta").setTranslationKey("securitycraft:reinforced_red_glazed_terracotta");
		SCContent.reinforcedBlackGlazedTerracotta = new BlockReinforcedGlazedTerracotta(EnumDyeColor.BLACK, Blocks.BLACK_GLAZED_TERRACOTTA).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("reinforced_black_glazed_terracotta").setTranslationKey("securitycraft:reinforced_black_glazed_terracotta");
		SCContent.riftStabilizer = new BlockRiftStabilizer(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("rift_stabilizer").setTranslationKey("securitycraft:rift_stabilizer");
		SCContent.displayCase = new BlockDisplayCase(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCDecoration).setRegistryName("display_case").setTranslationKey("securitycraft:display_case");
	}

	public static void setupMines() {
		SCContent.mine = (BlockMine) new BlockMine(Material.CIRCUITS).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 1F).setCreativeTab(SecurityCraft.tabSCMine).setRegistryName("mine").setTranslationKey("securitycraft:mine");
		SCContent.mineCut = (BlockMine) new BlockMine(Material.CIRCUITS).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 1F).setRegistryName("mine_cut").setTranslationKey("securitycraft:mineCut");
		SCContent.dirtMine = new BlockFullMineBase(Material.GROUND, Blocks.DIRT, 0).setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 0.5F).setRegistryName("dirt_mine").setTranslationKey("securitycraft:dirtMine");
		SCContent.stoneMine = new BlockFullMineBase(Material.ROCK, Blocks.STONE, 0).setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 1.5F).setRegistryName("stone_mine").setTranslationKey("securitycraft:stoneMine");
		SCContent.cobblestoneMine = new BlockFullMineBase(Material.ROCK, Blocks.COBBLESTONE, 0).setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 2.0F).setRegistryName("cobblestone_mine").setTranslationKey("securitycraft:cobblestoneMine");
		SCContent.sandMine = new BlockFullMineFalling(Material.SAND, Blocks.SAND).setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 0.5F).setRegistryName("sand_mine").setTranslationKey("securitycraft:sandMine");
		SCContent.diamondOreMine = new BlockFullMineBase(Material.ROCK, Blocks.DIAMOND_ORE, 2).setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 3.0F).setRegistryName("diamond_mine").setTranslationKey("securitycraft:diamondMine");
		SCContent.furnaceMine = new BlockFurnaceMine(Material.ROCK).setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 3.5F).setRegistryName("furnace_mine").setTranslationKey("securitycraft:furnaceMine");
		SCContent.gravelMine = new BlockFullMineFalling(Material.GROUND, Blocks.GRAVEL).setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 0.6F).setRegistryName("gravel_mine").setTranslationKey("securitycraft:gravelMine");
		SCContent.trackMine = new BlockTrackMine().setHardness(!ConfigHandler.ableToBreakMines ? -1F : 0.7F).setCreativeTab(SecurityCraft.tabSCMine).setRegistryName("track_mine").setTranslationKey("securitycraft:trackMine");
		SCContent.bouncingBetty = new BlockBouncingBetty(Material.CIRCUITS).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 1F).setCreativeTab(SecurityCraft.tabSCMine).setRegistryName("bouncing_betty").setTranslationKey("securitycraft:bouncingBetty");
		SCContent.claymore = new BlockClaymore(Material.CIRCUITS).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 1F).setCreativeTab(SecurityCraft.tabSCMine).setRegistryName("claymore").setTranslationKey("securitycraft:claymore");
		SCContent.ims = new BlockIMS(Material.IRON).setBlockUnbreakable().setCreativeTab(SecurityCraft.tabSCMine).setRegistryName("ims").setTranslationKey("securitycraft:ims");
		SCContent.coalOreMine = new BlockFullMineBase(Material.ROCK, Blocks.COAL_ORE, 0).setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 3.0F).setRegistryName("coal_mine").setTranslationKey("securitycraft:coal_mine");
		SCContent.emeraldOreMine = new BlockFullMineBase(Material.ROCK, Blocks.EMERALD_ORE, 2).setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 3.0F).setRegistryName("emerald_mine").setTranslationKey("securitycraft:emerald_mine");
		SCContent.goldOreMine = new BlockFullMineBase(Material.ROCK, Blocks.GOLD_ORE, 2).setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 3.0F).setRegistryName("gold_mine").setTranslationKey("securitycraft:gold_mine");
		SCContent.ironOreMine = new BlockFullMineBase(Material.ROCK, Blocks.IRON_ORE, 1).setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 3.0F).setRegistryName("iron_mine").setTranslationKey("securitycraft:iron_mine");
		SCContent.lapisOreMine = new BlockFullMineBase(Material.ROCK, Blocks.LAPIS_ORE, 1).setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 3.0F).setRegistryName("lapis_mine").setTranslationKey("securitycraft:lapis_mine");
		SCContent.quartzOreMine = new BlockFullMineBase(Material.ROCK, Blocks.QUARTZ_ORE, 0).setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 3.0F).setRegistryName("quartz_mine").setTranslationKey("securitycraft:quartz_mine");
		SCContent.redstoneOreMine = new BlockRedstoneOreMine().setCreativeTab(SecurityCraft.tabSCMine).setHardness(!ConfigHandler.ableToBreakMines ? -1F : 3.0F).setRegistryName("redstone_mine").setTranslationKey("securitycraft:redstone_mine");
	}

	public static void setupItems() {
		SCContent.codebreaker = new ItemCodebreaker().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("codebreaker").setTranslationKey("securitycraft:codebreaker");
		SCContent.keycardLvl1 = new ItemKeycard(0).setRegistryName("keycard_lv1").setTranslationKey("securitycraft:keycardLV1");
		SCContent.keycardLvl2 = new ItemKeycard(1).setRegistryName("keycard_lv2").setTranslationKey("securitycraft:keycardLV2");
		SCContent.keycardLvl3 = new ItemKeycard(2).setRegistryName("keycard_lv3").setTranslationKey("securitycraft:keycardLV3");
		SCContent.keycardLvl4 = new ItemKeycard(3).setRegistryName("keycard_lv4").setTranslationKey("securitycraft:keycardLV4");
		SCContent.keycardLvl5 = new ItemKeycard(4).setRegistryName("keycard_lv5").setTranslationKey("securitycraft:keycardLV5");
		SCContent.limitedUseKeycard = new ItemKeycard(-1).setRegistryName("limited_use_keycard").setTranslationKey("securitycraft:limitedUseKeycard");
		SCContent.reinforcedDoorItem = new ItemReinforcedDoor(SCContent.reinforcedDoor).setRegistryName("door_indestructible_iron_item").setTranslationKey("securitycraft:doorIndestructibleIronItem").setCreativeTab(SecurityCraft.tabSCDecoration);
		SCContent.universalBlockRemover = new ItemUniversalBlockRemover().setMaxStackSize(1).setMaxDamage(476).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("universal_block_remover").setTranslationKey("securitycraft:universalBlockRemover");
		SCContent.remoteAccessMine = new ItemMineRemoteAccessTool().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("remote_access_mine").setTranslationKey("securitycraft:remoteAccessMine");
		SCContent.remoteAccessSentry = new ItemSentryRemoteAccessTool().setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("remote_access_sentry").setTranslationKey("securitycraft:remoteAccessSentry");
		SCContent.fWaterBucket = new ItemModifiedBucket(SCContent.bogusWaterFlowing).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("bucket_f_water").setTranslationKey("securitycraft:bucketFWater");
		SCContent.fLavaBucket = new ItemModifiedBucket(SCContent.bogusLavaFlowing).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("bucket_f_lava").setTranslationKey("securitycraft:bucketFLava");
		SCContent.universalBlockModifier = new Item().setMaxStackSize(1).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("universal_block_modifier").setTranslationKey("securitycraft:universalBlockModifier");
		SCContent.redstoneModule = (ItemModule) new ItemModule(EnumModuleType.REDSTONE, false).setRegistryName("redstone_module").setTranslationKey("securitycraft:redstoneModule");
		SCContent.allowlistModule = (ItemModule) new ItemModule(EnumModuleType.ALLOWLIST, true, true, GuiHandler.MODULES).setRegistryName("whitelist_module").setTranslationKey("securitycraft:whitelistModule");
		SCContent.denylistModule = (ItemModule) new ItemModule(EnumModuleType.DENYLIST, true, true, GuiHandler.MODULES).setRegistryName("blacklist_module").setTranslationKey("securitycraft:blacklistModule");
		SCContent.harmingModule = (ItemModule) new ItemModule(EnumModuleType.HARMING, false).setRegistryName("harming_module").setTranslationKey("securitycraft:harmingModule");
		SCContent.smartModule = (ItemModule) new ItemModule(EnumModuleType.SMART, false).setRegistryName("smart_module").setTranslationKey("securitycraft:smartModule");
		SCContent.storageModule = (ItemModule) new ItemModule(EnumModuleType.STORAGE, false).setRegistryName("storage_module").setTranslationKey("securitycraft:storageModule");
		SCContent.disguiseModule = (ItemModule) new ItemModule(EnumModuleType.DISGUISE, false, true, GuiHandler.DISGUISE_MODULE).setRegistryName("disguise_module").setTranslationKey("securitycraft:disguiseModule");
		SCContent.speedModule = (ItemModule) new ItemModule(EnumModuleType.SPEED, false).setRegistryName("speed_module").setTranslationKey("securitycraft:speed_module");
		SCContent.wireCutters = new Item().setMaxStackSize(1).setMaxDamage(476).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("wire_cutters").setTranslationKey("securitycraft:wireCutters");
		SCContent.keyPanel = new ItemKeyPanel().setRegistryName("keypad_item");
		SCContent.adminTool = new ItemAdminTool().setMaxStackSize(1).setRegistryName("admin_tool").setTranslationKey("securitycraft:adminTool");
		SCContent.cameraMonitor = new ItemCameraMonitor().setMaxStackSize(1).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("camera_monitor").setTranslationKey("securitycraft:cameraMonitor");
		SCContent.scManual = new ItemSCManual().setMaxStackSize(1).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("sc_manual").setTranslationKey("securitycraft:scManual");
		SCContent.taser = new ItemTaser(false).setMaxStackSize(1).setRegistryName("taser").setTranslationKey("securitycraft:taser");
		SCContent.taserPowered = new ItemTaser(true).setMaxStackSize(1).setRegistryName("taser_powered").setTranslationKey("securitycraft:taser");
		SCContent.universalOwnerChanger = new ItemUniversalOwnerChanger().setMaxStackSize(1).setMaxDamage(48).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("universal_owner_changer").setTranslationKey("securitycraft:universalOwnerChanger");
		SCContent.universalBlockReinforcerLvL1 = new ItemUniversalBlockReinforcer(300).setMaxStackSize(1).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("universal_block_reinforcer_lvl1").setTranslationKey("securitycraft:universalBlockReinforcerLvL1");
		SCContent.universalBlockReinforcerLvL2 = new ItemUniversalBlockReinforcer(2700).setMaxStackSize(1).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("universal_block_reinforcer_lvl2").setTranslationKey("securitycraft:universalBlockReinforcerLvL2");
		SCContent.universalBlockReinforcerLvL3 = new ItemUniversalBlockReinforcer(0).setMaxStackSize(1).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("universal_block_reinforcer_lvl3").setTranslationKey("securitycraft:universalBlockReinforcerLvL3");
		SCContent.briefcase = new ItemBriefcase().setMaxStackSize(1).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("briefcase").setTranslationKey("securitycraft:briefcase");
		SCContent.universalKeyChanger = new ItemUniversalKeyChanger().setMaxStackSize(1).setCreativeTab(SecurityCraft.tabSCTechnical).setRegistryName("universal_key_changer").setTranslationKey("securitycraft:universalKeyChanger");
		SCContent.scannerDoorItem = new ItemSpecialDoor(SCContent.scannerDoor).setRegistryName("scanner_door_item").setTranslationKey("securitycraft:scannerDoorItem").setCreativeTab(SecurityCraft.tabSCDecoration);
		SCContent.secretSignItem = new ItemSecretSign().setRegistryName("secret_sign_item").setTranslationKey("securitycraft:secretSignItem").setCreativeTab(SecurityCraft.tabSCDecoration);
		SCContent.sentry = new ItemSentry().setRegistryName("sentry").setTranslationKey("securitycraft:sentry").setCreativeTab(SecurityCraft.tabSCTechnical);
		SCContent.crystalQuartzItem = new Item().setRegistryName("crystal_quartz_item").setTranslationKey("securitycraft:crystalQuartzItem").setCreativeTab(SecurityCraft.tabSCDecoration);
		SCContent.keypadDoorItem = new ItemSpecialDoor(SCContent.keypadDoor).setRegistryName("keypad_door_item").setTranslationKey("securitycraft:keypad_door_item").setCreativeTab(SecurityCraft.tabSCDecoration);
		SCContent.sonicSecuritySystemItem = new ItemSonicSecuritySystem().setTranslationKey("securitycraft:sonic_security_system").setCreativeTab(SecurityCraft.tabSCTechnical);
		SCContent.portableTunePlayer = new ItemPortableTunePlayer().setRegistryName("portable_tune_player").setTranslationKey("securitycraft:portable_tune_player").setCreativeTab(SecurityCraft.tabSCTechnical);
	}
}
