package net.geforcemods.securitycraft;

import net.geforcemods.securitycraft.blocks.AlarmBlock;
import net.geforcemods.securitycraft.blocks.BlockPocketBlock;
import net.geforcemods.securitycraft.blocks.BlockPocketManagerBlock;
import net.geforcemods.securitycraft.blocks.BlockPocketWallBlock;
import net.geforcemods.securitycraft.blocks.CageTrapBlock;
import net.geforcemods.securitycraft.blocks.CustomStairsBlock;
import net.geforcemods.securitycraft.blocks.FakeLavaBlock;
import net.geforcemods.securitycraft.blocks.FakeWaterBlock;
import net.geforcemods.securitycraft.blocks.FrameBlock;
import net.geforcemods.securitycraft.blocks.InventoryScannerBlock;
import net.geforcemods.securitycraft.blocks.InventoryScannerFieldBlock;
import net.geforcemods.securitycraft.blocks.IronFenceBlock;
import net.geforcemods.securitycraft.blocks.KeycardReaderBlock;
import net.geforcemods.securitycraft.blocks.KeypadBlock;
import net.geforcemods.securitycraft.blocks.KeypadChestBlock;
import net.geforcemods.securitycraft.blocks.KeypadFurnaceBlock;
import net.geforcemods.securitycraft.blocks.LaserBlock;
import net.geforcemods.securitycraft.blocks.LaserFieldBlock;
import net.geforcemods.securitycraft.blocks.LoggerBlock;
import net.geforcemods.securitycraft.blocks.MotionActivatedLightBlock;
import net.geforcemods.securitycraft.blocks.PanicButtonBlock;
import net.geforcemods.securitycraft.blocks.PortableRadarBlock;
import net.geforcemods.securitycraft.blocks.ProtectoBlock;
import net.geforcemods.securitycraft.blocks.RetinalScannerBlock;
import net.geforcemods.securitycraft.blocks.ScannerDoorBlock;
import net.geforcemods.securitycraft.blocks.SecretStandingSignBlock;
import net.geforcemods.securitycraft.blocks.SecretWallSignBlock;
import net.geforcemods.securitycraft.blocks.SecurityCameraBlock;
import net.geforcemods.securitycraft.blocks.TrophySystemBlock;
import net.geforcemods.securitycraft.blocks.mines.BaseFullMineBlock;
import net.geforcemods.securitycraft.blocks.mines.BouncingBettyBlock;
import net.geforcemods.securitycraft.blocks.mines.ClaymoreBlock;
import net.geforcemods.securitycraft.blocks.mines.FallingBlockMineBlock;
import net.geforcemods.securitycraft.blocks.mines.FurnaceMineBlock;
import net.geforcemods.securitycraft.blocks.mines.IMSBlock;
import net.geforcemods.securitycraft.blocks.mines.MineBlock;
import net.geforcemods.securitycraft.blocks.mines.TrackMineBlock;
import net.geforcemods.securitycraft.blocks.reinforced.BaseReinforcedBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedBookshelfBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedCarpetBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedDoorBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedFallingBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedFenceGateBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedGlassBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedIronTrapDoorBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedPaneBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedPressurePlateBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedRedstoneBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedRotatedCrystalQuartzPillar;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedRotatedPillarBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedSlabBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedStainedGlassBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedStainedGlassPaneBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedStairsBlock;
import net.geforcemods.securitycraft.fluids.FakeLavaFluid;
import net.geforcemods.securitycraft.fluids.FakeWaterFluid;
import net.geforcemods.securitycraft.items.AdminToolItem;
import net.geforcemods.securitycraft.items.BaseKeycardItem;
import net.geforcemods.securitycraft.items.BriefcaseItem;
import net.geforcemods.securitycraft.items.CameraMonitorItem;
import net.geforcemods.securitycraft.items.CodebreakerItem;
import net.geforcemods.securitycraft.items.KeyPanelItem;
import net.geforcemods.securitycraft.items.MineRemoteAccessToolItem;
import net.geforcemods.securitycraft.items.ModuleItem;
import net.geforcemods.securitycraft.items.ReinforcedDoorItem;
import net.geforcemods.securitycraft.items.SCManualItem;
import net.geforcemods.securitycraft.items.ScannerDoorItem;
import net.geforcemods.securitycraft.items.SecretSignItem;
import net.geforcemods.securitycraft.items.SentryItem;
import net.geforcemods.securitycraft.items.SentryRemoteAccessToolItem;
import net.geforcemods.securitycraft.items.TaserItem;
import net.geforcemods.securitycraft.items.UniversalBlockReinforcerItem;
import net.geforcemods.securitycraft.items.UniversalKeyChangerItem;
import net.geforcemods.securitycraft.items.UniversalOwnerChangerItem;
import net.geforcemods.securitycraft.misc.CustomModules;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.block.FlowingFluidBlock;
import net.minecraft.block.PressurePlateBlock.Sensitivity;
import net.minecraft.block.RotatedPillarBlock;
import net.minecraft.block.SlabBlock;
import net.minecraft.block.SoundType;
import net.minecraft.block.WoodType;
import net.minecraft.block.material.Material;
import net.minecraft.item.BucketItem;
import net.minecraft.item.DyeColor;
import net.minecraft.item.Item;
import net.minecraft.util.ResourceLocation;

public class SetupHandler
{
	public static void setupFluids()
	{
		SCContent.flowingFakeWater = new FakeWaterFluid.Flowing();
		SCContent.fakeWater = new FakeWaterFluid.Source();
		SCContent.flowingFakeLava = new FakeLavaFluid.Flowing();
		SCContent.fakeLava = new FakeLavaFluid.Source();
	}

	public static void setupBlocks()
	{
		SCContent.laserBlock = new LaserBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "laser_block"));
		SCContent.laserField = new LaserFieldBlock(Material.ROCK).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "laser"));
		SCContent.keypad = new KeypadBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keypad"));
		SCContent.retinalScanner = new RetinalScannerBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "retinal_scanner"));
		SCContent.reinforcedDoor = new ReinforcedDoorBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "iron_door_reinforced"));
		SCContent.keycardReader = new KeycardReaderBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keycard_reader"));
		SCContent.reinforcedIronTrapdoor = new ReinforcedIronTrapDoorBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "reinforced_iron_trapdoor"));
		SCContent.inventoryScanner = new InventoryScannerBlock(Material.ROCK).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "inventory_scanner"));
		SCContent.inventoryScannerField = new InventoryScannerFieldBlock(Material.GLASS).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "inventory_scanner_field"));
		SCContent.cageTrap = new CageTrapBlock(Material.ROCK).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "cage_trap"));
		SCContent.portableRadar = new PortableRadarBlock(Material.MISCELLANEOUS).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "portable_radar"));
		SCContent.keypadChest = new KeypadChestBlock().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keypad_chest"));
		SCContent.usernameLogger = new LoggerBlock(Material.ROCK).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "username_logger"));
		SCContent.alarm = new AlarmBlock().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "alarm"));
		SCContent.reinforcedFencegate = new ReinforcedFenceGateBlock().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "reinforced_fence_gate"));
		SCContent.panicButton = new PanicButtonBlock().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "panic_button"));
		SCContent.frame = new FrameBlock(Material.ROCK).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keypad_frame"));
		SCContent.keypadFurnace = new KeypadFurnaceBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keypad_furnace"));
		SCContent.securityCamera = new SecurityCameraBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "security_camera"));
		SCContent.ironFence = new IronFenceBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "electrified_iron_fence"));
		SCContent.protecto = new ProtectoBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "protecto"));
		SCContent.scannerDoor = new ScannerDoorBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "scanner_door"));
		SCContent.secretOakSign = new SecretStandingSignBlock(WoodType.field_227038_a_).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_sign_standing"));
		SCContent.secretOakWallSign = new SecretWallSignBlock(WoodType.field_227038_a_).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_sign_wall"));
		SCContent.secretSpruceSign = new SecretStandingSignBlock(WoodType.field_227039_b_).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_spruce_sign_standing"));
		SCContent.secretSpruceWallSign = new SecretWallSignBlock(WoodType.field_227039_b_).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_spruce_sign_wall"));
		SCContent.secretBirchSign = new SecretStandingSignBlock(WoodType.field_227040_c_).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_birch_sign_standing"));
		SCContent.secretBirchWallSign = new SecretWallSignBlock(WoodType.field_227040_c_).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_birch_sign_wall"));
		SCContent.secretJungleSign = new SecretStandingSignBlock(WoodType.field_227042_e_).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_jungle_sign_standing"));
		SCContent.secretJungleWallSign = new SecretWallSignBlock(WoodType.field_227042_e_).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_jungle_sign_wall"));
		SCContent.secretAcaciaSign = new SecretStandingSignBlock(WoodType.field_227041_d_).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_acacia_sign_standing"));
		SCContent.secretAcaciaWallSign = new SecretWallSignBlock(WoodType.field_227041_d_).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_acacia_sign_wall"));
		SCContent.secretDarkOakSign = new SecretStandingSignBlock(WoodType.field_227043_f_).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_dark_oak_sign_standing"));
		SCContent.secretDarkOakWallSign = new SecretWallSignBlock(WoodType.field_227043_f_).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_dark_oak_sign_wall"));
		SCContent.motionActivatedLight = new MotionActivatedLightBlock(Material.GLASS).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "motion_activated_light"));
		SCContent.fakeWaterBlock = (FlowingFluidBlock)new FakeWaterBlock().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "fake_water_block"));
		SCContent.fakeLavaBlock = (FlowingFluidBlock)new FakeLavaBlock().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "fake_lava_block"));
		SCContent.trophySystem = new TrophySystemBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "trophy_system"));
		SCContent.crystalQuartz = new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(0.8F)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "crystal_quartz"));
		SCContent.crystalQuartzPillar = new RotatedPillarBlock(Block.Properties.create(Material.ROCK).hardnessAndResistance(0.8F)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "crystal_quartz_pillar"));
		SCContent.chiseledCrystalQuartz = new Block(Block.Properties.create(Material.ROCK).hardnessAndResistance(0.8F)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "chiseled_crystal_quartz"));
		SCContent.crystalQuartzSlab = new SlabBlock(Block.Properties.create(Material.ROCK).hardnessAndResistance(2.0F, 6.0F)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "crystal_quartz_slab"));
		SCContent.stairsCrystalQuartz = new CustomStairsBlock(SCContent.crystalQuartz.getDefaultState(), Block.Properties.from(SCContent.crystalQuartz)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "crystal_quartz_stairs"));
		SCContent.blockPocketWall = new BlockPocketWallBlock().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "block_pocket_wall"));
		SCContent.blockPocketManager = new BlockPocketManagerBlock().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "block_pocket_manager"));
	}

	public static void setupReinforcedBlocks()
	{
		//ordered by vanilla building blocks creative tab order
		SCContent.reinforcedStone = new BaseReinforcedBlock(Material.ROCK, Blocks.STONE, "reinforced_stone");
		SCContent.reinforcedGranite = new BaseReinforcedBlock(Material.ROCK, Blocks.GRANITE, "reinforced_granite");
		SCContent.reinforcedPolishedGranite = new BaseReinforcedBlock(Material.ROCK, Blocks.POLISHED_GRANITE, "reinforced_polished_granite");
		SCContent.reinforcedDiorite = new BaseReinforcedBlock(Material.ROCK, Blocks.DIORITE, "reinforced_diorite");
		SCContent.reinforcedPolishedDiorite = new BaseReinforcedBlock(Material.ROCK, Blocks.POLISHED_DIORITE, "reinforced_polished_diorite");
		SCContent.reinforcedAndesite = new BaseReinforcedBlock(Material.ROCK, Blocks.ANDESITE, "reinforced_andesite");
		SCContent.reinforcedPolishedAndesite = new BaseReinforcedBlock(Material.ROCK, Blocks.POLISHED_ANDESITE, "reinforced_polished_andesite");
		SCContent.reinforcedDirt = new BaseReinforcedBlock(SoundType.GROUND, Material.EARTH, Blocks.DIRT, "reinforced_dirt");
		SCContent.reinforcedCobblestone = new BaseReinforcedBlock(Material.ROCK, Blocks.COBBLESTONE, "reinforced_cobblestone");
		SCContent.reinforcedOakPlanks = new BaseReinforcedBlock(SoundType.WOOD, Material.WOOD, Blocks.OAK_PLANKS, "reinforced_oak_planks");
		SCContent.reinforcedSprucePlanks = new BaseReinforcedBlock(SoundType.WOOD, Material.WOOD, Blocks.SPRUCE_PLANKS, "reinforced_spruce_planks");
		SCContent.reinforcedBirchPlanks = new BaseReinforcedBlock(SoundType.WOOD, Material.WOOD, Blocks.BIRCH_PLANKS, "reinforced_birch_planks");
		SCContent.reinforcedJunglePlanks = new BaseReinforcedBlock(SoundType.WOOD, Material.WOOD, Blocks.JUNGLE_PLANKS, "reinforced_jungle_planks");
		SCContent.reinforcedAcaciaPlanks = new BaseReinforcedBlock(SoundType.WOOD, Material.WOOD, Blocks.ACACIA_PLANKS, "reinforced_acacia_planks");
		SCContent.reinforcedDarkOakPlanks = new BaseReinforcedBlock(SoundType.WOOD, Material.WOOD, Blocks.DARK_OAK_PLANKS, "reinforced_dark_oak_planks");
		SCContent.reinforcedSand = new ReinforcedFallingBlock(SoundType.SAND, Material.SAND, Blocks.SAND, "reinforced_sand");
		SCContent.reinforcedRedSand = new ReinforcedFallingBlock(SoundType.SAND, Material.SAND, Blocks.RED_SAND, "reinforced_red_sand");
		SCContent.reinforcedGravel = new ReinforcedFallingBlock(SoundType.GROUND, Material.EARTH, Blocks.GRAVEL, "reinforced_gravel");
		SCContent.reinforcedOakLog = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.OAK_LOG, "reinforced_oak_log");
		SCContent.reinforcedSpruceLog = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.SPRUCE_LOG, "reinforced_spruce_log");
		SCContent.reinforcedBirchLog = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.BIRCH_LOG, "reinforced_birch_log");
		SCContent.reinforcedJungleLog = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.JUNGLE_LOG, "reinforced_jungle_log");
		SCContent.reinforcedAcaciaLog = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.ACACIA_LOG, "reinforced_acacia_log");
		SCContent.reinforcedDarkOakLog = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.DARK_OAK_LOG, "reinforced_dark_oak_log");
		SCContent.reinforcedStrippedOakLog = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_OAK_LOG, "reinforced_stripped_oak_log");
		SCContent.reinforcedStrippedSpruceLog = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_SPRUCE_LOG, "reinforced_stripped_spruce_log");
		SCContent.reinforcedStrippedBirchLog = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_BIRCH_LOG, "reinforced_stripped_birch_log");
		SCContent.reinforcedStrippedJungleLog = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_JUNGLE_LOG, "reinforced_stripped_jungle_log");
		SCContent.reinforcedStrippedAcaciaLog = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_ACACIA_LOG, "reinforced_stripped_acacia_log");
		SCContent.reinforcedStrippedDarkOakLog = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_DARK_OAK_LOG, "reinforced_stripped_dark_oak_log");
		SCContent.reinforcedStrippedOakWood = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_OAK_WOOD, "reinforced_stripped_oak_wood");
		SCContent.reinforcedStrippedSpruceWood = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_SPRUCE_WOOD, "reinforced_stripped_spruce_wood");
		SCContent.reinforcedStrippedBirchWood = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_BIRCH_WOOD, "reinforced_stripped_birch_wood");
		SCContent.reinforcedStrippedJungleWood = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_JUNGLE_WOOD, "reinforced_stripped_jungle_wood");
		SCContent.reinforcedStrippedAcaciaWood = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_ACACIA_WOOD, "reinforced_stripped_acacia_wood");
		SCContent.reinforcedStrippedDarkOakWood = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.STRIPPED_DARK_OAK_WOOD, "reinforced_stripped_dark_oak_wood");
		SCContent.reinforcedOakWood = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.OAK_WOOD, "reinforced_oak_wood");
		SCContent.reinforcedSpruceWood = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.SPRUCE_WOOD, "reinforced_spruce_wood");
		SCContent.reinforcedBirchWood = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.BIRCH_WOOD, "reinforced_birch_wood");
		SCContent.reinforcedJungleWood = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.JUNGLE_WOOD, "reinforced_jungle_wood");
		SCContent.reinforcedAcaciaWood = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.ACACIA_WOOD, "reinforced_acacia_wood");
		SCContent.reinforcedDarkOakWood = new ReinforcedRotatedPillarBlock(SoundType.WOOD, Material.WOOD, Blocks.DARK_OAK_WOOD, "reinforced_dark_oak_wood");
		SCContent.reinforcedGlass = new ReinforcedGlassBlock(Blocks.GLASS, "reinforced_glass");
		SCContent.reinforcedLapisBlock = new BaseReinforcedBlock(Material.ROCK, Blocks.LAPIS_BLOCK, "reinforced_lapis_block");
		SCContent.reinforcedSandstone = new BaseReinforcedBlock(Material.ROCK, Blocks.SANDSTONE, "reinforced_sandstone");
		SCContent.reinforcedChiseledSandstone = new BaseReinforcedBlock(Material.ROCK, Blocks.CHISELED_SANDSTONE, "reinforced_chiseled_sandstone");
		SCContent.reinforcedCutSandstone = new BaseReinforcedBlock(Material.ROCK, Blocks.CUT_SANDSTONE, "reinforced_cut_sandstone");
		SCContent.reinforcedWhiteWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.WHITE_WOOL, "reinforced_white_wool");
		SCContent.reinforcedOrangeWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.ORANGE_WOOL, "reinforced_orange_wool");
		SCContent.reinforcedMagentaWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.MAGENTA_WOOL, "reinforced_magenta_wool");
		SCContent.reinforcedLightBlueWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.LIGHT_BLUE_WOOL, "reinforced_light_blue_wool");
		SCContent.reinforcedYellowWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.YELLOW_WOOL, "reinforced_yellow_wool");
		SCContent.reinforcedLimeWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.LIME_WOOL, "reinforced_lime_wool");
		SCContent.reinforcedPinkWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.PINK_WOOL, "reinforced_pink_wool");
		SCContent.reinforcedGrayWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.GRAY_WOOL, "reinforced_gray_wool");
		SCContent.reinforcedLightGrayWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.LIGHT_GRAY_WOOL, "reinforced_light_gray_wool");
		SCContent.reinforcedCyanWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.CYAN_WOOL, "reinforced_cyan_wool");
		SCContent.reinforcedPurpleWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.PURPLE_WOOL, "reinforced_purple_wool");
		SCContent.reinforcedBlueWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.BLUE_WOOL, "reinforced_blue_wool");
		SCContent.reinforcedBrownWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.BROWN_WOOL, "reinforced_brown_wool");
		SCContent.reinforcedGreenWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.GREEN_WOOL, "reinforced_green_wool");
		SCContent.reinforcedRedWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.RED_WOOL, "reinforced_red_wool");
		SCContent.reinforcedBlackWool = new BaseReinforcedBlock(SoundType.CLOTH, Material.WOOL, Blocks.BLACK_WOOL, "reinforced_black_wool");
		SCContent.reinforcedGoldBlock = new BaseReinforcedBlock(SoundType.METAL, Material.IRON, Blocks.GOLD_BLOCK, "reinforced_gold_block");
		SCContent.reinforcedIronBlock = new BaseReinforcedBlock(SoundType.METAL, Material.IRON, Blocks.IRON_BLOCK, "reinforced_iron_block");
		SCContent.reinforcedOakSlab = new ReinforcedSlabBlock(SoundType.WOOD, Material.WOOD, Blocks.OAK_SLAB, "reinforced_oak_slab");
		SCContent.reinforcedSpruceSlab = new ReinforcedSlabBlock(SoundType.WOOD, Material.WOOD, Blocks.SPRUCE_SLAB, "reinforced_spruce_slab");
		SCContent.reinforcedBirchSlab = new ReinforcedSlabBlock(SoundType.WOOD, Material.WOOD, Blocks.BIRCH_SLAB, "reinforced_birch_slab");
		SCContent.reinforcedJungleSlab = new ReinforcedSlabBlock(SoundType.WOOD, Material.WOOD, Blocks.JUNGLE_SLAB, "reinforced_jungle_slab");
		SCContent.reinforcedAcaciaSlab = new ReinforcedSlabBlock(SoundType.WOOD, Material.WOOD, Blocks.ACACIA_SLAB, "reinforced_acacia_slab");
		SCContent.reinforcedDarkOakSlab = new ReinforcedSlabBlock(SoundType.WOOD, Material.WOOD, Blocks.DARK_OAK_SLAB, "reinforced_dark_oak_slab");
		SCContent.reinforcedNormalStoneSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.STONE_SLAB, "reinforced_normal_stone_slab");
		SCContent.reinforcedSmoothStoneSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.SMOOTH_STONE_SLAB, "reinforced_stone_slab");
		SCContent.reinforcedSandstoneSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.SANDSTONE_SLAB, "reinforced_sandstone_slab");
		SCContent.reinforcedCobblestoneSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.COBBLESTONE_SLAB, "reinforced_cobblestone_slab");
		SCContent.reinforcedBrickSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.BRICK_SLAB, "reinforced_brick_slab");
		SCContent.reinforcedStoneBrickSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.STONE_BRICK_SLAB, "reinforced_stone_brick_slab");
		SCContent.reinforcedNetherBrickSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.NETHER_BRICK_SLAB, "reinforced_nether_brick_slab");
		SCContent.reinforcedQuartzSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.QUARTZ_SLAB, "reinforced_quartz_slab");
		SCContent.reinforcedRedSandstoneSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.RED_SANDSTONE_SLAB, "reinforced_red_sandstone_slab");
		SCContent.reinforcedPurpurSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.PURPUR_SLAB, "reinforced_purpur_slab");
		SCContent.reinforcedPrismarineSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.PRISMARINE_SLAB, "reinforced_prismarine_slab");
		SCContent.reinforcedPrismarineBrickSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.PRISMARINE_BRICK_SLAB, "reinforced_prismarine_brick_slab");
		SCContent.reinforcedDarkPrismarineSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.DARK_PRISMARINE_SLAB, "reinforced_dark_prismarine_slab");
		SCContent.reinforcedSmoothQuartz = new BaseReinforcedBlock(Material.ROCK, Blocks.SMOOTH_QUARTZ, "reinforced_smooth_quartz");
		SCContent.reinforcedSmoothRedSandstone = new BaseReinforcedBlock(Material.ROCK, Blocks.SMOOTH_RED_SANDSTONE, "reinforced_smooth_red_sandstone");
		SCContent.reinforcedSmoothSandstone = new BaseReinforcedBlock(Material.ROCK, Blocks.SMOOTH_SANDSTONE, "reinforced_smooth_sandstone");
		SCContent.reinforcedSmoothStone = new BaseReinforcedBlock(Material.ROCK, Blocks.SMOOTH_STONE, "reinforced_smooth_stone");
		SCContent.reinforcedBricks = new BaseReinforcedBlock(Material.ROCK, Blocks.BRICKS, "reinforced_bricks");
		SCContent.reinforcedBookshelf = new ReinforcedBookshelfBlock(SoundType.WOOD, Material.WOOD, Blocks.BOOKSHELF, "reinforced_bookshelf");
		SCContent.reinforcedMossyCobblestone = new BaseReinforcedBlock(Material.ROCK, Blocks.MOSSY_COBBLESTONE, "reinforced_mossy_cobblestone");
		SCContent.reinforcedObsidian = new BaseReinforcedBlock(Material.ROCK, Blocks.OBSIDIAN, "reinforced_obsidian");
		SCContent.reinforcedPurpurBlock = new BaseReinforcedBlock(Material.ROCK, Blocks.PURPUR_BLOCK, "reinforced_purpur_block");
		SCContent.reinforcedPurpurPillar = new ReinforcedRotatedPillarBlock(Material.ROCK, Blocks.PURPUR_PILLAR, "reinforced_purpur_pillar");
		SCContent.reinforcedPurpurStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.PURPUR_STAIRS, "reinforced_purpur_stairs");
		SCContent.reinforcedOakStairs = new ReinforcedStairsBlock(SoundType.WOOD, Material.WOOD, Blocks.OAK_STAIRS, "reinforced_oak_stairs");
		SCContent.reinforcedDiamondBlock = new BaseReinforcedBlock(SoundType.METAL, Material.IRON, Blocks.DIAMOND_BLOCK, "reinforced_diamond_block");
		SCContent.reinforcedCobblestoneStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.COBBLESTONE_STAIRS, "reinforced_cobblestone_stairs");
		SCContent.reinforcedNetherrack = new BaseReinforcedBlock(Material.ROCK, Blocks.NETHERRACK, "reinforced_netherrack");
		SCContent.reinforcedGlowstone = new BaseReinforcedBlock(SoundType.GLASS, Material.GLASS, Blocks.GLOWSTONE, "reinforced_glowstone", 15);
		SCContent.reinforcedStoneBricks = new BaseReinforcedBlock(Material.ROCK, Blocks.STONE_BRICKS, "reinforced_stone_bricks");
		SCContent.reinforcedMossyStoneBricks = new BaseReinforcedBlock(Material.ROCK, Blocks.MOSSY_STONE_BRICKS, "reinforced_mossy_stone_bricks");
		SCContent.reinforcedCrackedStoneBricks = new BaseReinforcedBlock(Material.ROCK, Blocks.CRACKED_STONE_BRICKS, "reinforced_cracked_stone_bricks");
		SCContent.reinforcedChiseledStoneBricks = new BaseReinforcedBlock(Material.ROCK, Blocks.CHISELED_STONE_BRICKS, "reinforced_chiseled_stone_bricks");
		SCContent.reinforcedBrickStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.BRICK_STAIRS, "reinforced_brick_stairs");
		SCContent.reinforcedStoneBrickStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.STONE_BRICK_STAIRS, "reinforced_stone_brick_stairs");
		SCContent.reinforcedNetherBricks = new BaseReinforcedBlock(Material.ROCK, Blocks.NETHER_BRICKS, "reinforced_nether_bricks");
		SCContent.reinforcedNetherBrickStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.NETHER_BRICK_STAIRS, "reinforced_nether_brick_stairs");
		SCContent.reinforcedEndStone = new BaseReinforcedBlock(Material.ROCK, Blocks.END_STONE, "reinforced_end_stone");
		SCContent.reinforcedEndStoneBricks = new BaseReinforcedBlock(Material.ROCK, Blocks.END_STONE_BRICKS, "reinforced_end_stone_bricks");
		SCContent.reinforcedSandstoneStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.SANDSTONE_STAIRS, "reinforced_sandstone_stairs");
		SCContent.reinforcedEmeraldBlock = new BaseReinforcedBlock(SoundType.METAL, Material.IRON, Blocks.EMERALD_BLOCK, "reinforced_emerald_block");
		SCContent.reinforcedSpruceStairs = new ReinforcedStairsBlock(SoundType.WOOD, Material.WOOD, Blocks.SPRUCE_STAIRS, "reinforced_spruce_stairs");
		SCContent.reinforcedBirchStairs = new ReinforcedStairsBlock(SoundType.WOOD, Material.WOOD, Blocks.BIRCH_STAIRS, "reinforced_birch_stairs");
		SCContent.reinforcedJungleStairs = new ReinforcedStairsBlock(SoundType.WOOD, Material.WOOD, Blocks.JUNGLE_STAIRS, "reinforced_jungle_stairs");
		SCContent.reinforcedChiseledQuartz = new BaseReinforcedBlock(Material.ROCK, Blocks.CHISELED_QUARTZ_BLOCK, "reinforced_chiseled_quartz_block");
		SCContent.reinforcedQuartz = new BaseReinforcedBlock(Material.ROCK, Blocks.QUARTZ_BLOCK, "reinforced_quartz_block");
		SCContent.reinforcedQuartzPillar = new ReinforcedRotatedPillarBlock(Material.ROCK, Blocks.QUARTZ_PILLAR, "reinforced_quartz_pillar");
		SCContent.reinforcedQuartzStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.QUARTZ_STAIRS, "reinforced_quartz_stairs");
		SCContent.reinforcedWhiteTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.WHITE_TERRACOTTA, "reinforced_white_terracotta");
		SCContent.reinforcedOrangeTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.ORANGE_TERRACOTTA, "reinforced_orange_terracotta");
		SCContent.reinforcedMagentaTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.MAGENTA_TERRACOTTA, "reinforced_magenta_terracotta");
		SCContent.reinforcedLightBlueTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.LIGHT_BLUE_TERRACOTTA, "reinforced_light_blue_terracotta");
		SCContent.reinforcedYellowTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.YELLOW_TERRACOTTA, "reinforced_yellow_terracotta");
		SCContent.reinforcedLimeTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.LIME_TERRACOTTA, "reinforced_lime_terracotta");
		SCContent.reinforcedPinkTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.PINK_TERRACOTTA, "reinforced_pink_terracotta");
		SCContent.reinforcedGrayTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.GRAY_TERRACOTTA, "reinforced_gray_terracotta");
		SCContent.reinforcedLightGrayTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.LIGHT_GRAY_TERRACOTTA, "reinforced_light_gray_terracotta");
		SCContent.reinforcedCyanTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.CYAN_TERRACOTTA, "reinforced_cyan_terracotta");
		SCContent.reinforcedPurpleTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.PURPLE_TERRACOTTA, "reinforced_purple_terracotta");
		SCContent.reinforcedBlueTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.BLUE_TERRACOTTA, "reinforced_blue_terracotta");
		SCContent.reinforcedBrownTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.BROWN_TERRACOTTA, "reinforced_brown_terracotta");
		SCContent.reinforcedGreenTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.GREEN_TERRACOTTA, "reinforced_green_terracotta");
		SCContent.reinforcedRedTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.RED_TERRACOTTA, "reinforced_red_terracotta");
		SCContent.reinforcedBlackTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.BLACK_TERRACOTTA, "reinforced_black_terracotta");
		SCContent.reinforcedTerracotta = new BaseReinforcedBlock(Material.ROCK, Blocks.TERRACOTTA, "reinforced_hardened_clay");
		SCContent.reinforcedCoalBlock = new BaseReinforcedBlock(Material.ROCK, Blocks.COAL_BLOCK, "reinforced_coal_block");
		SCContent.reinforcedAcaciaStairs = new ReinforcedStairsBlock(SoundType.WOOD, Material.WOOD, Blocks.ACACIA_STAIRS, "reinforced_acacia_stairs");
		SCContent.reinforcedDarkOakStairs = new ReinforcedStairsBlock(SoundType.WOOD, Material.WOOD, Blocks.DARK_OAK_STAIRS, "reinforced_dark_oak_stairs");
		SCContent.reinforcedWhiteStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.WHITE, Blocks.WHITE_STAINED_GLASS, "reinforced_white_stained_glass");
		SCContent.reinforcedOrangeStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.ORANGE, Blocks.ORANGE_STAINED_GLASS, "reinforced_orange_stained_glass");
		SCContent.reinforcedMagentaStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.MAGENTA, Blocks.MAGENTA_STAINED_GLASS, "reinforced_magenta_stained_glass");
		SCContent.reinforcedLightBlueStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_STAINED_GLASS, "reinforced_light_blue_stained_glass");
		SCContent.reinforcedYellowStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.YELLOW, Blocks.YELLOW_STAINED_GLASS, "reinforced_yellow_stained_glass");
		SCContent.reinforcedLimeStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.LIME, Blocks.LIME_STAINED_GLASS, "reinforced_lime_stained_glass");
		SCContent.reinforcedPinkStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.PINK, Blocks.PINK_STAINED_GLASS, "reinforced_pink_stained_glass");
		SCContent.reinforcedGrayStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.GRAY, Blocks.GRAY_STAINED_GLASS, "reinforced_gray_stained_glass");
		SCContent.reinforcedLightGrayStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_STAINED_GLASS, "reinforced_light_gray_stained_glass");
		SCContent.reinforcedCyanStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.CYAN, Blocks.CYAN_STAINED_GLASS, "reinforced_cyan_stained_glass");
		SCContent.reinforcedPurpleStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.PURPLE, Blocks.PURPLE_STAINED_GLASS, "reinforced_purple_stained_glass");
		SCContent.reinforcedBlueStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.BLUE, Blocks.BLUE_STAINED_GLASS, "reinforced_blue_stained_glass");
		SCContent.reinforcedBrownStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.BROWN, Blocks.BROWN_STAINED_GLASS, "reinforced_brown_stained_glass");
		SCContent.reinforcedGreenStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.GREEN, Blocks.GREEN_STAINED_GLASS, "reinforced_green_stained_glass");
		SCContent.reinforcedRedStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.RED, Blocks.RED_STAINED_GLASS, "reinforced_red_stained_glass");
		SCContent.reinforcedBlackStainedGlass = new ReinforcedStainedGlassBlock(DyeColor.BLACK, Blocks.BLACK_STAINED_GLASS, "reinforced_black_stained_glass");
		SCContent.reinforcedPrismarine = new BaseReinforcedBlock(Material.ROCK, Blocks.PRISMARINE, "reinforced_prismarine");
		SCContent.reinforcedPrismarineBricks = new BaseReinforcedBlock(Material.ROCK, Blocks.PRISMARINE_BRICKS, "reinforced_prismarine_bricks");
		SCContent.reinforcedDarkPrismarine = new BaseReinforcedBlock(Material.ROCK, Blocks.DARK_PRISMARINE, "reinforced_dark_prismarine");
		SCContent.reinforcedPrismarineStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.PRISMARINE_STAIRS, "reinforced_prismarine_stairs");
		SCContent.reinforcedPrismarineBrickStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.PRISMARINE_BRICK_STAIRS, "reinforced_prismarine_brick_stairs");
		SCContent.reinforcedDarkPrismarineStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.DARK_PRISMARINE_STAIRS, "reinforced_dark_prismarine_stairs");
		SCContent.reinforcedSeaLantern = new BaseReinforcedBlock(Material.GLASS, Blocks.SEA_LANTERN, "reinforced_sea_lantern", 15);
		SCContent.reinforcedRedSandstone = new BaseReinforcedBlock(Material.ROCK, Blocks.SANDSTONE, "reinforced_red_sandstone");
		SCContent.reinforcedChiseledRedSandstone = new BaseReinforcedBlock(Material.ROCK, Blocks.CHISELED_SANDSTONE, "reinforced_chiseled_red_sandstone");
		SCContent.reinforcedCutRedSandstone = new BaseReinforcedBlock(Material.ROCK, Blocks.CUT_SANDSTONE, "reinforced_cut_red_sandstone");
		SCContent.reinforcedRedSandstoneStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.RED_SANDSTONE_STAIRS, "reinforced_red_sandstone_stairs");
		SCContent.reinforcedRedNetherBricks = new BaseReinforcedBlock(Material.ROCK, Blocks.RED_NETHER_BRICKS, "reinforced_red_nether_bricks");
		SCContent.reinforcedBoneBlock = new ReinforcedRotatedPillarBlock(Material.ROCK, Blocks.BONE_BLOCK, "reinforced_bone_block");
		SCContent.reinforcedWhiteConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.WHITE_CONCRETE, "reinforced_white_concrete");
		SCContent.reinforcedOrangeConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.ORANGE_CONCRETE, "reinforced_orange_concrete");
		SCContent.reinforcedMagentaConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.MAGENTA_CONCRETE, "reinforced_magenta_concrete");
		SCContent.reinforcedLightBlueConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.LIGHT_BLUE_CONCRETE, "reinforced_light_blue_concrete");
		SCContent.reinforcedYellowConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.YELLOW_CONCRETE, "reinforced_yellow_concrete");
		SCContent.reinforcedLimeConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.LIME_CONCRETE, "reinforced_lime_concrete");
		SCContent.reinforcedPinkConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.PINK_CONCRETE, "reinforced_pink_concrete");
		SCContent.reinforcedGrayConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.GRAY_CONCRETE, "reinforced_gray_concrete");
		SCContent.reinforcedLightGrayConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.LIGHT_GRAY_CONCRETE, "reinforced_light_gray_concrete");
		SCContent.reinforcedCyanConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.CYAN_CONCRETE, "reinforced_cyan_concrete");
		SCContent.reinforcedPurpleConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.PURPLE_CONCRETE, "reinforced_purple_concrete");
		SCContent.reinforcedBlueConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.BLUE_CONCRETE, "reinforced_blue_concrete");
		SCContent.reinforcedBrownConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.BROWN_CONCRETE, "reinforced_brown_concrete");
		SCContent.reinforcedGreenConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.GREEN_CONCRETE, "reinforced_green_concrete");
		SCContent.reinforcedRedConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.RED_CONCRETE, "reinforced_red_concrete");
		SCContent.reinforcedBlackConcrete = new BaseReinforcedBlock(Material.ROCK, Blocks.BLACK_CONCRETE, "reinforced_black_concrete");
		SCContent.reinforcedPolishedGraniteStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.POLISHED_GRANITE_STAIRS, "reinforced_polished_granite_stairs");
		SCContent.reinforcedSmoothRedSandstoneStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.SMOOTH_RED_SANDSTONE_STAIRS, "reinforced_smooth_red_sandstone_stairs");
		SCContent.reinforcedMossyStoneBrickStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.MOSSY_STONE_BRICK_STAIRS, "reinforced_mossy_stone_brick_stairs");
		SCContent.reinforcedPolishedDioriteStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.POLISHED_DIORITE_STAIRS, "reinforced_polished_diorite_stairs");
		SCContent.reinforcedMossyCobblestoneStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.MOSSY_COBBLESTONE_STAIRS, "reinforced_mossy_cobblestone_stairs");
		SCContent.reinforcedEndStoneBrickStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.END_STONE_BRICK_STAIRS, "reinforced_end_stone_brick_stairs");
		SCContent.reinforcedStoneStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.STONE_STAIRS, "reinforced_stone_stairs");
		SCContent.reinforcedSmoothSandstoneStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.SMOOTH_SANDSTONE_STAIRS, "reinforced_smooth_sandstone_stairs");
		SCContent.reinforcedSmoothQuartzStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.SMOOTH_QUARTZ_STAIRS, "reinforced_smooth_quartz_stairs");
		SCContent.reinforcedGraniteStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.GRANITE_STAIRS, "reinforced_granite_stairs");
		SCContent.reinforcedAndesiteStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.ANDESITE_STAIRS, "reinforced_andesite_stairs");
		SCContent.reinforcedRedNetherBrickStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.RED_NETHER_BRICK_STAIRS, "reinforced_red_nether_brick_stairs");
		SCContent.reinforcedPolishedAndesiteStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.POLISHED_ANDESITE_STAIRS, "reinforced_polished_andesite_stairs");
		SCContent.reinforcedDioriteStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, Blocks.DIORITE_STAIRS, "reinforced_diorite_stairs");
		SCContent.reinforcedPolishedGraniteSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.POLISHED_GRANITE_SLAB, "reinforced_polished_granite_slab");
		SCContent.reinforcedSmoothRedSandstoneSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.SMOOTH_RED_SANDSTONE_SLAB, "reinforced_smooth_red_sandstone_slab");
		SCContent.reinforcedMossyStoneBrickSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.MOSSY_STONE_BRICK_SLAB, "reinforced_mossy_stone_brick_slab");
		SCContent.reinforcedPolishedDioriteSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.POLISHED_DIORITE_SLAB, "reinforced_polished_diorite_slab");
		SCContent.reinforcedMossyCobblestoneSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.MOSSY_COBBLESTONE_SLAB, "reinforced_mossy_cobblestone_slab");
		SCContent.reinforcedEndStoneBrickSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.END_STONE_BRICK_SLAB, "reinforced_end_stone_brick_slab");
		SCContent.reinforcedSmoothSandstoneSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.SMOOTH_SANDSTONE_SLAB, "reinforced_smooth_sandstone_slab");
		SCContent.reinforcedSmoothQuartzSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.SMOOTH_QUARTZ_SLAB, "reinforced_smooth_quartz_slab");
		SCContent.reinforcedGraniteSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.GRANITE_SLAB, "reinforced_granite_slab");
		SCContent.reinforcedAndesiteSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.ANDESITE_SLAB, "reinforced_andesite_slab");
		SCContent.reinforcedRedNetherBrickSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.RED_NETHER_BRICK_SLAB, "reinforced_red_nether_brick_slab");
		SCContent.reinforcedPolishedAndesiteSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.POLISHED_ANDESITE_SLAB, "reinforced_polished_andesite_slab");
		SCContent.reinforcedDioriteSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, Blocks.DIORITE_SLAB, "reinforced_diorite_slab");
		//ordered by vanilla decoration blocks creative tab order
		SCContent.reinforcedIronBars = new ReinforcedPaneBlock(SoundType.METAL, Material.IRON, Blocks.IRON_BARS, "reinforced_iron_bars");
		SCContent.reinforcedGlassPane = new ReinforcedPaneBlock(SoundType.GLASS, Material.GLASS, Blocks.GLASS_PANE, "reinforced_glass_pane");
		SCContent.reinforcedWhiteCarpet = new ReinforcedCarpetBlock(Blocks.WHITE_CARPET, "reinforced_white_carpet");
		SCContent.reinforcedOrangeCarpet = new ReinforcedCarpetBlock(Blocks.ORANGE_CARPET, "reinforced_orange_carpet");
		SCContent.reinforcedMagentaCarpet = new ReinforcedCarpetBlock(Blocks.MAGENTA_CARPET, "reinforced_magenta_carpet");
		SCContent.reinforcedLightBlueCarpet = new ReinforcedCarpetBlock(Blocks.LIGHT_BLUE_CARPET, "reinforced_light_blue_carpet");
		SCContent.reinforcedYellowCarpet = new ReinforcedCarpetBlock(Blocks.YELLOW_CARPET, "reinforced_yellow_carpet");
		SCContent.reinforcedLimeCarpet = new ReinforcedCarpetBlock(Blocks.LIME_CARPET, "reinforced_lime_carpet");
		SCContent.reinforcedPinkCarpet = new ReinforcedCarpetBlock(Blocks.PINK_CARPET, "reinforced_pink_carpet");
		SCContent.reinforcedGrayCarpet = new ReinforcedCarpetBlock(Blocks.GRAY_CARPET, "reinforced_gray_carpet");
		SCContent.reinforcedLightGrayCarpet = new ReinforcedCarpetBlock(Blocks.LIGHT_GRAY_CARPET, "reinforced_light_gray_carpet");
		SCContent.reinforcedCyanCarpet = new ReinforcedCarpetBlock(Blocks.CYAN_CARPET, "reinforced_cyan_carpet");
		SCContent.reinforcedPurpleCarpet = new ReinforcedCarpetBlock(Blocks.PURPLE_CARPET, "reinforced_purple_carpet");
		SCContent.reinforcedBlueCarpet = new ReinforcedCarpetBlock(Blocks.BLUE_CARPET, "reinforced_blue_carpet");
		SCContent.reinforcedBrownCarpet = new ReinforcedCarpetBlock(Blocks.BROWN_CARPET, "reinforced_brown_carpet");
		SCContent.reinforcedGreenCarpet = new ReinforcedCarpetBlock(Blocks.GREEN_CARPET, "reinforced_green_carpet");
		SCContent.reinforcedRedCarpet = new ReinforcedCarpetBlock(Blocks.RED_CARPET, "reinforced_red_carpet");
		SCContent.reinforcedBlackCarpet = new ReinforcedCarpetBlock(Blocks.BLACK_CARPET, "reinforced_black_carpet");
		SCContent.reinforcedWhiteStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.WHITE, Blocks.WHITE_STAINED_GLASS_PANE, "reinforced_white_stained_glass_pane");
		SCContent.reinforcedOrangeStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.ORANGE, Blocks.ORANGE_STAINED_GLASS_PANE, "reinforced_orange_stained_glass_pane");
		SCContent.reinforcedMagentaStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.MAGENTA, Blocks.MAGENTA_STAINED_GLASS_PANE, "reinforced_magenta_stained_glass_pane");
		SCContent.reinforcedLightBlueStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.LIGHT_BLUE, Blocks.LIGHT_BLUE_STAINED_GLASS_PANE, "reinforced_light_blue_stained_glass_pane");
		SCContent.reinforcedYellowStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.YELLOW, Blocks.YELLOW_STAINED_GLASS_PANE, "reinforced_yellow_stained_glass_pane");
		SCContent.reinforcedLimeStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.LIME, Blocks.LIME_STAINED_GLASS_PANE, "reinforced_lime_stained_glass_pane");
		SCContent.reinforcedPinkStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.PINK, Blocks.PINK_STAINED_GLASS_PANE, "reinforced_pink_stained_glass_pane");
		SCContent.reinforcedGrayStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.GRAY, Blocks.GRAY_STAINED_GLASS_PANE, "reinforced_gray_stained_glass_pane");
		SCContent.reinforcedLightGrayStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.LIGHT_GRAY, Blocks.LIGHT_GRAY_STAINED_GLASS_PANE, "reinforced_light_gray_stained_glass_pane");
		SCContent.reinforcedCyanStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.CYAN, Blocks.CYAN_STAINED_GLASS_PANE, "reinforced_cyan_stained_glass_pane");
		SCContent.reinforcedPurpleStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.PURPLE, Blocks.PURPLE_STAINED_GLASS_PANE, "reinforced_purple_stained_glass_pane");
		SCContent.reinforcedBlueStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.BLUE, Blocks.BLUE_STAINED_GLASS_PANE, "reinforced_blue_stained_glass_pane");
		SCContent.reinforcedBrownStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.BROWN, Blocks.BROWN_STAINED_GLASS_PANE, "reinforced_brown_stained_glass_pane");
		SCContent.reinforcedGreenStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.GREEN, Blocks.GREEN_STAINED_GLASS_PANE, "reinforced_green_stained_glass_pane");
		SCContent.reinforcedRedStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.RED, Blocks.RED_STAINED_GLASS_PANE, "reinforced_red_stained_glass_pane");
		SCContent.reinforcedBlackStainedGlassPane = new ReinforcedStainedGlassPaneBlock(DyeColor.BLACK, Blocks.BLACK_STAINED_GLASS_PANE, "reinforced_black_stained_glass_pane");
		//anything else, alphabetical
		SCContent.reinforcedChiseledCrystalQuartz = new BlockPocketBlock(Material.ROCK, SCContent.chiseledCrystalQuartz, "reinforced_chiseled_crystal_quartz_block");
		SCContent.reinforcedCrystalQuartz = new BlockPocketBlock(Material.ROCK, SCContent.crystalQuartz, "reinforced_crystal_quartz_block");
		SCContent.reinforcedCrystalQuartzPillar = new ReinforcedRotatedCrystalQuartzPillar(Material.ROCK, SCContent.crystalQuartzPillar, "reinforced_crystal_quartz_pillar");
		SCContent.reinforcedCrystalQuartzSlab = new ReinforcedSlabBlock(SoundType.STONE, Material.ROCK, SCContent.crystalQuartzSlab, "reinforced_crystal_quartz_slab");
		SCContent.reinforcedCrystalQuartzStairs = new ReinforcedStairsBlock(SoundType.STONE, Material.ROCK, SCContent.stairsCrystalQuartz, "reinforced_crystal_quartz_stairs");
		SCContent.reinforcedStonePressurePlate = new ReinforcedPressurePlateBlock(Sensitivity.MOBS, ReinforcedPressurePlateBlock.STONE_PROPERTIES, Blocks.STONE_PRESSURE_PLATE).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "reinforced_stone_pressure_plate"));
		SCContent.reinforcedOakPressurePlate = new ReinforcedPressurePlateBlock(Sensitivity.EVERYTHING, ReinforcedPressurePlateBlock.WOOD_PROPERTIES, Blocks.OAK_PRESSURE_PLATE).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "reinforced_oak_pressure_plate"));
		SCContent.reinforcedSprucePressurePlate = new ReinforcedPressurePlateBlock(Sensitivity.EVERYTHING, ReinforcedPressurePlateBlock.WOOD_PROPERTIES, Blocks.SPRUCE_PRESSURE_PLATE).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "reinforced_spruce_pressure_plate"));
		SCContent.reinforcedBirchPressurePlate = new ReinforcedPressurePlateBlock(Sensitivity.EVERYTHING, ReinforcedPressurePlateBlock.WOOD_PROPERTIES, Blocks.BIRCH_PRESSURE_PLATE).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "reinforced_birch_pressure_plate"));
		SCContent.reinforcedJunglePressurePlate = new ReinforcedPressurePlateBlock(Sensitivity.EVERYTHING, ReinforcedPressurePlateBlock.WOOD_PROPERTIES, Blocks.JUNGLE_PRESSURE_PLATE).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "reinforced_jungle_pressure_plate"));
		SCContent.reinforcedAcaciaPressurePlate = new ReinforcedPressurePlateBlock(Sensitivity.EVERYTHING, ReinforcedPressurePlateBlock.WOOD_PROPERTIES, Blocks.ACACIA_PRESSURE_PLATE).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "reinforced_acacia_pressure_plate"));
		SCContent.reinforcedDarkOakPressurePlate = new ReinforcedPressurePlateBlock(Sensitivity.EVERYTHING, ReinforcedPressurePlateBlock.WOOD_PROPERTIES, Blocks.DARK_OAK_PRESSURE_PLATE).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "reinforced_dark_oak_pressure_plate"));
		SCContent.reinforcedRedstoneBlock = new ReinforcedRedstoneBlock();
	}

	public static void setupMines()
	{
		SCContent.mine = (MineBlock) new MineBlock(Material.MISCELLANEOUS, 1F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "mine"));
		SCContent.dirtMine = new BaseFullMineBlock(Material.EARTH, SoundType.GROUND, Blocks.DIRT, 1.25F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "dirt_mine"));
		SCContent.stoneMine = new BaseFullMineBlock(Material.ROCK, SoundType.STONE, Blocks.STONE, 2.5F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "stone_mine"));
		SCContent.cobblestoneMine = new BaseFullMineBlock(Material.ROCK, SoundType.STONE, Blocks.COBBLESTONE, 2.75F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "cobblestone_mine"));
		SCContent.sandMine = new FallingBlockMineBlock(Material.SAND, SoundType.SAND, Blocks.SAND, 1.25F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "sand_mine"));
		SCContent.diamondOreMine = new BaseFullMineBlock(Material.ROCK, SoundType.STONE, Blocks.DIAMOND_ORE, 3.75F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "diamond_mine"));
		SCContent.furnaceMine = new FurnaceMineBlock(Material.ROCK, 3.75F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "furnace_mine"));
		SCContent.gravelMine = new FallingBlockMineBlock(Material.EARTH, SoundType.GROUND, Blocks.GRAVEL, 1.25F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "gravel_mine"));
		SCContent.trackMine = new TrackMineBlock().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "track_mine"));
		SCContent.bouncingBetty = new BouncingBettyBlock(Material.MISCELLANEOUS, 1F).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "bouncing_betty"));
		SCContent.claymore = new ClaymoreBlock(Material.MISCELLANEOUS).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "claymore"));
		SCContent.ims = new IMSBlock(Material.IRON).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "ims"));
	}

	public static void setupItems()
	{
		SCContent.codebreaker = new CodebreakerItem().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "codebreaker"));
		SCContent.keycardLvl1 = new BaseKeycardItem(0).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keycard_lv1"));
		SCContent.keycardLvl2 = new BaseKeycardItem(1).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keycard_lv2"));
		SCContent.keycardLvl3 = new BaseKeycardItem(2).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keycard_lv3"));
		SCContent.keycardLvl4 = new BaseKeycardItem(4).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keycard_lv4"));
		SCContent.keycardLvl5 = new BaseKeycardItem(5).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keycard_lv5"));
		SCContent.limitedUseKeycard = new BaseKeycardItem(3).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "limited_use_keycard"));
		SCContent.reinforcedDoorItem = new ReinforcedDoorItem().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "door_indestructible_iron_item"));
		SCContent.universalBlockRemover = new Item(new Item.Properties().maxStackSize(1).defaultMaxDamage(476).group(SecurityCraft.groupSCTechnical)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_block_remover"));
		SCContent.remoteAccessMine = new MineRemoteAccessToolItem().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "remote_access_mine"));
		SCContent.remoteAccessSentry = new SentryRemoteAccessToolItem().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "remote_access_sentry"));
		SCContent.fWaterBucket = new BucketItem(SCContent.fakeWater, new Item.Properties().group(SecurityCraft.groupSCTechnical).maxStackSize(1)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "bucket_f_water"));
		SCContent.fLavaBucket = new BucketItem(SCContent.fakeLava, new Item.Properties().group(SecurityCraft.groupSCTechnical).maxStackSize(1)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "bucket_f_lava"));
		SCContent.universalBlockModifier = new Item(new Item.Properties().maxStackSize(1).group(SecurityCraft.groupSCTechnical)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_block_modifier"));
		SCContent.redstoneModule = (ModuleItem) new ModuleItem(CustomModules.REDSTONE, false).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "redstone_module"));
		SCContent.whitelistModule = (ModuleItem) new ModuleItem(CustomModules.WHITELIST, true, true).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "whitelist_module"));
		SCContent.blacklistModule = (ModuleItem) new ModuleItem(CustomModules.BLACKLIST, true, true).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "blacklist_module"));
		SCContent.harmingModule = (ModuleItem) new ModuleItem(CustomModules.HARMING, false).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "harming_module"));
		SCContent.smartModule = (ModuleItem) new ModuleItem(CustomModules.SMART, false).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "smart_module"));
		SCContent.storageModule = (ModuleItem) new ModuleItem(CustomModules.STORAGE, false).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "storage_module"));
		SCContent.disguiseModule = (ModuleItem) new ModuleItem(CustomModules.DISGUISE, false, true, 0, 1).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "disguise_module"));
		SCContent.wireCutters = new Item(new Item.Properties().maxStackSize(1).defaultMaxDamage(476).group(SecurityCraft.groupSCTechnical)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "wire_cutters"));
		SCContent.keyPanel = new KeyPanelItem().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "keypad_item"));
		SCContent.adminTool = new AdminToolItem().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "admin_tool"));
		SCContent.cameraMonitor = new CameraMonitorItem().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "camera_monitor"));
		SCContent.scManual = new SCManualItem().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "sc_manual"));
		SCContent.taser = new TaserItem(false).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "taser"));
		SCContent.taserPowered = new TaserItem(true).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "taser_powered"));
		SCContent.universalOwnerChanger = new UniversalOwnerChangerItem().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_owner_changer"));
		SCContent.universalBlockReinforcerLvL1 = new UniversalBlockReinforcerItem(300).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_block_reinforcer_lvl1"));
		SCContent.universalBlockReinforcerLvL2 = new UniversalBlockReinforcerItem(2700).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_block_reinforcer_lvl2"));
		SCContent.universalBlockReinforcerLvL3 = new UniversalBlockReinforcerItem(0).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_block_reinforcer_lvl3"));
		SCContent.briefcase = new BriefcaseItem().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "briefcase"));
		SCContent.universalKeyChanger = new UniversalKeyChangerItem().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "universal_key_changer"));
		SCContent.scannerDoorItem = new ScannerDoorItem().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "scanner_door_item"));
		SCContent.secretOakSignItem = new SecretSignItem(SCContent.secretOakSign, SCContent.secretOakWallSign, "item.securitycraft.secret_sign_item").setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_sign_item"));
		SCContent.secretSpruceSignItem = new SecretSignItem(SCContent.secretSpruceSign, SCContent.secretSpruceWallSign, "item.securitycraft.secret_spruce_sign_item").setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_spruce_sign_item"));
		SCContent.secretBirchSignItem = new SecretSignItem(SCContent.secretBirchSign, SCContent.secretBirchWallSign, "item.securitycraft.secret_birch_sign_item").setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_birch_sign_item"));
		SCContent.secretJungleSignItem = new SecretSignItem(SCContent.secretJungleSign, SCContent.secretJungleWallSign, "item.securitycraft.secret_jungle_sign_item").setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_jungle_sign_item"));
		SCContent.secretAcaciaSignItem = new SecretSignItem(SCContent.secretAcaciaSign, SCContent.secretAcaciaWallSign, "item.securitycraft.secret_acacia_sign_item").setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_acacia_sign_item"));
		SCContent.secretDarkOakSignItem = new SecretSignItem(SCContent.secretDarkOakSign, SCContent.secretDarkOakWallSign, "item.securitycraft.secret_dark_oak_sign_item").setRegistryName(new ResourceLocation(SecurityCraft.MODID, "secret_dark_oak_sign_item"));
		SCContent.sentry = new SentryItem().setRegistryName(new ResourceLocation(SecurityCraft.MODID, "sentry"));
		SCContent.crystalQuartzItem = new Item(new Item.Properties().group(SecurityCraft.groupSCDecoration)).setRegistryName(new ResourceLocation(SecurityCraft.MODID, "crystal_quartz_item"));
	}
}
