package net.geforcemods.securitycraft.datagen;

import java.util.Arrays;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.stream.Stream;

import com.google.common.collect.ImmutableList;
import com.google.common.collect.ImmutableList.Builder;

import net.geforcemods.securitycraft.SCContent;
import net.geforcemods.securitycraft.SCTags;
import net.geforcemods.securitycraft.SecurityCraft;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedSlabBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedStairsBlock;
import net.geforcemods.securitycraft.blocks.reinforced.ReinforcedWallBlock;
import net.minecraft.core.HolderLookup;
import net.minecraft.data.PackOutput;
import net.minecraft.data.tags.TagAppender;
import net.minecraft.resources.ResourceKey;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.ColorCollection;
import net.minecraft.world.level.block.WeatheringCopperCollection;
import net.neoforged.neoforge.common.Tags;
import net.neoforged.neoforge.common.data.BlockTagsProvider;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredHolder;

public class BlockTagGenerator extends BlockTagsProvider {
	public BlockTagGenerator(PackOutput output, CompletableFuture<HolderLookup.Provider> lookupProvider) {
		super(output, lookupProvider, SecurityCraft.MODID);
	}

	@Override
	@SuppressWarnings("unchecked")
	protected void addTags(HolderLookup.Provider provider) {
		//@formatter:off
		List<ResourceKey<Block>> woodenSlabs = Arrays.asList(
				SCContent.REINFORCED_OAK_SLAB.getKey(),
				SCContent.REINFORCED_SPRUCE_SLAB.getKey(),
				SCContent.REINFORCED_BIRCH_SLAB.getKey(),
				SCContent.REINFORCED_JUNGLE_SLAB.getKey(),
				SCContent.REINFORCED_ACACIA_SLAB.getKey(),
				SCContent.REINFORCED_DARK_OAK_SLAB.getKey(),
				SCContent.REINFORCED_MANGROVE_SLAB.getKey(),
				SCContent.REINFORCED_CHERRY_SLAB.getKey(),
				SCContent.REINFORCED_PALE_OAK_SLAB.getKey(),
				SCContent.REINFORCED_BAMBOO_SLAB.getKey(),
				SCContent.REINFORCED_BAMBOO_MOSAIC_SLAB.getKey(),
				SCContent.REINFORCED_CRIMSON_SLAB.getKey(),
				SCContent.REINFORCED_WARPED_SLAB.getKey());
		List<ResourceKey<Block>> woodenStairs = Arrays.asList(
				SCContent.REINFORCED_OAK_STAIRS.getKey(),
				SCContent.REINFORCED_SPRUCE_STAIRS.getKey(),
				SCContent.REINFORCED_BIRCH_STAIRS.getKey(),
				SCContent.REINFORCED_JUNGLE_STAIRS.getKey(),
				SCContent.REINFORCED_ACACIA_STAIRS.getKey(),
				SCContent.REINFORCED_DARK_OAK_STAIRS.getKey(),
				SCContent.REINFORCED_MANGROVE_STAIRS.getKey(),
				SCContent.REINFORCED_CHERRY_STAIRS.getKey(),
				SCContent.REINFORCED_PALE_OAK_STAIRS.getKey(),
				SCContent.REINFORCED_BAMBOO_STAIRS.getKey(),
				SCContent.REINFORCED_BAMBOO_MOSAIC_STAIRS.getKey(),
				SCContent.REINFORCED_CRIMSON_STAIRS.getKey(),
				SCContent.REINFORCED_WARPED_STAIRS.getKey());

		//securitycraft tags
		tag(SCTags.Blocks.ALL_SECRET_SIGNS).addTag(SCTags.Blocks.SECRET_HANGING_SIGNS).addTag(SCTags.Blocks.SECRET_SIGNS);
		tag(SCTags.Blocks.REINFORCED_ACACIA_LOGS).add(
				SCContent.REINFORCED_ACACIA_LOG.getKey(),
				SCContent.REINFORCED_ACACIA_WOOD.getKey(),
				SCContent.REINFORCED_STRIPPED_ACACIA_LOG.getKey(),
				SCContent.REINFORCED_STRIPPED_ACACIA_WOOD.getKey());
		tag(SCTags.Blocks.REINFORCED_BAMBOO_BLOCKS).add(
				SCContent.REINFORCED_BAMBOO_BLOCK.getKey(),
				SCContent.REINFORCED_STRIPPED_BAMBOO_BLOCK.getKey());
		tag(SCTags.Blocks.REINFORCED_BARS)
				.add(SCContent.REINFORCED_IRON_BARS.getKey())
				.addAll(keysFromCollection(SCContent.REINFORCED_COPPER_BARS));
		tag(SCTags.Blocks.REINFORCED_BIRCH_LOGS).add(
				SCContent.REINFORCED_BIRCH_LOG.getKey(),
				SCContent.REINFORCED_BIRCH_WOOD.getKey(),
				SCContent.REINFORCED_STRIPPED_BIRCH_LOG.getKey(),
				SCContent.REINFORCED_STRIPPED_BIRCH_WOOD.getKey());
		tag(SCTags.Blocks.REINFORCED_BUTTONS).addTag(SCTags.Blocks.REINFORCED_WOODEN_BUTTONS).add(
				SCContent.REINFORCED_STONE_BUTTON.getKey(),
				SCContent.REINFORCED_POLISHED_BLACKSTONE_BUTTON.getKey());
		tag(SCTags.Blocks.REINFORCED_CAULDRONS).add(
				SCContent.REINFORCED_CAULDRON.getKey(),
				SCContent.REINFORCED_LAVA_CAULDRON.getKey(),
				SCContent.REINFORCED_POWDER_SNOW_CAULDRON.getKey(),
				SCContent.REINFORCED_WATER_CAULDRON.getKey());
		tag(SCTags.Blocks.REINFORCED_CHERRY_LOGS).add(
				SCContent.REINFORCED_CHERRY_LOG.getKey(),
				SCContent.REINFORCED_CHERRY_WOOD.getKey(),
				SCContent.REINFORCED_STRIPPED_CHERRY_LOG.getKey(),
				SCContent.REINFORCED_STRIPPED_CHERRY_WOOD.getKey());
		tag(SCTags.Blocks.REINFORCED_COBBLESTONE).add(
				SCContent.REINFORCED_COBBLESTONE.getKey(),
				SCContent.REINFORCED_MOSSY_COBBLESTONE.getKey());
		tag(SCTags.Blocks.REINFORCED_CONCRETE).addAll(keysFromCollection(SCContent.REINFORCED_CONCRETE));
		tag(SCTags.Blocks.REINFORCED_CRIMSON_STEMS).add(
				SCContent.REINFORCED_CRIMSON_STEM.getKey(),
				SCContent.REINFORCED_CRIMSON_HYPHAE.getKey(),
				SCContent.REINFORCED_STRIPPED_CRIMSON_STEM.getKey(),
				SCContent.REINFORCED_STRIPPED_CRIMSON_HYPHAE.getKey());
		tag(SCTags.Blocks.REINFORCED_DARK_OAK_LOGS).add(
				SCContent.REINFORCED_DARK_OAK_LOG.getKey(),
				SCContent.REINFORCED_DARK_OAK_WOOD.getKey(),
				SCContent.REINFORCED_STRIPPED_DARK_OAK_LOG.getKey(),
				SCContent.REINFORCED_STRIPPED_DARK_OAK_WOOD.getKey());
		tag(SCTags.Blocks.REINFORCED_DIRT).add(
				SCContent.REINFORCED_DIRT.getKey(),
				SCContent.REINFORCED_COARSE_DIRT.getKey(),
				SCContent.REINFORCED_ROOTED_DIRT.getKey());
		tag(SCTags.Blocks.REINFORCED_END_STONES).add(
				SCContent.REINFORCED_END_STONE.getKey());
		tag(SCTags.Blocks.REINFORCED_FENCES).addTag(SCTags.Blocks.REINFORCED_WOODEN_FENCES).add(
				SCContent.REINFORCED_NETHER_BRICK_FENCE.getKey());
		tag(SCTags.Blocks.REINFORCED_GLASS_PANES)
				.add(SCContent.REINFORCED_GLASS_PANE.getKey())
				.addAll(keysFromCollection(SCContent.REINFORCED_STAINED_GLASS_PANE));
		tag(SCTags.Blocks.REINFORCED_GLAZED_TERRACOTTA).addAll(keysFromCollection(SCContent.REINFORCED_GLAZED_TERRACOTTA));
		tag(SCTags.Blocks.REINFORCED_GRASS_BLOCKS).add(
				SCContent.REINFORCED_GRASS_BLOCK.getKey(),
				SCContent.REINFORCED_PODZOL.getKey(),
				SCContent.REINFORCED_MYCELIUM.getKey());
		tag(SCTags.Blocks.REINFORCED_ICE).add(
				SCContent.REINFORCED_ICE.getKey(),
				SCContent.REINFORCED_PACKED_ICE.getKey(),
				SCContent.REINFORCED_BLUE_ICE.getKey());
		tag(SCTags.Blocks.REINFORCED_JUNGLE_LOGS).add(
				SCContent.REINFORCED_JUNGLE_LOG.getKey(),
				SCContent.REINFORCED_JUNGLE_WOOD.getKey(),
				SCContent.REINFORCED_STRIPPED_JUNGLE_LOG.getKey(),
				SCContent.REINFORCED_STRIPPED_JUNGLE_WOOD.getKey());
		tag(SCTags.Blocks.REINFORCED_LOGS)
				.addTag(SCTags.Blocks.REINFORCED_ACACIA_LOGS)
				.addTag(SCTags.Blocks.REINFORCED_BIRCH_LOGS)
				.addTag(SCTags.Blocks.REINFORCED_CHERRY_LOGS)
				.addTag(SCTags.Blocks.REINFORCED_CRIMSON_STEMS)
				.addTag(SCTags.Blocks.REINFORCED_DARK_OAK_LOGS)
				.addTag(SCTags.Blocks.REINFORCED_JUNGLE_LOGS)
				.addTag(SCTags.Blocks.REINFORCED_MANGROVE_LOGS)
				.addTag(SCTags.Blocks.REINFORCED_OAK_LOGS)
				.addTag(SCTags.Blocks.REINFORCED_PALE_OAK_LOGS)
				.addTag(SCTags.Blocks.REINFORCED_SPRUCE_LOGS)
				.addTag(SCTags.Blocks.REINFORCED_WARPED_STEMS);
		tag(SCTags.Blocks.REINFORCED_MANGROVE_LOGS).add(
				SCContent.REINFORCED_MANGROVE_LOG.getKey(),
				SCContent.REINFORCED_MANGROVE_WOOD.getKey(),
				SCContent.REINFORCED_STRIPPED_MANGROVE_LOG.getKey(),
				SCContent.REINFORCED_STRIPPED_MANGROVE_WOOD.getKey());
		tag(SCTags.Blocks.REINFORCED_MOSS_BLOCKS).add(SCContent.REINFORCED_MOSS_BLOCK.getKey(), SCContent.REINFORCED_PALE_MOSS_BLOCK.getKey());
		tag(SCTags.Blocks.REINFORCED_MUD).add(SCContent.REINFORCED_MUD.getKey());
		tag(SCTags.Blocks.REINFORCED_NYLIUM).add(
				SCContent.REINFORCED_CRIMSON_NYLIUM.getKey(),
				SCContent.REINFORCED_WARPED_NYLIUM.getKey());
		tag(SCTags.Blocks.REINFORCED_OAK_LOGS).add(
				SCContent.REINFORCED_OAK_LOG.getKey(),
				SCContent.REINFORCED_OAK_WOOD.getKey(),
				SCContent.REINFORCED_STRIPPED_OAK_LOG.getKey(),
				SCContent.REINFORCED_STRIPPED_OAK_WOOD.getKey());
		tag(SCTags.Blocks.REINFORCED_PALE_OAK_LOGS).add(
				SCContent.REINFORCED_PALE_OAK_LOG.getKey(),
				SCContent.REINFORCED_PALE_OAK_WOOD.getKey(),
				SCContent.REINFORCED_STRIPPED_PALE_OAK_LOG.getKey(),
				SCContent.REINFORCED_STRIPPED_PALE_OAK_WOOD.getKey());
		tag(SCTags.Blocks.REINFORCED_PLANKS).add(
				SCContent.REINFORCED_ACACIA_PLANKS.getKey(),
				SCContent.REINFORCED_BAMBOO_PLANKS.getKey(),
				SCContent.REINFORCED_BIRCH_PLANKS.getKey(),
				SCContent.REINFORCED_CHERRY_PLANKS.getKey(),
				SCContent.REINFORCED_CRIMSON_PLANKS.getKey(),
				SCContent.REINFORCED_DARK_OAK_PLANKS.getKey(),
				SCContent.REINFORCED_JUNGLE_PLANKS.getKey(),
				SCContent.REINFORCED_MANGROVE_PLANKS.getKey(),
				SCContent.REINFORCED_OAK_PLANKS.getKey(),
				SCContent.REINFORCED_PALE_OAK_PLANKS.getKey(),
				SCContent.REINFORCED_SPRUCE_PLANKS.getKey(),
				SCContent.REINFORCED_WARPED_PLANKS.getKey());
		tag(SCTags.Blocks.REINFORCED_PRESSURE_PLATES).addTag(SCTags.Blocks.REINFORCED_WOODEN_PRESSURE_PLATES).addTag(SCTags.Blocks.REINFORCED_STONE_PRESSURE_PLATES);
		tag(SCTags.Blocks.REINFORCED_SAND).add(
				SCContent.REINFORCED_RED_SAND.getKey(),
				SCContent.REINFORCED_SAND.getKey(),
				SCContent.SUSPICIOUS_SAND_MINE.getKey());
		tag(SCTags.Blocks.REINFORCED_SLABS).addTag(SCTags.Blocks.REINFORCED_WOODEN_SLABS);
		tag(SCTags.Blocks.REINFORCED_SPRUCE_LOGS).add(
				SCContent.REINFORCED_SPRUCE_LOG.getKey(),
				SCContent.REINFORCED_SPRUCE_WOOD.getKey(),
				SCContent.REINFORCED_STRIPPED_SPRUCE_LOG.getKey(),
				SCContent.REINFORCED_STRIPPED_SPRUCE_WOOD.getKey());
		tag(SCTags.Blocks.REINFORCED_STAIRS).addTag(SCTags.Blocks.REINFORCED_WOODEN_STAIRS);
		tag(SCTags.Blocks.REINFORCED_STONE).add(
				SCContent.REINFORCED_ANDESITE.getKey(),
				SCContent.REINFORCED_DIORITE.getKey(),
				SCContent.REINFORCED_GRANITE.getKey(),
				SCContent.REINFORCED_STONE.getKey(),
				SCContent.REINFORCED_POLISHED_ANDESITE.getKey(),
				SCContent.REINFORCED_POLISHED_DIORITE.getKey(),
				SCContent.REINFORCED_POLISHED_GRANITE.getKey());
		tag(SCTags.Blocks.REINFORCED_STONE_BRICKS).add(
				SCContent.REINFORCED_STONE_BRICKS.getKey(),
				SCContent.REINFORCED_MOSSY_STONE_BRICKS.getKey(),
				SCContent.REINFORCED_CRACKED_STONE_BRICKS.getKey(),
				SCContent.REINFORCED_CHISELED_STONE_BRICKS.getKey());
		tag(SCTags.Blocks.REINFORCED_STONE_PRESSURE_PLATES).add(
				SCContent.REINFORCED_STONE_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_POLISHED_BLACKSTONE_PRESSURE_PLATE.getKey());
		tag(SCTags.Blocks.REINFORCED_TERRACOTTA).addAll(keysFromCollection(SCContent.REINFORCED_DYED_TERRACOTTA));
		tag(SCTags.Blocks.REINFORCED_WARPED_STEMS).add(
				SCContent.REINFORCED_WARPED_STEM.getKey(),
				SCContent.REINFORCED_WARPED_HYPHAE.getKey(),
				SCContent.REINFORCED_STRIPPED_WARPED_STEM.getKey(),
				SCContent.REINFORCED_STRIPPED_WARPED_HYPHAE.getKey());
		tag(SCTags.Blocks.REINFORCED_WOODEN_BUTTONS).add(
				SCContent.REINFORCED_OAK_BUTTON.getKey(),
				SCContent.REINFORCED_SPRUCE_BUTTON.getKey(),
				SCContent.REINFORCED_BIRCH_BUTTON.getKey(),
				SCContent.REINFORCED_JUNGLE_BUTTON.getKey(),
				SCContent.REINFORCED_ACACIA_BUTTON.getKey(),
				SCContent.REINFORCED_DARK_OAK_BUTTON.getKey(),
				SCContent.REINFORCED_MANGROVE_BUTTON.getKey(),
				SCContent.REINFORCED_CHERRY_BUTTON.getKey(),
				SCContent.REINFORCED_PALE_OAK_BUTTON.getKey(),
				SCContent.REINFORCED_BAMBOO_BUTTON.getKey(),
				SCContent.REINFORCED_CRIMSON_BUTTON.getKey(),
				SCContent.REINFORCED_WARPED_BUTTON.getKey());
		tag(SCTags.Blocks.REINFORCED_WOODEN_FENCES).add(
				SCContent.REINFORCED_OAK_FENCE.getKey(),
				SCContent.REINFORCED_SPRUCE_FENCE.getKey(),
				SCContent.REINFORCED_BIRCH_FENCE.getKey(),
				SCContent.REINFORCED_JUNGLE_FENCE.getKey(),
				SCContent.REINFORCED_ACACIA_FENCE.getKey(),
				SCContent.REINFORCED_DARK_OAK_FENCE.getKey(),
				SCContent.REINFORCED_MANGROVE_FENCE.getKey(),
				SCContent.REINFORCED_CHERRY_FENCE.getKey(),
				SCContent.REINFORCED_PALE_OAK_FENCE.getKey(),
				SCContent.REINFORCED_BAMBOO_FENCE.getKey(),
				SCContent.REINFORCED_CRIMSON_FENCE.getKey(),
				SCContent.REINFORCED_WARPED_FENCE.getKey());
		tag(SCTags.Blocks.REINFORCED_WOODEN_FENCE_GATES).add(
				SCContent.REINFORCED_OAK_FENCE_GATE.getKey(),
				SCContent.REINFORCED_SPRUCE_FENCE_GATE.getKey(),
				SCContent.REINFORCED_BIRCH_FENCE_GATE.getKey(),
				SCContent.REINFORCED_JUNGLE_FENCE_GATE.getKey(),
				SCContent.REINFORCED_ACACIA_FENCE_GATE.getKey(),
				SCContent.REINFORCED_DARK_OAK_FENCE_GATE.getKey(),
				SCContent.REINFORCED_MANGROVE_FENCE_GATE.getKey(),
				SCContent.REINFORCED_CHERRY_FENCE_GATE.getKey(),
				SCContent.REINFORCED_PALE_OAK_FENCE_GATE.getKey(),
				SCContent.REINFORCED_BAMBOO_FENCE_GATE.getKey(),
				SCContent.REINFORCED_CRIMSON_FENCE_GATE.getKey(),
				SCContent.REINFORCED_WARPED_FENCE_GATE.getKey());
		tag(SCTags.Blocks.REINFORCED_WOODEN_PRESSURE_PLATES).add(
				SCContent.REINFORCED_OAK_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_SPRUCE_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_BIRCH_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_JUNGLE_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_ACACIA_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_DARK_OAK_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_MANGROVE_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_CHERRY_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_PALE_OAK_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_BAMBOO_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_CRIMSON_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_WARPED_PRESSURE_PLATE.getKey());
		tag(SCTags.Blocks.REINFORCED_WOODEN_SHELVES).add(
				SCContent.REINFORCED_OAK_SHELF.getKey(),
				SCContent.REINFORCED_SPRUCE_SHELF.getKey(),
				SCContent.REINFORCED_BIRCH_SHELF.getKey(),
				SCContent.REINFORCED_JUNGLE_SHELF.getKey(),
				SCContent.REINFORCED_ACACIA_SHELF.getKey(),
				SCContent.REINFORCED_DARK_OAK_SHELF.getKey(),
				SCContent.REINFORCED_MANGROVE_SHELF.getKey(),
				SCContent.REINFORCED_CHERRY_SHELF.getKey(),
				SCContent.REINFORCED_PALE_OAK_SHELF.getKey(),
				SCContent.REINFORCED_BAMBOO_SHELF.getKey(),
				SCContent.REINFORCED_CRIMSON_SHELF.getKey(),
				SCContent.REINFORCED_WARPED_SHELF.getKey());
		tag(SCTags.Blocks.REINFORCED_WOODEN_SLABS).add(woodenSlabs.toArray(new ResourceKey[0]));
		tag(SCTags.Blocks.REINFORCED_WOODEN_STAIRS).add(woodenStairs.toArray(new ResourceKey[0]));
		tag(SCTags.Blocks.REINFORCED_WOOL).addAll(keysFromCollection(SCContent.REINFORCED_WOOL));
		tag(SCTags.Blocks.REINFORCED_WOOL_CARPETS).addAll(keysFromCollection(SCContent.REINFORCED_CARPET));
		tag(SCTags.Blocks.SECRET_HANGING_SIGNS).addTag(SCTags.Blocks.SECRET_CEILING_HANGING_SIGNS).addTag(SCTags.Blocks.SECRET_WALL_HANGING_SIGNS);
		tag(SCTags.Blocks.SECRET_SIGNS).addTag(SCTags.Blocks.SECRET_STANDING_SIGNS).addTag(SCTags.Blocks.SECRET_WALL_SIGNS);
		tag(SCTags.Blocks.SECRET_CEILING_HANGING_SIGNS).add(
				SCContent.SECRET_ACACIA_HANGING_SIGN.getKey(),
				SCContent.SECRET_BAMBOO_HANGING_SIGN.getKey(),
				SCContent.SECRET_BIRCH_HANGING_SIGN.getKey(),
				SCContent.SECRET_CHERRY_HANGING_SIGN.getKey(),
				SCContent.SECRET_CRIMSON_HANGING_SIGN.getKey(),
				SCContent.SECRET_DARK_OAK_HANGING_SIGN.getKey(),
				SCContent.SECRET_JUNGLE_HANGING_SIGN.getKey(),
				SCContent.SECRET_MANGROVE_HANGING_SIGN.getKey(),
				SCContent.SECRET_OAK_HANGING_SIGN.getKey(),
				SCContent.SECRET_PALE_OAK_HANGING_SIGN.getKey(),
				SCContent.SECRET_SPRUCE_HANGING_SIGN.getKey(),
				SCContent.SECRET_WARPED_HANGING_SIGN.getKey());
		tag(SCTags.Blocks.SECRET_STANDING_SIGNS).add(
				SCContent.SECRET_ACACIA_SIGN.getKey(),
				SCContent.SECRET_BAMBOO_SIGN.getKey(),
				SCContent.SECRET_BIRCH_SIGN.getKey(),
				SCContent.SECRET_CHERRY_SIGN.getKey(),
				SCContent.SECRET_CRIMSON_SIGN.getKey(),
				SCContent.SECRET_DARK_OAK_SIGN.getKey(),
				SCContent.SECRET_JUNGLE_SIGN.getKey(),
				SCContent.SECRET_MANGROVE_SIGN.getKey(),
				SCContent.SECRET_OAK_SIGN.getKey(),
				SCContent.SECRET_PALE_OAK_SIGN.getKey(),
				SCContent.SECRET_SPRUCE_SIGN.getKey(),
				SCContent.SECRET_WARPED_SIGN.getKey());
		tag(SCTags.Blocks.SECRET_WALL_HANGING_SIGNS).add(
				SCContent.SECRET_ACACIA_WALL_HANGING_SIGN.getKey(),
				SCContent.SECRET_BAMBOO_WALL_HANGING_SIGN.getKey(),
				SCContent.SECRET_BIRCH_WALL_HANGING_SIGN.getKey(),
				SCContent.SECRET_CHERRY_WALL_HANGING_SIGN.getKey(),
				SCContent.SECRET_CRIMSON_WALL_HANGING_SIGN.getKey(),
				SCContent.SECRET_DARK_OAK_WALL_HANGING_SIGN.getKey(),
				SCContent.SECRET_JUNGLE_WALL_HANGING_SIGN.getKey(),
				SCContent.SECRET_MANGROVE_WALL_HANGING_SIGN.getKey(),
				SCContent.SECRET_OAK_WALL_HANGING_SIGN.getKey(),
				SCContent.SECRET_PALE_OAK_WALL_HANGING_SIGN.getKey(),
				SCContent.SECRET_SPRUCE_WALL_HANGING_SIGN.getKey(),
				SCContent.SECRET_WARPED_WALL_HANGING_SIGN.getKey());
		tag(SCTags.Blocks.SECRET_WALL_SIGNS).add(
				SCContent.SECRET_ACACIA_WALL_SIGN.getKey(),
				SCContent.SECRET_BAMBOO_WALL_SIGN.getKey(),
				SCContent.SECRET_BIRCH_WALL_SIGN.getKey(),
				SCContent.SECRET_CHERRY_WALL_SIGN.getKey(),
				SCContent.SECRET_CRIMSON_WALL_SIGN.getKey(),
				SCContent.SECRET_DARK_OAK_WALL_SIGN.getKey(),
				SCContent.SECRET_JUNGLE_WALL_SIGN.getKey(),
				SCContent.SECRET_MANGROVE_WALL_SIGN.getKey(),
				SCContent.SECRET_OAK_WALL_SIGN.getKey(),
				SCContent.SECRET_PALE_OAK_WALL_SIGN.getKey(),
				SCContent.SECRET_SPRUCE_WALL_SIGN.getKey(),
				SCContent.SECRET_WARPED_WALL_SIGN.getKey());
		tag(SCTags.Blocks.SUSPICIOUS_MINES).add(SCContent.SUSPICIOUS_GRAVEL_MINE.getKey(), SCContent.SUSPICIOUS_SAND_MINE.getKey());

		//minecraft tags
		tag(BlockTags.ALL_SIGNS).addTag(SCTags.Blocks.ALL_SECRET_SIGNS);
		tag(BlockTags.BARS).addTag(SCTags.Blocks.REINFORCED_BARS);
		tag(BlockTags.BEACON_BASE_BLOCKS).add(
				SCContent.REINFORCED_DIAMOND_BLOCK.getKey(),
				SCContent.REINFORCED_EMERALD_BLOCK.getKey(),
				SCContent.REINFORCED_GOLD_BLOCK.getKey(),
				SCContent.REINFORCED_IRON_BLOCK.getKey(),
				SCContent.REINFORCED_NETHERITE_BLOCK.getKey());
		tag(BlockTags.BUTTONS).addTag(SCTags.Blocks.REINFORCED_BUTTONS);
		tag(BlockTags.CAMEL_SAND_STEP_SOUND_BLOCKS).addTag(SCTags.Blocks.REINFORCED_SAND);
		tag(BlockTags.CAULDRONS).add(
				SCContent.REINFORCED_CAULDRON.getKey(),
				SCContent.REINFORCED_LAVA_CAULDRON.getKey(),
				SCContent.REINFORCED_WATER_CAULDRON.getKey(),
				SCContent.REINFORCED_POWDER_SNOW_CAULDRON.getKey());
		tag(BlockTags.CEILING_HANGING_SIGNS).addTag(SCTags.Blocks.SECRET_CEILING_HANGING_SIGNS);
		tag(BlockTags.CLIMBABLE).add(
				SCContent.REINFORCED_LADDER.getKey(),
				SCContent.REINFORCED_SCAFFOLDING.getKey());
		tag(BlockTags.CRYSTAL_SOUND_BLOCKS).add(SCContent.REINFORCED_AMETHYST_BLOCK.getKey());
		tag(BlockTags.DAMPENS_VIBRATIONS).addTag(SCTags.Blocks.REINFORCED_WOOL);
		tag(BlockTags.DOORS).add(SCContent.KEYPAD_DOOR.getKey(), SCContent.REINFORCED_DOOR.getKey(), SCContent.SCANNER_DOOR.getKey());
		tag(BlockTags.ENCHANTMENT_POWER_PROVIDER).add(SCContent.REINFORCED_BOOKSHELF.getKey());
		tag(BlockTags.FALL_DAMAGE_RESETTING).add(SCContent.REINFORCED_LADDER.getKey());
		tag(BlockTags.FENCE_GATES).addTag(SCTags.Blocks.REINFORCED_WOODEN_FENCE_GATES).add(
				SCContent.ELECTRIFIED_IRON_FENCE_GATE.getKey());
		tag(BlockTags.FENCES).add(
				SCContent.ELECTRIFIED_IRON_FENCE.getKey(),
				SCContent.REINFORCED_NETHER_BRICK_FENCE.getKey());
		tag(BlockTags.FOREST_ROCK_CAN_PLACE_ON)
				.addTag(SCTags.Blocks.REINFORCED_DIRT)
				.addTag(SCTags.Blocks.REINFORCED_MUD)
				.addTag(SCTags.Blocks.REINFORCED_MOSS_BLOCKS)
				.addTag(SCTags.Blocks.REINFORCED_GRASS_BLOCKS)
				.add(SCContent.REINFORCED_STONE.getKey(),
						SCContent.REINFORCED_GRANITE.getKey(),
						SCContent.REINFORCED_DIORITE.getKey(),
						SCContent.REINFORCED_ANDESITE.getKey(),
						SCContent.REINFORCED_TUFF.getKey(),
						SCContent.REINFORCED_DEEPSLATE.getKey());
		tag(BlockTags.GUARDED_BY_PIGLINS).add(
				SCContent.DEEPSLATE_GOLD_ORE_MINE.getKey(),
				SCContent.GILDED_BLACKSTONE_MINE.getKey(),
				SCContent.GOLD_ORE_MINE.getKey(),
				SCContent.NETHER_GOLD_ORE_MINE.getKey(),
				SCContent.REINFORCED_GOLD_BLOCK.getKey(),
				SCContent.REINFORCED_RAW_GOLD_BLOCK.getKey());
		tag(BlockTags.HUGE_BROWN_MUSHROOM_CAN_PLACE_ON)
				.addTag(SCTags.Blocks.REINFORCED_DIRT)
				.addTag(SCTags.Blocks.REINFORCED_MUD)
				.addTag(SCTags.Blocks.REINFORCED_MOSS_BLOCKS)
				.addTag(SCTags.Blocks.REINFORCED_GRASS_BLOCKS)
				.add(SCContent.REINFORCED_MYCELIUM.getKey(),
						SCContent.REINFORCED_PODZOL.getKey(),
						SCContent.REINFORCED_CRIMSON_NYLIUM.getKey(),
						SCContent.REINFORCED_WARPED_NYLIUM.getKey());
		tag(BlockTags.HUGE_RED_MUSHROOM_CAN_PLACE_ON)
				.addTag(SCTags.Blocks.REINFORCED_DIRT)
				.addTag(SCTags.Blocks.REINFORCED_MUD)
				.addTag(SCTags.Blocks.REINFORCED_MOSS_BLOCKS)
				.addTag(SCTags.Blocks.REINFORCED_GRASS_BLOCKS)
				.add(SCContent.REINFORCED_MYCELIUM.getKey(),
						SCContent.REINFORCED_PODZOL.getKey(),
						SCContent.REINFORCED_CRIMSON_NYLIUM.getKey(),
						SCContent.REINFORCED_WARPED_NYLIUM.getKey());
		tag(BlockTags.IMPERMEABLE)
				.add(SCContent.REINFORCED_GLASS.getKey(), SCContent.REINFORCED_TINTED_GLASS.getKey())
				.addAll(keysFromCollection(SCContent.REINFORCED_STAINED_GLASS));
		tag(BlockTags.INFINIBURN_OVERWORLD).add(SCContent.REINFORCED_NETHERRACK.getKey(), SCContent.REINFORCED_MAGMA_BLOCK.getKey());
		tag(BlockTags.NEEDS_DIAMOND_TOOL).add(SCContent.ANCIENT_DEBRIS_MINE.getKey());
		tag(BlockTags.NEEDS_IRON_TOOL).add(
				SCContent.GOLD_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_GOLD_ORE_MINE.getKey(),
				SCContent.REDSTONE_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_REDSTONE_ORE_MINE.getKey(),
				SCContent.EMERALD_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_EMERALD_ORE_MINE.getKey(),
				SCContent.DIAMOND_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_DIAMOND_ORE_MINE.getKey());
		tag(BlockTags.NEEDS_STONE_TOOL).add(
				SCContent.IRON_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_IRON_ORE_MINE.getKey(),
				SCContent.COPPER_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_COPPER_ORE_MINE.getKey(),
				SCContent.LAPIS_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_LAPIS_ORE_MINE.getKey());
		tag(BlockTags.NYLIUM).addTag(SCTags.Blocks.REINFORCED_NYLIUM);
		tag(BlockTags.OCCLUDES_VIBRATION_SIGNALS).addTag(SCTags.Blocks.REINFORCED_WOOL);
		tag(BlockTags.PIGLIN_REPELLENTS).add(SCContent.REINFORCED_SOUL_LANTERN.getKey());
		tag(BlockTags.TRIGGERS_AMBIENT_DESERT_SAND_BLOCK_SOUNDS).add(SCContent.REINFORCED_SAND.getKey(), SCContent.REINFORCED_RED_SAND.getKey());
		tag(BlockTags.TRIGGERS_AMBIENT_DESERT_DRY_VEGETATION_BLOCK_SOUNDS).addTag(SCTags.Blocks.REINFORCED_TERRACOTTA).add(SCContent.REINFORCED_SAND.getKey(), SCContent.REINFORCED_RED_SAND.getKey());
		tag(BlockTags.PRESSURE_PLATES).addTag(SCTags.Blocks.REINFORCED_PRESSURE_PLATES);
		tag(BlockTags.RAILS).add(SCContent.TRACK_MINE.getKey());
		tag(BlockTags.SHEARS_EXTREME_BREAKING_SPEED).add(SCContent.REINFORCED_COBWEB.getKey());
		tag(BlockTags.SLABS).addTag(SCTags.Blocks.REINFORCED_SLABS).add(SCContent.CRYSTAL_QUARTZ_SLAB.getKey(), SCContent.SMOOTH_CRYSTAL_QUARTZ_SLAB.getKey());
		tag(BlockTags.SIGNS).addTag(SCTags.Blocks.SECRET_SIGNS);
		tag(BlockTags.SNAPS_GOAT_HORN).add(
				SCContent.REINFORCED_ACACIA_LOG.getKey(),
				SCContent.REINFORCED_BIRCH_LOG.getKey(),
				SCContent.REINFORCED_OAK_LOG.getKey(),
				SCContent.REINFORCED_JUNGLE_LOG.getKey(),
				SCContent.REINFORCED_SPRUCE_LOG.getKey(),
				SCContent.REINFORCED_DARK_OAK_LOG.getKey(),
				SCContent.REINFORCED_MANGROVE_LOG.getKey(),
				SCContent.REINFORCED_CHERRY_LOG.getKey(),
				SCContent.REINFORCED_PALE_OAK_LOG.getKey(),
				SCContent.REINFORCED_STONE.getKey(),
				SCContent.REINFORCED_PACKED_ICE.getKey(),
				SCContent.IRON_ORE_MINE.getKey(),
				SCContent.COAL_ORE_MINE.getKey(),
				SCContent.COPPER_ORE_MINE.getKey(),
				SCContent.EMERALD_ORE_MINE.getKey());
		tag(BlockTags.SNIFFER_DIGGABLE_BLOCK)
				.addTag(SCTags.Blocks.REINFORCED_DIRT)
				.addTag(SCTags.Blocks.REINFORCED_MUD)
				.addTag(SCTags.Blocks.REINFORCED_MOSS_BLOCKS)
				.add(SCContent.REINFORCED_GRASS_BLOCK.getKey(), SCContent.REINFORCED_PODZOL.getKey());
		tag(BlockTags.SNIFFER_EGG_HATCH_BOOST).add(SCContent.REINFORCED_MOSS_BLOCK.getKey());
		tag(BlockTags.SNOW).add(SCContent.REINFORCED_SNOW_BLOCK.getKey());
		tag(BlockTags.SOUL_FIRE_BASE_BLOCKS).add(SCContent.REINFORCED_SOUL_SAND.getKey(), SCContent.REINFORCED_SOUL_SOIL.getKey());
		tag(BlockTags.SOUL_SPEED_BLOCKS).add(SCContent.REINFORCED_SOUL_SAND.getKey(), SCContent.REINFORCED_SOUL_SOIL.getKey());
		tag(BlockTags.STAIRS).addTag(SCTags.Blocks.REINFORCED_STAIRS).add(SCContent.CRYSTAL_QUARTZ_STAIRS.getKey(), SCContent.SMOOTH_CRYSTAL_QUARTZ_STAIRS.getKey());
		tag(BlockTags.STONE_BUTTONS).add(
				SCContent.REINFORCED_STONE_BUTTON.getKey(),
				SCContent.REINFORCED_POLISHED_BLACKSTONE_BUTTON.getKey());
		tag(BlockTags.STRIDER_WARM_BLOCKS).add(SCContent.FAKE_LAVA_BLOCK.getKey());
		tag(BlockTags.STANDING_SIGNS).addTag(SCTags.Blocks.SECRET_STANDING_SIGNS);
		tag(BlockTags.TERRACOTTA).addTag(SCTags.Blocks.REINFORCED_TERRACOTTA);
		tag(BlockTags.TRAPDOORS).add(SCContent.REINFORCED_IRON_TRAPDOOR.getKey(), SCContent.KEYPAD_TRAPDOOR.getKey(), SCContent.SCANNER_TRAPDOOR.getKey());
		tag(BlockTags.VIBRATION_RESONATORS).add(SCContent.REINFORCED_AMETHYST_BLOCK.getKey());
		tag(BlockTags.WALL_SIGNS).addTag(SCTags.Blocks.SECRET_WALL_SIGNS);
		tag(BlockTags.WALL_HANGING_SIGNS).addTag(SCTags.Blocks.SECRET_WALL_HANGING_SIGNS);
		tag(BlockTags.WALLS).addTag(SCTags.Blocks.REINFORCED_WALLS);
		tag(BlockTags.WITHER_SUMMON_BASE_BLOCKS).add(SCContent.REINFORCED_SOUL_SAND.getKey(), SCContent.REINFORCED_SOUL_SOIL.getKey());
		tag(BlockTags.WOODEN_FENCES).addTag(SCTags.Blocks.REINFORCED_WOODEN_FENCES);
		tag(BlockTags.WOOL).addTag(SCTags.Blocks.REINFORCED_WOOL);
		tag(BlockTags.WOOL_CARPETS).addTag(SCTags.Blocks.REINFORCED_WOOL_CARPETS);
		tag(BlockTags.ENABLES_BUBBLE_COLUMN_DRAG_DOWN).add(SCContent.REINFORCED_MAGMA_BLOCK.getKey());
		tag(BlockTags.ENABLES_BUBBLE_COLUMN_PUSH_UP).add(SCContent.REINFORCED_SOUL_SAND.getKey());
		tag(BlockTags.SUPPORTS_DRY_VEGETATION).addTag(SCTags.Blocks.REINFORCED_SAND).addTag(SCTags.Blocks.REINFORCED_TERRACOTTA);
		tag(BlockTags.SUPPORTS_SUGAR_CANE)
				.addTag(SCTags.Blocks.REINFORCED_DIRT)
				.addTag(SCTags.Blocks.REINFORCED_MUD)
				.addTag(SCTags.Blocks.REINFORCED_MOSS_BLOCKS)
				.addTag(SCTags.Blocks.REINFORCED_GRASS_BLOCKS)
				.addTag(SCTags.Blocks.REINFORCED_SAND);
		tag(BlockTags.SUPPORTS_BAMBOO)
				.addTag(SCTags.Blocks.REINFORCED_SAND)
				.addTag(SCTags.Blocks.REINFORCED_DIRT)
				.addTag(SCTags.Blocks.REINFORCED_MUD)
				.addTag(SCTags.Blocks.REINFORCED_MOSS_BLOCKS)
				.addTag(SCTags.Blocks.REINFORCED_GRASS_BLOCKS)
				.add(SCContent.REINFORCED_GRAVEL.getKey(), SCContent.SUSPICIOUS_GRAVEL_MINE.getKey());
		tag(BlockTags.SUPPORTS_SMALL_DRIPLEAF).add(SCContent.REINFORCED_CLAY.getKey()).add(SCContent.REINFORCED_MOSS_BLOCK.getKey());
		tag(BlockTags.SUPPORTS_BIG_DRIPLEAF).add(
				SCContent.REINFORCED_DIRT.getKey(),
				SCContent.REINFORCED_GRASS_BLOCK.getKey(),
				SCContent.REINFORCED_PODZOL.getKey(),
				SCContent.REINFORCED_COARSE_DIRT.getKey(),
				SCContent.REINFORCED_MYCELIUM.getKey(),
				SCContent.REINFORCED_ROOTED_DIRT.getKey(),
				SCContent.REINFORCED_MOSS_BLOCK.getKey(),
				SCContent.REINFORCED_MUD.getKey());
		tag(BlockTags.SUPPORTS_CACTUS).addTag(SCTags.Blocks.REINFORCED_SAND);
		tag(BlockTags.SUPPORTS_CHORUS_PLANT).add(SCContent.REINFORCED_END_STONE.getKey());
		tag(BlockTags.SUPPORTS_CHORUS_FLOWER).add(SCContent.REINFORCED_END_STONE.getKey());
		tag(BlockTags.SUPPORTS_NETHER_SPROUTS).addTag(SCTags.Blocks.REINFORCED_NYLIUM).add(SCContent.REINFORCED_SOUL_SOIL.getKey());
		tag(BlockTags.SUPPORTS_AZALEA).add(SCContent.REINFORCED_CLAY.getKey());
		tag(BlockTags.SUPPORTS_WARPED_FUNGUS).addTag(SCTags.Blocks.REINFORCED_NYLIUM).add(SCContent.REINFORCED_MYCELIUM.getKey()).add(SCContent.REINFORCED_SOUL_SOIL.getKey());
		tag(BlockTags.SUPPORTS_MANGROVE_PROPAGULE).add(SCContent.REINFORCED_CLAY.getKey());
		tag(BlockTags.SUPPORTS_NETHER_WART).add(SCContent.REINFORCED_SOUL_SAND.getKey());
		tag(BlockTags.SUPPORTS_WARPED_ROOTS).addTag(SCTags.Blocks.REINFORCED_NYLIUM).add(SCContent.REINFORCED_SOUL_SOIL.getKey());
		tag(BlockTags.SUPPORTS_WITHER_ROSE).add(SCContent.REINFORCED_NETHERRACK.getKey()).add(SCContent.REINFORCED_SOUL_SAND.getKey()).add(SCContent.REINFORCED_SOUL_SOIL.getKey());
		tag(BlockTags.SUPPORTS_COCOA).addTag(SCTags.Blocks.REINFORCED_JUNGLE_LOGS);
		tag(BlockTags.SUPPORTS_LILY_PAD).add(SCContent.REINFORCED_ICE.getKey());
		tag(BlockTags.SUPPORT_OVERRIDE_SNOW_LAYER).add(SCContent.REINFORCED_SOUL_SAND.getKey()).add(SCContent.REINFORCED_MUD.getKey());
		tag(BlockTags.CANNOT_SUPPORT_SEAGRASS).add(SCContent.REINFORCED_MAGMA_BLOCK.getKey());
		tag(BlockTags.CANNOT_SUPPORT_KELP).add(SCContent.REINFORCED_MAGMA_BLOCK.getKey());
		tag(BlockTags.CANNOT_SUPPORT_SNOW_LAYER).add(SCContent.REINFORCED_ICE.getKey()).add(SCContent.REINFORCED_PACKED_ICE.getKey());
		tag(BlockTags.OVERRIDES_MUSHROOM_LIGHT_REQUIREMENT).add(SCContent.REINFORCED_MYCELIUM.getKey()).add(SCContent.REINFORCED_PODZOL.getKey()).add(SCContent.REINFORCED_CRIMSON_NYLIUM.getKey()).add(SCContent.REINFORCED_WARPED_NYLIUM.getKey());
		tag(BlockTags.AZALEA_GROWS_ON)
				.addTag(SCTags.Blocks.REINFORCED_DIRT)
				.addTag(SCTags.Blocks.REINFORCED_MUD)
				.addTag(SCTags.Blocks.REINFORCED_MOSS_BLOCKS)
				.addTag(SCTags.Blocks.REINFORCED_GRASS_BLOCKS)
				.addTag(SCTags.Blocks.REINFORCED_SAND)
				.addTag(SCTags.Blocks.REINFORCED_TERRACOTTA)
				.add(SCContent.REINFORCED_SNOW_BLOCK.getKey());
		tag(BlockTags.SUPPORTS_VEGETATION)
				.addTag(SCTags.Blocks.REINFORCED_DIRT)
				.addTag(SCTags.Blocks.REINFORCED_MUD)
				.addTag(SCTags.Blocks.REINFORCED_MOSS_BLOCKS)
				.addTag(SCTags.Blocks.REINFORCED_GRASS_BLOCKS);
		//@formatter:on
		miningRelatedTags();

		//NeoForge tags
		tag(Tags.Blocks.CONCRETES).addTag(SCTags.Blocks.REINFORCED_CONCRETE);
		tag(Tags.Blocks.FENCE_GATES_WOODEN).addTag(SCTags.Blocks.REINFORCED_WOODEN_FENCE_GATES);
		tag(Tags.Blocks.GLAZED_TERRACOTTAS).addTag(SCTags.Blocks.REINFORCED_GLAZED_TERRACOTTA);

		//automatic
		TagAppender<Block> dragonImmune = tag(BlockTags.DRAGON_IMMUNE);
		TagAppender<Block> noRelocation = tag(Tags.Blocks.RELOCATION_NOT_SUPPORTED);
		TagAppender<Block> witherImmune = tag(BlockTags.WITHER_IMMUNE);

		for (DeferredHolder<Block, ? extends Block> ro : SCContent.BLOCKS.getEntries()) {
			Block block = ro.get();
			ResourceKey<Block> key = ro.getKey();

			if (block != SCContent.CHISELED_CRYSTAL_QUARTZ.get() && block != SCContent.CRYSTAL_QUARTZ_BLOCK.get() && block != SCContent.CRYSTAL_QUARTZ_PILLAR.get() && block != SCContent.CRYSTAL_QUARTZ_SLAB.get() && block != SCContent.CRYSTAL_QUARTZ_STAIRS.get() && block != SCContent.CRYSTAL_QUARTZ_BRICKS.get() && block != SCContent.SMOOTH_CRYSTAL_QUARTZ.get() && block != SCContent.SMOOTH_CRYSTAL_QUARTZ_STAIRS.get() && block != SCContent.SMOOTH_CRYSTAL_QUARTZ_SLAB.get()) {
				dragonImmune.add(key);
				witherImmune.add(key);
				noRelocation.add(key);
			}

			switch (block) {
				case ReinforcedSlabBlock _ when !woodenSlabs.contains(key) -> tag(SCTags.Blocks.REINFORCED_SLABS).add(key);
				case ReinforcedStairsBlock _ when !woodenStairs.contains(key) ->
						tag(SCTags.Blocks.REINFORCED_STAIRS).add(key);
				case ReinforcedWallBlock _ -> tag(SCTags.Blocks.REINFORCED_WALLS).add(key);
				default -> {
				}
			}
		}
	}

	private void miningRelatedTags() {
		//@formatter:off
		tag(BlockTags.MINEABLE_WITH_AXE).add(
				SCContent.CREAKING_HEART_MINE.getKey(),
				SCContent.REINFORCED_BOOKSHELF.getKey(),
				SCContent.REINFORCED_LADDER.getKey(),
				SCContent.REINFORCED_LECTERN.getKey(),
				SCContent.REINFORCED_BAMBOO_MOSAIC.getKey(),
				SCContent.REINFORCED_BAMBOO_MOSAIC_SLAB.getKey(),
				SCContent.REINFORCED_BAMBOO_MOSAIC_STAIRS.getKey(),
				SCContent.REINFORCED_CHISELED_BOOKSHELF.getKey())
			.addTag(SCTags.Blocks.REINFORCED_WOODEN_FENCE_GATES)
			.addTag(SCTags.Blocks.REINFORCED_LOGS)
			.addTag(SCTags.Blocks.REINFORCED_PLANKS)
			.addTag(SCTags.Blocks.SECRET_SIGNS)
			.addTag(SCTags.Blocks.REINFORCED_WOODEN_BUTTONS)
			.addTag(SCTags.Blocks.REINFORCED_WOODEN_FENCES)
			.addTag(SCTags.Blocks.REINFORCED_WOODEN_PRESSURE_PLATES)
			.addTag(SCTags.Blocks.REINFORCED_WOODEN_SHELVES)
			.addTag(SCTags.Blocks.REINFORCED_WOODEN_SLABS)
			.addTag(SCTags.Blocks.REINFORCED_WOODEN_STAIRS)
			.addTag(SCTags.Blocks.SECRET_HANGING_SIGNS)
			.addTag(SCTags.Blocks.REINFORCED_BAMBOO_BLOCKS);
		tag(BlockTags.MINEABLE_WITH_HOE).add(
				SCContent.REINFORCED_NETHER_WART_BLOCK.getKey(),
				SCContent.REINFORCED_WARPED_WART_BLOCK.getKey(),
				SCContent.REINFORCED_SHROOMLIGHT.getKey(),
				SCContent.REINFORCED_MOSS_BLOCK.getKey(),
				SCContent.REINFORCED_MOSS_CARPET.getKey(),
				SCContent.REINFORCED_PALE_MOSS_BLOCK.getKey(),
				SCContent.REINFORCED_PALE_MOSS_CARPET.getKey());
		tag(BlockTags.MINEABLE_WITH_PICKAXE).add(
				SCContent.ALARM.getKey(),
				SCContent.BLOCK_CHANGE_DETECTOR.getKey(),
				SCContent.BLOCK_POCKET_WALL.getKey(),
				SCContent.BLOCK_POCKET_MANAGER.getKey(),
				SCContent.BOUNCING_BETTY.getKey(),
				SCContent.CAGE_TRAP.getKey(),
				SCContent.CLAYMORE.getKey(),
				SCContent.FLOOR_TRAP.getKey(),
				SCContent.DISPLAY_CASE.getKey(),
				SCContent.GLOW_DISPLAY_CASE.getKey(),
				SCContent.FRAME.getKey(),
				SCContent.IMS.getKey(),
				SCContent.INVENTORY_SCANNER.getKey(),
				SCContent.KEY_PANEL_BLOCK.getKey(),
				SCContent.KEYCARD_LOCK.getKey(),
				SCContent.KEYCARD_READER.getKey(),
				SCContent.KEYPAD.getKey(),
				SCContent.KEYPAD_BARREL.getKey(),
				SCContent.KEYPAD_CHEST.getKey(),
				SCContent.KEYPAD_DOOR.getKey(),
				SCContent.KEYPAD_TRAPDOOR.getKey(),
				SCContent.KEYPAD_FURNACE.getKey(),
				SCContent.KEYPAD_SMOKER.getKey(),
				SCContent.KEYPAD_BLAST_FURNACE.getKey(),
				SCContent.MOTION_ACTIVATED_LIGHT.getKey(),
				SCContent.LASER_BLOCK.getKey(),
				SCContent.PANIC_BUTTON.getKey(),
				SCContent.PORTABLE_RADAR.getKey(),
				SCContent.PROJECTOR.getKey(),
				SCContent.PROTECTO.getKey(),
				SCContent.REINFORCED_DOOR.getKey(),
				SCContent.ELECTRIFIED_IRON_FENCE.getKey(),
				SCContent.ELECTRIFIED_IRON_FENCE_GATE.getKey(),
				SCContent.RETINAL_SCANNER.getKey(),
				SCContent.RIFT_STABILIZER.getKey(),
				SCContent.SCANNER_DOOR.getKey(),
				SCContent.SCANNER_TRAPDOOR.getKey(),
				SCContent.SECURE_TRADING_STATION.getKey(),
				SCContent.SECURITY_CAMERA.getKey(),
				SCContent.SONIC_SECURITY_SYSTEM.getKey(),
				SCContent.TROPHY_SYSTEM.getKey(),
				SCContent.SECURE_REDSTONE_INTERFACE.getKey(),
				SCContent.USERNAME_LOGGER.getKey(),
				SCContent.MINE.getKey(),
				SCContent.CRYSTAL_QUARTZ_SLAB.getKey(),
				SCContent.SMOOTH_CRYSTAL_QUARTZ.getKey(),
				SCContent.CHISELED_CRYSTAL_QUARTZ.getKey(),
				SCContent.CRYSTAL_QUARTZ_BLOCK.getKey(),
				SCContent.CRYSTAL_QUARTZ_BRICKS.getKey(),
				SCContent.CRYSTAL_QUARTZ_PILLAR.getKey(),
				SCContent.CRYSTAL_QUARTZ_STAIRS.getKey(),
				SCContent.SMOOTH_CRYSTAL_QUARTZ_STAIRS.getKey(),
				SCContent.SMOOTH_CRYSTAL_QUARTZ_SLAB.getKey(),
				SCContent.REINFORCED_CRYSTAL_QUARTZ_SLAB.getKey(),
				SCContent.REINFORCED_SMOOTH_CRYSTAL_QUARTZ.getKey(),
				SCContent.REINFORCED_CHISELED_CRYSTAL_QUARTZ.getKey(),
				SCContent.REINFORCED_CRYSTAL_QUARTZ_BLOCK.getKey(),
				SCContent.REINFORCED_CRYSTAL_QUARTZ_BRICKS.getKey(),
				SCContent.REINFORCED_CRYSTAL_QUARTZ_PILLAR.getKey(),
				SCContent.REINFORCED_CRYSTAL_QUARTZ_STAIRS.getKey(),
				SCContent.REINFORCED_SMOOTH_CRYSTAL_QUARTZ_STAIRS.getKey(),
				SCContent.REINFORCED_SMOOTH_CRYSTAL_QUARTZ_SLAB.getKey(),
				SCContent.STONE_MINE.getKey(),
				SCContent.DEEPSLATE_MINE.getKey(),
				SCContent.COBBLED_DEEPSLATE_MINE.getKey(),
				SCContent.COBBLESTONE_MINE.getKey(),
				SCContent.COAL_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_COAL_ORE_MINE.getKey(),
				SCContent.IRON_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_IRON_ORE_MINE.getKey(),
				SCContent.GOLD_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_GOLD_ORE_MINE.getKey(),
				SCContent.COPPER_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_COPPER_ORE_MINE.getKey(),
				SCContent.REDSTONE_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_REDSTONE_ORE_MINE.getKey(),
				SCContent.EMERALD_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_EMERALD_ORE_MINE.getKey(),
				SCContent.LAPIS_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_LAPIS_ORE_MINE.getKey(),
				SCContent.DIAMOND_ORE_MINE.getKey(),
				SCContent.DEEPSLATE_DIAMOND_ORE_MINE.getKey(),
				SCContent.NETHER_GOLD_ORE_MINE.getKey(),
				SCContent.QUARTZ_ORE_MINE.getKey(),
				SCContent.ANCIENT_DEBRIS_MINE.getKey(),
				SCContent.GILDED_BLACKSTONE_MINE.getKey(),
				SCContent.FURNACE_MINE.getKey(),
				SCContent.SMOKER_MINE.getKey(),
				SCContent.BLAST_FURNACE_MINE.getKey(),
				SCContent.NETHERRACK_MINE.getKey(),
				SCContent.END_STONE_MINE.getKey(),
				SCContent.REINFORCED_STONE.getKey(),
				SCContent.REINFORCED_GRANITE.getKey(),
				SCContent.REINFORCED_POLISHED_GRANITE.getKey(),
				SCContent.REINFORCED_DIORITE.getKey(),
				SCContent.REINFORCED_POLISHED_DIORITE.getKey(),
				SCContent.REINFORCED_ANDESITE.getKey(),
				SCContent.REINFORCED_POLISHED_ANDESITE.getKey(),
				SCContent.REINFORCED_COBBLESTONE.getKey(),
				SCContent.REINFORCED_LAPIS_BLOCK.getKey(),
				SCContent.REINFORCED_DISPENSER.getKey(),
				SCContent.REINFORCED_SANDSTONE.getKey(),
				SCContent.REINFORCED_CHISELED_SANDSTONE.getKey(),
				SCContent.REINFORCED_CUT_SANDSTONE.getKey(),
				SCContent.REINFORCED_GOLD_BLOCK.getKey(),
				SCContent.REINFORCED_IRON_BLOCK.getKey(),
				SCContent.REINFORCED_BRICKS.getKey(),
				SCContent.REINFORCED_MOSSY_COBBLESTONE.getKey(),
				SCContent.REINFORCED_OBSIDIAN.getKey(),
				SCContent.REINFORCED_DIAMOND_BLOCK.getKey(),
				SCContent.REINFORCED_COBBLESTONE_STAIRS.getKey(),
				SCContent.REINFORCED_STONE_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_NETHERRACK.getKey(),
				SCContent.REINFORCED_BASALT.getKey(),
				SCContent.REINFORCED_POLISHED_BASALT.getKey(),
				SCContent.REINFORCED_STONE_BRICKS.getKey(),
				SCContent.REINFORCED_MOSSY_STONE_BRICKS.getKey(),
				SCContent.REINFORCED_CRACKED_STONE_BRICKS.getKey(),
				SCContent.REINFORCED_CHISELED_STONE_BRICKS.getKey(),
				SCContent.HORIZONTAL_REINFORCED_IRON_BARS.getKey(),
				SCContent.REINFORCED_IRON_CHAIN.getKey(),
				SCContent.REINFORCED_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_STONE_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_NETHER_BRICKS.getKey(),
				SCContent.REINFORCED_NETHER_BRICK_FENCE.getKey(),
				SCContent.REINFORCED_NETHER_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_END_STONE.getKey(),
				SCContent.REINFORCED_SANDSTONE_STAIRS.getKey(),
				SCContent.REINFORCED_EMERALD_BLOCK.getKey(),
				SCContent.REINFORCED_REDSTONE_BLOCK.getKey(),
				SCContent.REINFORCED_HOPPER.getKey(),
				SCContent.REINFORCED_QUARTZ_BLOCK.getKey(),
				SCContent.REINFORCED_CHISELED_QUARTZ.getKey(),
				SCContent.REINFORCED_QUARTZ_PILLAR.getKey(),
				SCContent.REINFORCED_QUARTZ_STAIRS.getKey(),
				SCContent.REINFORCED_DROPPER.getKey(),
				SCContent.REINFORCED_IRON_TRAPDOOR.getKey(),
				SCContent.REINFORCED_PRISMARINE.getKey(),
				SCContent.REINFORCED_PRISMARINE_BRICKS.getKey(),
				SCContent.REINFORCED_DARK_PRISMARINE.getKey(),
				SCContent.REINFORCED_PRISMARINE_STAIRS.getKey(),
				SCContent.REINFORCED_PRISMARINE_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_DARK_PRISMARINE_STAIRS.getKey(),
				SCContent.REINFORCED_PRISMARINE_SLAB.getKey(),
				SCContent.REINFORCED_PRISMARINE_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_DARK_PRISMARINE_SLAB.getKey(),
				SCContent.REINFORCED_TERRACOTTA.getKey(),
				SCContent.REINFORCED_COAL_BLOCK.getKey(),
				SCContent.REINFORCED_RED_SANDSTONE.getKey(),
				SCContent.REINFORCED_CHISELED_RED_SANDSTONE.getKey(),
				SCContent.REINFORCED_CUT_RED_SANDSTONE.getKey(),
				SCContent.REINFORCED_RED_SANDSTONE_STAIRS.getKey(),
				SCContent.REINFORCED_NORMAL_STONE_SLAB.getKey(),
				SCContent.REINFORCED_SMOOTH_STONE_SLAB.getKey(),
				SCContent.REINFORCED_SANDSTONE_SLAB.getKey(),
				SCContent.REINFORCED_CUT_SANDSTONE_SLAB.getKey(),
				SCContent.REINFORCED_COBBLESTONE_SLAB.getKey(),
				SCContent.REINFORCED_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_STONE_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_NETHER_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_QUARTZ_SLAB.getKey(),
				SCContent.REINFORCED_RED_SANDSTONE_SLAB.getKey(),
				SCContent.REINFORCED_CUT_RED_SANDSTONE_SLAB.getKey(),
				SCContent.REINFORCED_PURPUR_SLAB.getKey(),
				SCContent.REINFORCED_SMOOTH_STONE.getKey(),
				SCContent.REINFORCED_SMOOTH_SANDSTONE.getKey(),
				SCContent.REINFORCED_SMOOTH_QUARTZ.getKey(),
				SCContent.REINFORCED_SMOOTH_RED_SANDSTONE.getKey(),
				SCContent.REINFORCED_PURPUR_BLOCK.getKey(),
				SCContent.REINFORCED_PURPUR_PILLAR.getKey(),
				SCContent.REINFORCED_PURPUR_STAIRS.getKey(),
				SCContent.REINFORCED_END_STONE_BRICKS.getKey(),
				SCContent.REINFORCED_MAGMA_BLOCK.getKey(),
				SCContent.REINFORCED_RED_NETHER_BRICKS.getKey(),
				SCContent.REINFORCED_BONE_BLOCK.getKey(),
				SCContent.REINFORCED_OBSERVER.getKey(),
				SCContent.REINFORCED_POLISHED_GRANITE_STAIRS.getKey(),
				SCContent.REINFORCED_SMOOTH_RED_SANDSTONE_STAIRS.getKey(),
				SCContent.REINFORCED_MOSSY_STONE_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_POLISHED_DIORITE_STAIRS.getKey(),
				SCContent.REINFORCED_MOSSY_COBBLESTONE_STAIRS.getKey(),
				SCContent.REINFORCED_END_STONE_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_STONE_STAIRS.getKey(),
				SCContent.REINFORCED_SMOOTH_SANDSTONE_STAIRS.getKey(),
				SCContent.REINFORCED_SMOOTH_QUARTZ_STAIRS.getKey(),
				SCContent.REINFORCED_GRANITE_STAIRS.getKey(),
				SCContent.REINFORCED_ANDESITE_STAIRS.getKey(),
				SCContent.REINFORCED_RED_NETHER_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_POLISHED_ANDESITE_STAIRS.getKey(),
				SCContent.REINFORCED_DIORITE_STAIRS.getKey(),
				SCContent.REINFORCED_POLISHED_GRANITE_SLAB.getKey(),
				SCContent.REINFORCED_SMOOTH_RED_SANDSTONE_SLAB.getKey(),
				SCContent.REINFORCED_MOSSY_STONE_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_POLISHED_DIORITE_SLAB.getKey(),
				SCContent.REINFORCED_MOSSY_COBBLESTONE_SLAB.getKey(),
				SCContent.REINFORCED_END_STONE_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_SMOOTH_SANDSTONE_SLAB.getKey(),
				SCContent.REINFORCED_SMOOTH_QUARTZ_SLAB.getKey(),
				SCContent.REINFORCED_GRANITE_SLAB.getKey(),
				SCContent.REINFORCED_ANDESITE_SLAB.getKey(),
				SCContent.REINFORCED_RED_NETHER_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_POLISHED_ANDESITE_SLAB.getKey(),
				SCContent.REINFORCED_DIORITE_SLAB.getKey(),
				SCContent.REINFORCED_LANTERN.getKey(),
				SCContent.REINFORCED_SOUL_LANTERN.getKey(),
				SCContent.REINFORCED_WARPED_NYLIUM.getKey(),
				SCContent.REINFORCED_CRIMSON_NYLIUM.getKey(),
				SCContent.REINFORCED_NETHERITE_BLOCK.getKey(),
				SCContent.REINFORCED_CRYING_OBSIDIAN.getKey(),
				SCContent.REINFORCED_BLACKSTONE.getKey(),
				SCContent.REINFORCED_BLACKSTONE_STAIRS.getKey(),
				SCContent.REINFORCED_BLACKSTONE_SLAB.getKey(),
				SCContent.REINFORCED_POLISHED_BLACKSTONE.getKey(),
				SCContent.REINFORCED_POLISHED_BLACKSTONE_BRICKS.getKey(),
				SCContent.REINFORCED_CRACKED_POLISHED_BLACKSTONE_BRICKS.getKey(),
				SCContent.REINFORCED_CHISELED_POLISHED_BLACKSTONE.getKey(),
				SCContent.REINFORCED_POLISHED_BLACKSTONE_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_POLISHED_BLACKSTONE_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_POLISHED_BLACKSTONE_STAIRS.getKey(),
				SCContent.REINFORCED_POLISHED_BLACKSTONE_SLAB.getKey(),
				SCContent.REINFORCED_POLISHED_BLACKSTONE_PRESSURE_PLATE.getKey(),
				SCContent.REINFORCED_CHISELED_NETHER_BRICKS.getKey(),
				SCContent.REINFORCED_CRACKED_NETHER_BRICKS.getKey(),
				SCContent.REINFORCED_QUARTZ_BRICKS.getKey(),
				SCContent.REINFORCED_TUFF.getKey(),
				SCContent.REINFORCED_CALCITE.getKey(),
				SCContent.REINFORCED_DRIPSTONE_BLOCK.getKey(),
				SCContent.REINFORCED_DEEPSLATE.getKey(),
				SCContent.REINFORCED_COBBLED_DEEPSLATE.getKey(),
				SCContent.REINFORCED_COBBLED_DEEPSLATE_STAIRS.getKey(),
				SCContent.REINFORCED_COBBLED_DEEPSLATE_SLAB.getKey(),
				SCContent.REINFORCED_POLISHED_DEEPSLATE.getKey(),
				SCContent.REINFORCED_POLISHED_DEEPSLATE_STAIRS.getKey(),
				SCContent.REINFORCED_POLISHED_DEEPSLATE_SLAB.getKey(),
				SCContent.REINFORCED_DEEPSLATE_TILES.getKey(),
				SCContent.REINFORCED_DEEPSLATE_TILE_STAIRS.getKey(),
				SCContent.REINFORCED_DEEPSLATE_TILE_SLAB.getKey(),
				SCContent.REINFORCED_DEEPSLATE_BRICKS.getKey(),
				SCContent.REINFORCED_DEEPSLATE_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_DEEPSLATE_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_CHISELED_DEEPSLATE.getKey(),
				SCContent.REINFORCED_CRACKED_DEEPSLATE_BRICKS.getKey(),
				SCContent.REINFORCED_CRACKED_DEEPSLATE_TILES.getKey(),
				SCContent.REINFORCED_SMOOTH_BASALT.getKey(),
				SCContent.REINFORCED_RAW_IRON_BLOCK.getKey(),
				SCContent.REINFORCED_RAW_COPPER_BLOCK.getKey(),
				SCContent.REINFORCED_RAW_GOLD_BLOCK.getKey(),
				SCContent.REINFORCED_ICE.getKey(),
				SCContent.REINFORCED_PACKED_ICE.getKey(),
				SCContent.REINFORCED_BLUE_ICE.getKey(),
				SCContent.REINFORCED_PISTON.getKey(),
				SCContent.REINFORCED_STICKY_PISTON.getKey(),
				SCContent.REINFORCED_PISTON_HEAD.getKey(),
				SCContent.REINFORCED_AMETHYST_BLOCK.getKey(),
				SCContent.REINFORCED_MUD_BRICKS.getKey(),
				SCContent.REINFORCED_MUD_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_MUD_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_PACKED_MUD.getKey(),
				SCContent.REINFORCED_TUFF_SLAB.getKey(),
				SCContent.REINFORCED_TUFF_STAIRS.getKey(),
				SCContent.REINFORCED_TUFF_WALL.getKey(),
				SCContent.REINFORCED_CHISELED_TUFF.getKey(),
				SCContent.REINFORCED_POLISHED_TUFF.getKey(),
				SCContent.REINFORCED_POLISHED_TUFF_SLAB.getKey(),
				SCContent.REINFORCED_POLISHED_TUFF_STAIRS.getKey(),
				SCContent.REINFORCED_POLISHED_TUFF_WALL.getKey(),
				SCContent.REINFORCED_TUFF_BRICKS.getKey(),
				SCContent.REINFORCED_TUFF_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_TUFF_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_TUFF_BRICK_WALL.getKey(),
				SCContent.REINFORCED_CHISELED_TUFF_BRICKS.getKey(),
				SCContent.REINFORCED_RESIN_BRICKS.getKey(),
				SCContent.REINFORCED_RESIN_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_RESIN_BRICK_WALL.getKey(),
				SCContent.REINFORCED_RESIN_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_CHISELED_RESIN_BRICKS.getKey(),
				SCContent.REINFORCED_STONE_BUTTON.getKey(),
				SCContent.REINFORCED_POLISHED_BLACKSTONE_BUTTON.getKey(),
				SCContent.REINFORCED_SULFUR.getKey(),
				SCContent.REINFORCED_SULFUR_SLAB.getKey(),
				SCContent.REINFORCED_SULFUR_STAIRS.getKey(),
				SCContent.REINFORCED_SULFUR_WALL.getKey(),
				SCContent.REINFORCED_POLISHED_SULFUR.getKey(),
				SCContent.REINFORCED_POLISHED_SULFUR_SLAB.getKey(),
				SCContent.REINFORCED_POLISHED_SULFUR_STAIRS.getKey(),
				SCContent.REINFORCED_POLISHED_SULFUR_WALL.getKey(),
				SCContent.REINFORCED_SULFUR_BRICKS.getKey(),
				SCContent.REINFORCED_SULFUR_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_SULFUR_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_SULFUR_BRICK_WALL.getKey(),
				SCContent.REINFORCED_CHISELED_SULFUR.getKey(),
				SCContent.REINFORCED_CINNABAR.getKey(),
				SCContent.REINFORCED_CINNABAR_SLAB.getKey(),
				SCContent.REINFORCED_CINNABAR_STAIRS.getKey(),
				SCContent.REINFORCED_CINNABAR_WALL.getKey(),
				SCContent.REINFORCED_POLISHED_CINNABAR.getKey(),
				SCContent.REINFORCED_POLISHED_CINNABAR_SLAB.getKey(),
				SCContent.REINFORCED_POLISHED_CINNABAR_STAIRS.getKey(),
				SCContent.REINFORCED_POLISHED_CINNABAR_WALL.getKey(),
				SCContent.REINFORCED_CINNABAR_BRICKS.getKey(),
				SCContent.REINFORCED_CINNABAR_BRICK_SLAB.getKey(),
				SCContent.REINFORCED_CINNABAR_BRICK_STAIRS.getKey(),
				SCContent.REINFORCED_CINNABAR_BRICK_WALL.getKey(),
				SCContent.REINFORCED_CHISELED_CINNABAR.getKey(),
				SCContent.REINFORCED_POTENT_SULFUR.getKey())
		.addTag(SCTags.Blocks.REINFORCED_BARS)
		.addTag(SCTags.Blocks.REINFORCED_WALLS)
		.addTag(SCTags.Blocks.REINFORCED_CAULDRONS)
		.addAll(keysFromCollection(SCContent.REINFORCED_DYED_TERRACOTTA))
		.addAll(keysFromCollection(SCContent.REINFORCED_GLAZED_TERRACOTTA))
		.addAll(keysFromCollection(SCContent.REINFORCED_CONCRETE))
		.addAll(keysFromCollection(SCContent.REINFORCED_COPPER_BLOCK))
		.addAll(keysFromCollection(SCContent.REINFORCED_CUT_COPPER))
		.addAll(keysFromCollection(SCContent.REINFORCED_CUT_COPPER_STAIRS))
		.addAll(keysFromCollection(SCContent.REINFORCED_CUT_COPPER_SLAB))
		.addAll(keysFromCollection(SCContent.REINFORCED_CHISELED_COPPER))
		.addAll(keysFromCollection(SCContent.REINFORCED_COPPER_GRATE))
		.addAll(keysFromCollection(SCContent.REINFORCED_COPPER_BULB))
		.addAll(keysFromCollection(SCContent.REINFORCED_LIGHTNING_ROD))
		.addAll(keysFromCollection(SCContent.REINFORCED_COPPER_CHAIN))
		.addAll(keysFromCollection(SCContent.REINFORCED_COPPER_LANTERN));
		tag(BlockTags.MINEABLE_WITH_SHOVEL).add(
				SCContent.DIRT_MINE.getKey(),
				SCContent.GRAVEL_MINE.getKey(),
				SCContent.SAND_MINE.getKey(),
				SCContent.SUSPICIOUS_GRAVEL_MINE.getKey(),
				SCContent.SUSPICIOUS_SAND_MINE.getKey(),
				SCContent.REINFORCED_CLAY.getKey(),
				SCContent.REINFORCED_DIRT.getKey(),
				SCContent.REINFORCED_COARSE_DIRT.getKey(),
				SCContent.REINFORCED_PODZOL.getKey(),
				SCContent.REINFORCED_GRASS_BLOCK.getKey(),
				SCContent.REINFORCED_GRAVEL.getKey(),
				SCContent.REINFORCED_MYCELIUM.getKey(),
				SCContent.REINFORCED_SAND.getKey(),
				SCContent.REINFORCED_RED_SAND.getKey(),
				SCContent.REINFORCED_SNOW_BLOCK.getKey(),
				SCContent.REINFORCED_SOUL_SAND.getKey(),
				SCContent.REINFORCED_DIRT_PATH.getKey(),
				SCContent.REINFORCED_SOUL_SOIL.getKey(),
				SCContent.REINFORCED_ROOTED_DIRT.getKey(),
				SCContent.REINFORCED_MUD.getKey());
		tag(BlockTags.NEEDS_DIAMOND_TOOL).add(
				SCContent.PROTECTO.getKey(),
				SCContent.REINFORCED_OBSIDIAN.getKey(),
				SCContent.REINFORCED_CRYING_OBSIDIAN.getKey(),
				SCContent.REINFORCED_NETHERITE_BLOCK.getKey());
		tag(BlockTags.NEEDS_IRON_TOOL).add(
				SCContent.REINFORCED_DIAMOND_BLOCK.getKey(),
				SCContent.REINFORCED_EMERALD_BLOCK.getKey(),
				SCContent.REINFORCED_GOLD_BLOCK.getKey(),
				SCContent.REINFORCED_RAW_GOLD_BLOCK.getKey());
		tag(BlockTags.NEEDS_STONE_TOOL).add(
				SCContent.BOUNCING_BETTY.getKey(),
				SCContent.CAGE_TRAP.getKey(),
				SCContent.CLAYMORE.getKey(),
				SCContent.FLOOR_TRAP.getKey(),
				SCContent.IMS.getKey(),
				SCContent.DISPLAY_CASE.getKey(),
				SCContent.GLOW_DISPLAY_CASE.getKey(),
				SCContent.FRAME.getKey(),
				SCContent.KEY_PANEL_BLOCK.getKey(),
				SCContent.KEYPAD.getKey(),
				SCContent.KEYPAD_BARREL.getKey(),
				SCContent.KEYPAD_CHEST.getKey(),
				SCContent.KEYPAD_FURNACE.getKey(),
				SCContent.KEYPAD_SMOKER.getKey(),
				SCContent.KEYPAD_BLAST_FURNACE.getKey(),
				SCContent.MOTION_ACTIVATED_LIGHT.getKey(),
				SCContent.PORTABLE_RADAR.getKey(),
				SCContent.PROJECTOR.getKey(),
				SCContent.RIFT_STABILIZER.getKey(),
				SCContent.SECURITY_CAMERA.getKey(),
				SCContent.SONIC_SECURITY_SYSTEM.getKey(),
				SCContent.TROPHY_SYSTEM.getKey(),
				SCContent.MINE.getKey(),
				SCContent.REINFORCED_IRON_BLOCK.getKey(),
				SCContent.REINFORCED_RAW_IRON_BLOCK.getKey(),
				SCContent.REINFORCED_LAPIS_BLOCK.getKey(),
				SCContent.REINFORCED_RAW_COPPER_BLOCK.getKey())
		.addAll(keysFromCollection(SCContent.REINFORCED_COPPER_BLOCK))
		.addAll(keysFromCollection(SCContent.REINFORCED_CUT_COPPER))
		.addAll(keysFromCollection(SCContent.REINFORCED_CUT_COPPER_STAIRS))
		.addAll(keysFromCollection(SCContent.REINFORCED_CUT_COPPER_SLAB))
		.addAll(keysFromCollection(SCContent.REINFORCED_CHISELED_COPPER))
		.addAll(keysFromCollection(SCContent.REINFORCED_COPPER_GRATE))
		.addAll(keysFromCollection(SCContent.REINFORCED_COPPER_BULB))
		.addAll(keysFromCollection(SCContent.REINFORCED_LIGHTNING_ROD));
	}

	@Override
	public String getName() {
		return "SecurityCraft Block Tags";
	}

	private static Stream<ResourceKey<Block>> keysFromCollection(ColorCollection<? extends DeferredBlock<? extends Block>> collection) {
		return collection.asList().stream().map(DeferredHolder::getKey);
	}

	private static Stream<ResourceKey<Block>> keysFromCollection(WeatheringCopperCollection.ByState<? extends DeferredBlock<? extends Block>> collection) {
		Builder<ResourceKey<Block>> builder = ImmutableList.builderWithExpectedSize(4);

		collection.forEach(e -> builder.add(e.getKey()));
		return builder.build().stream();
	}
}
