blank_issues_enabled: false
contact_links:
  - name: Help & Suggestions (SecurityCraft Discord)
    url: https://discord.gg/U8DvBAW
    about: The best place to receive quick answers to any questions, post feature requests, and anything else you may have.