blank_issues_enabled: false
contact_links:
  - name: SecurityCraft Discord
    url: https://discord.gg/U8DvBAW
    about: The best place to receive quick answers to any questions, any feature requests, and etc... you may have