package net.geforcemods.securitycraft;

import net.geforcemods.securitycraft.blocks.mines.BlockMine;
import net.geforcemods.securitycraft.items.ItemModule;
import net.geforcemods.securitycraft.util.Reinforced;
import net.minecraft.block.Block;
import net.minecraft.item.Item;

public class SCContent
{
	//Blocks
	public static Block alarm;
	public static Block alarmLit;
	public static Block bogusLava;
	public static Block bogusLavaFlowing;
	public static Block bogusWater;
	public static Block bogusWaterFlowing;
	public static Block bouncingBetty;
	public static Block cageTrap;
	public static Block claymoreActive;
	public static Block claymoreDefused;
	public static Block cobblestoneMine;
	public static Block deactivatedCageTrap;
	public static Block diamondOreMine;
	public static Block dirtMine;
	public static Block frame;
	public static Block furnaceMine;
	public static Block gravelMine;
	public static Block ims;
	public static Block inventoryScanner;
	public static Block inventoryScannerField;
	public static Block ironFence;
	public static Block ironTrapdoor;
	public static Block keycardReader;
	public static Block keypad;
	public static Block keypadChest;
	public static Block keypadFurnace;
	public static Block laserBlock;
	public static Block laserField;
	public static Block motionActivatedLightOff;
	public static Block motionActivatedLightOn;
	public static Block panicButton;
	public static Block portableRadar;
	public static Block protecto;
	@Reinforced public static Block reinforcedBrick;
	@Reinforced public static Block reinforcedCarpet;
	@Reinforced public static Block reinforcedCobblestone;
	@Reinforced public static Block reinforcedCompressedBlocks;
	@Reinforced public static Block reinforcedDirt;
	public static Block reinforcedDirtSlab;
	public static Block reinforcedDoor;
	public static Block reinforcedDoubleDirtSlab;
	public static Block reinforcedDoubleStoneSlabs;
	public static Block reinforcedDoubleWoodSlabs;
	@Reinforced public static Block reinforcedEndStone;
	public static Block reinforcedFencegate;
	@Reinforced public static Block reinforcedGlass;
	@Reinforced public static Block reinforcedGlassPane;
	@Reinforced public static Block reinforcedGlowstone;
	@Reinforced public static Block reinforcedGravel;
	@Reinforced public static Block reinforcedHardenedClay;
	@Reinforced public static Block reinforcedIronBars;
	@Reinforced public static Block reinforcedMetals;
	@Reinforced public static Block reinforcedMossyCobblestone;
	@Reinforced public static Block reinforcedNetherBrick;
	@Reinforced public static Block reinforcedNetherrack;
	@Reinforced public static Block reinforcedNewLogs;
	@Reinforced public static Block reinforcedObsidian;
	@Reinforced public static Block reinforcedOldLogs;
	@Reinforced public static Block reinforcedQuartz;
	@Reinforced public static Block reinforcedSand;
	@Reinforced public static Block reinforcedSandstone;
	@Reinforced public static Block reinforcedStainedGlass;
	@Reinforced public static Block reinforcedStainedGlassPanes;
	@Reinforced public static Block reinforcedStainedHardenedClay;
	public static Block reinforcedStairsAcacia;
	public static Block reinforcedStairsBirch;
	public static Block reinforcedStairsBrick;
	public static Block reinforcedStairsCobblestone;
	public static Block reinforcedStairsDarkoak;
	public static Block reinforcedStairsJungle;
	public static Block reinforcedStairsNetherBrick;
	public static Block reinforcedStairsOak;
	public static Block reinforcedStairsQuartz;
	public static Block reinforcedStairsSandstone;
	public static Block reinforcedStairsSpruce;
	public static Block reinforcedStairsStone;
	public static Block reinforcedStairsStoneBrick;
	@Reinforced public static Block reinforcedStone;
	@Reinforced public static Block reinforcedStoneBrick;
	public static Block reinforcedStoneSlabs;
	@Reinforced public static Block reinforcedWoodPlanks;
	public static Block reinforcedWoodSlabs;
	@Reinforced public static Block reinforcedWool;
	public static Block retinalScanner;
	public static Block sandMine;
	public static Block scannerDoor;
	public static Block secretSignStanding;
	public static Block secretSignWall;
	public static Block securityCamera;
	public static Block stoneMine;
	public static Block trackMine;
	public static Block usernameLogger;
	public static BlockMine mine;
	public static BlockMine mineCut;

	//Items
	public static Item adminTool;
	public static Item briefcase;
	public static Item cameraMonitor;
	public static Item codebreaker;
	public static Item fLavaBucket;
	public static Item fWaterBucket;
	public static Item keycards;
	public static Item keyPanel;
	public static Item reinforcedDoorItem;
	public static Item remoteAccessMine;
	public static Item scannerDoorItem;
	public static Item scManual;
	public static Item secretSignItem;
	public static Item sentry;
	public static Item taser;
	public static Item taserPowered;
	public static Item universalBlockModifier;
	public static Item universalBlockReinforcerLvL1;
	public static Item universalBlockReinforcerLvL2;
	public static Item universalBlockReinforcerLvL3;
	public static Item universalBlockRemover;
	public static Item universalKeyChanger;
	public static Item universalOwnerChanger;
	public static Item wireCutters;

	//Modules
	public static ItemModule blacklistModule;
	public static ItemModule disguiseModule;
	public static ItemModule harmingModule;
	public static ItemModule redstoneModule;
	public static ItemModule smartModule;
	public static ItemModule storageModule;
	public static ItemModule whitelistModule;
}
